cloud-barista/cb-spider

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VNetworkHandler.go
cloud-control-manager/cloud-driver/interfaces/resources/VNetworkHandler.go

- VPC는 외부에는 숨기고 내부에서 자동으로 CB Default Virtual Network("CB-VNet")을 생성및 삭제하는 방식의 변경될 개발 방안의 버전 적용
- VNetworkHandler I/F의 VNetworkInfo 구조체에 Id와 SubnetId가 존재해서 Id의 용도를 SubnetId가 아닌 VpcId로 사용했음.
- ListVNetwork() : 여러 개의 VPC에 속한 Subnet 목록을 조회할 것인지 CB-VNet에 속한 서브넷만 조회할 것인지 결정 필요. (메인이 서브넷이고 CB-VNet은 숨은 개념이라 구현은 CB-VNet하위만 조회하도록 했음.)
- CB Default Virtual Network를 자동으로 생성할 때 CIDR 정보는 Subnet 생성 요청 정보의 CIDR의 앞 16바이트로 생성하도록 구현 함.(AWS에서 사용 가능한 최대 서브넷 크기가 /16)
(예) "192.168.100.1/24"로 서브넷 생성을 요청하면 CB-VNet이 없는 경우 "192.168.0.0/16"으로 VPC를 자동 생성함.
- 마지막 서브넷 삭제시 CB-Vnet 자동 삭제됨.
- Test_Resources.go의 handleVNetwork()에서 테스트 가능
- 서브넷 생성 시 조회 & 삭제 테스트 편의를 위해 생성된 Subnet ID를 조회할 대상으로 자동 설정함.
- 서브넷 목록 조회 시조회 & 삭제 테스트 편의를 위해 조회된 목록의 첫번째 Subnet ID를 조회할 대상으로 자동 설정함.
- 서브넷 생성 테스트는 CIDR 범주가 있어서 실행시 마다 handleVNetwork()의 소스 …

CB-Net 방식의 VNetworkHandler 구현 완료

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/KeyPairHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VNetworkHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VNicHandler.go
cloud-control-manager/cloud-driver/interfaces/new-resources/VNicHandler.go
cloud-control-manager/cloud-driver/interfaces/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/interfaces/resources/VNetworkHandler.go

2차 인터페이스 적용완료
- VNetworkHandler.go 적용 완료
--> 내부적으로 CB전용 VPC와 Subnet을 생성&삭제함.
- ImageHandler.go 적용 완료
--> amazon소유의 퍼블릭 AMI 목록과 Get만 구현(삭제 미구현)
- KeyPairHandler.go 적용 완료
--> Test 샘플은 "CB-KeyPairTest" 키페어를 생성 & 조회 & 삭제 함.
- VNicHandler.go 2차 인터페이스 방식은 적용완료 …
--> VPC와 Subnet 자동 조회&생성 로직 구현 필요해서 다른 곳에선 동작 안함
--> Subnet 정보를 전달받지 않기 때문에 VNicHandler에서 VNetworkHandler와 연계해서
VPC와 Subnet을 자동으로 가져오거나 생성하는 로직을 반영해야 함.
- 다른 핸들러들도 VNicHandler와 비슷하게 내부에서 VPC 정보를 자동으로 가져오는 기능을 넣어야 해서 잠시 보류

2차 인터페이스 일부 적용완료

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/CommonAwsFunc.go
cloud-control-manager/cloud-driver/drivers/aws/resources/PublicIPHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go
cloud-control-manager/cloud-driver/interfaces/new-resources/PublicIPHandler.go

PublicIPHandler.go 2차 인터페이스 반영 완료
개정안에 맞게 Public**IP 기반에서** PublicIP **ID**("**AllocationId**") 기반으로 로직 변경
- PublicIP 생성 시 Name 태그 설정 로직 반영
- PublicIP 생성 로직에서 생성된 IP를 VM에 할당하는 기능 제거
→ VM 생성 시 전달 받은  PublicIP ID를 이용해서 할당하는 방식으로 변경 됨
[참고] PublicIPInfo 구조체에서 Id string 필드가 사라져서 Key&Value의 “AssociationId”키에 값을 저장해서 리턴 함.
**VM 생성 요청 시 PublicIPID 값으로 Key&Value의 AssociationId Key에 저장된 값을 전달해야 함.**
**[사용 예시]**
Public IP 생성
reqInfo := irs.PublicIPReqInfo{Name: "mcloud-barista-eip-test"}
result, err := handler.CreatePublicIP(reqInfo)
목록 조회
result, err := handler.ListPublicIP()
정보 조회
result, err := handler.GetPublicIP("eipalloc-06a67a15fda999ad7")
PublicIP 삭제
result, err := handler.DeletePublicIP("eipalloc-06a67a15fda999ad7")

PublicIPHandler.go 2차 인터페이스 반영 완료

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/CommonAwsFunc.go
cloud-control-manager/cloud-driver/drivers/aws/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VNetworkHandler.go
cloud-control-manager/cloud-driver/interfaces/new-resources/SecurityHandler.go
cloud-control-manager/cloud-driver/interfaces/resources/SecurityHandler.go

- 바뀔 2차 공통 인터페이스의 Port정보가 Int64가 아닌 string 타입이라서 1차 인터페이스 타입도 String 타입으로 변경했음. (interfaces/resources/**SecurityHandler.go**)
FromPort   **string**
ToPort     **string**
- 보안 그룹 생성 시 네트워크 정보는 내부에서 조회해서 사용하도록 수정 함. (VPC이름 : "CB-VNet")
생성된 VPC가 없을 경우 자동으로 생성하지만 현재는 VPC까지만 자동생성하고 있음.
**아직 서브넷은 자동으로 생성하지 않기 때문에 테스트를 위해선 "CB-VNet"이름의 VPC를 생성하고 서브넷을 하나 생성해줘야 함. ("CB-VNet-Subnet")**
(편하게는 VNetworkHandler.go를 이용해서 생성해도 됨.)
**[사용 예시]**
**보안그룹 생성**
securityReqInfo := irs.SecurityReqInfo{
Name: "sgtest2-mcloub-barista",
SecurityRules: &[]irs.SecurityRuleInfo{ //보안 정책 설정
{
FromPort:   "80",
ToPort:     "80",
IPProtocol: "tcp",
Direction:  "inbound",
},
{
FromPort:   "8080",
ToPort:     "8080",
IPProtocol: "tcp",
Direction:  "inbound",
},
{
FromPort:   "443",
ToPort:     "443",
IPProtocol: "tcp", …

SecurityHandler.go 2차 로직 반영 완료

---

cloud-control-manager/cloud-driver/drivers/aws/AwsDriver.go
cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/main/Test_VM.go
cloud-control-manager/cloud-driver/drivers/aws/resources/CommonAwsFunc.go
cloud-control-manager/cloud-driver/drivers/aws/resources/PublicIPHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VNetworkHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VNicHandler.go

- VNicHandler.go / VNetworkHandler.go / SecurityHandler.go에서 VPC & Subnet 정보가 필요한 경우
자동으로 생성및 삭제하도록 구현 했지만 호출 상황에 따라서는 문제 소지가 있어서
Createxxx 함수에서만 자동으로 생성하고 조회의 경우 생성하지 않도록 수정
삭제의 경우도 비슷하게 체크 범주(VNic이 전부 삭제되어도 보안 그룹은 남아 있는지 함께 체크)가 커서 일단 VNetworkHandler.go의 삭제 요청이 있는 경우에만 VPC가 자동으로 삭제되도록 수정함.
[AWS VM핸들러 이슈]
- 사용자가 생성한 VPC는 기본적으로 외부와의 인터넷이 단절된 상태로 생성됨.
즉, 사용자가 생성한 VPC에는 PublicIP를 할당할 수 없기 때문에
PublicIP를 할당 할 수 있도록 외부와의 인터넷이 가능하도록 생성된 VPC의 라우팅 구성이 필요함.
(예: 생성된 VPC에 인터넷게이트웨이를 생성 후 연결)
- VPC 생성시 IGW(인터넷게이트웨이) 생성및 연결 로직을 반영 예정이며...
현재는 자동으로 생성된 CB-Net VPC에 수작업으로 IGW를 연결해야 VM 생성시 Public IP가 할당됨.

2차 인터페이스 반영 완료

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/PublicIPHandler.go
cloud-control-manager/cloud-driver/interfaces/resources/PublicIPHandler.go

출력된 정보에 Name 값이 없으면 불편 할 수 있어서 편의를 위해 Name 정보는 KeyValueList에 전달 함.

PublicIP 핸들러의 정보조회 시 Name 필드에 Name Tag대신 AllocationId를 리턴 함.

---

cloud-control-manager/cloud-driver/drivers/aws/resources/KeyPairHandler.go

서버에 존재하지 않는 KeyPair 삭제 시 True대신 False 리턴을 희망해서
KeyPair 삭제전 삭제 할 KeyPair가 서버에 존재하는지 체크로직을 추가함.

존재하지 않는 키페어 검증 루틴 추가 (bug#37)

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/PublicIPHandler.go

PublicIp 조회시 AWS API의 에러가 없는 경우 "PublicIP NotFound" 예외 메시지를 던지도록 기능 추가 (#43 Bug에 대한 조치)
#43 Bug: GET aws publicip with invalid `eipalloc` ID returns an empty JSON object, not an error message

[#43 Bug Fix] PublicIp 조회시 AWS API의 에러가 없는 경우 "PublicIP NotFound" 예외 메시지 추가

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_VM.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go

- VM 생성시 전달 받은 vNic Id가 있으면 Attach하도록 기능 추가
--> 향후 CB인터페이스 변경 및 VNetworkHandler.go와 VMHandler.go간의 기능 파악이 용이하도록
VM 생성 시 vNic Id가 전달되면 생성된 VM에 전달 받은 vNic을 추가하는 로직 추가 함.
**[이슈]** 이 형태로 지원할 경우 CB Interface의 경우 **PrivateIP 필드는 배열이 아닌 단순 string으로 문자열이지만...**
**vNic을 전달 받아서 추가할 경우 최소한 vNic이 2개 이상이 되기 때문에 응답도 Array가됨.**
Array 타입으로 변경하거나 Array를 일일이 String으로 변환해서 CB응답으로 리턴해도되지만
아직 미정인 부분이라 Array를 String으로 변환하지 않고 기존 로직 그대로 첫 번째 IP만 리턴하도록했음.
따라서, vNic Id가 있을 때와 없을 때의 차이는 AWS Console에서 생성된 VM의 Private IP쪽을 체크하면 됨.(또는 AWS 콘솔의 네트워크인터페이스 관리 페이지에서 체크해도 됨)

- VM 생성시 전달 받은 vNic Id가 있으면 Attach하도록 기능 추가

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_VM.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go

AWS VMStatus를 CB VMStatus로 치환
[예외1] Pending은 VM 생성 / 재시작시 발생하지만 VM 생성 시점에서는 확인이 안되고 겹치기 때문에 Resuming으로 처리
[예외2] Rebooting은 맵핑은 했지만 너무 빨라서 확인 못 했음. (Running만 리턴됨)
[변환 규칙]
pending		--> Resuming
running		--> running
stopping		--> Suspending
stopped		--> Suspended
Rebooting 	--> Rebooting
shutting-down	--> Terminating
Terminated 	--> Terminated

AWS VMStatus를 CB VMStatus로 치환

---

api-runtime/rest-runtime/test/azure/security/create-test.sh
api-runtime/rest-runtime/test/azure/vm/get-test.sh
api-runtime/rest-runtime/test/azure/vm/start-test.sh
cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/azure/resources/CommonAzureFunc.go
cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go

- Azure VM 생성 시 VNicId 파라미터 포맷 변경 (Id->Name)
curl -X POST http://$RESTSERVER:1024/vm?connection_name=azure-config01 -H 'Content-Type: application/json' -d '{
"VMName": "CBVm",
"ImageId": "Canonical:UbuntuServer:18.04-LTS:18.04.201804262",
**"NetworkInterfaceId": "CB-VNic",**
"VMSpecId": "Standard_B1ls",
"VMUserId": "cb-user",
"KeyPairName" : "CB-Keypair"
}'
- Azure VM Mapping 정보 추가 (PrivateIP, PublicIP)
- Azure SecurityGroup 생성 시 파라미터 옵션 변경 (FromPort-ToPort)
curl -X POST http://$RESTSERVER:1024/securitygroup?connection_name=azure-config01 -H 'Content-Type: application/json' -d '{
"Name": "CB-SecGroup",
"SecurityRules": [
**{"FromPort": "0", "ToPort" : "65535", "IPProtocol" : "tcp", "Direction" : "inbound"}**
]
}'

Azure VM 생성 파라미터 포맷 변경 및 SecurityGroup 옵션 변경

---

cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go

- Azure 리소스 핸들러 호출 시 (CRUD) ResourceGroup 존재 여부 체크 및 자동 생성 기능 추가
cim-insert-test.sh
curl -X POST http://$RESTSERVER:1024/region -H 'Content-Type: application/json' -d '{"RegionName":"azure-region01","ProviderName":"AZURE", "KeyValueInfoList": [{"Key":"location", "Value":"koreacentral"}, **{"Key":"ResourceGroup", "Value":"CB-GROUP2"}**]}'

Azure 리소스 핸들러 호출 시 ResourceGroup 존재 여부 체크 및 자동 생성 기능 추가

---

api-runtime/rest-runtime/test/openstack/vm/get-status-test.sh
api-runtime/rest-runtime/test/openstack/vm/get-test.sh
api-runtime/rest-runtime/test/openstack/vm/list-status-test.sh
api-runtime/rest-runtime/test/openstack/vm/list-test.sh
api-runtime/rest-runtime/test/openstack/vm/reboot-test.sh
api-runtime/rest-runtime/test/openstack/vm/resume-test.sh
api-runtime/rest-runtime/test/openstack/vm/start-test.sh
api-runtime/rest-runtime/test/openstack/vm/suspend-test.sh
api-runtime/rest-runtime/test/openstack/vm/terminate-test.sh
cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go

- Azure VMStatus 예외처리 및 주석 추가
- OpenStack VMStatus 매핑 적용
- OpenStack StartVM 관련 bash 예제코드 추가 (start-test.sh)
-------
** OpenStack VM 생성 테스트 시 리소스 이름 정보
**-- ImageId = ubuntu16.04
-- VirtualNetworkId(서브넷 ID와 매핑) = CB-Subnet
-- SecurityGroupIds = CB-SecGroup
-- VMSpecId = m1.small
-- KeyPairName(Name이 ID 처럼 사용) =  CB-KeyPair
-- PublicIPId(IP가 ID 처럼 사용) = 182.252.135.78**
curl -X POST http://$RESTSERVER:1024/vm?connection_name=openstack-config01 -H 'Content-Type: application/json' -d '{
"VMName": "CBVm",
"ImageId": "c14a9728-eb03-4813-9e1a-8f57fe62b4fb",
"VirtualNetworkId": "bb64d667-6ac7-420e-a0a1-17a32951161d",
"SecurityGroupIds": [
"38c71c09-f8d8-4197-afd8-1a067a760e24"
],
"VMSpecId": "ba7c426b-29b4-4e6f-833c-8c36b8566c37",
"KeyPairName": "CB-KeyPair",
"PublicIPId": "182.252.135.78"
}' …

OpenStack VMStatus 매핑 적용

---

cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Vm.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/CommonHandler.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/VNetworkHandler.go

- VNetworkHandler 기능 변경
-- 입력 받은 Name과 상관 없이 **"cb-vnet"으로만 생성**되도록 함.
- SecurityHandler 기능 변경
-- VM에 보안그룹 할당및 보안그룹 태깅을 위해 "cb-vnet"에 태깅함.
-- inboud / outboud를 INGRESS / EGRESS로 치환
- VMHandler 기능 변경
-- ImageId를 입력 받도록 수정 (예:**projects/ubuntu-os-cloud/global/images/ubuntu-minimal-1804-bionic-v20191024**) : ImageName을 조회해서 Id를 사용하는 로직 추가 예정(현재는 FullURL을 입력해야 동작함)
-- VM 생성시 태깅에 보안 그룹 반영
-- VM 정보 조회시 태깅 정보를 보안 그룹에 반영
-- VM 정보 조회시 ImageId 정보 반영
- ImageHandler 기능 변경
-- 공개이미지 목록 조회 기능 추가

VNetworkHandler & SecurityHandler & VMHandler & ImageHandler 기능 변경

---

cloud-control-manager/cloud-driver/drivers/gcp/GCPDriver-lib.go
cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Vm.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/CommonHandler.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/KeyPairHandler.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go

- VMHandler 기능 추가
-- ssh 계정 설정 (KeyPair 정보 연동)
-- VMUserId(ProjectID) 추가 :  ssh로그인 시 ProjectId로 로그인하면됨.
- KeyPairHandler 기능 추가
-- 콘솔 정보에 프로젝트 Id 구분자 추가
- 기본 Vnet이름을 "cb-vnet2"에서 "cb-vnet"으로 수정

- VMHandler &  기능 추가

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/main/Test_VM.go
cloud-control-manager/cloud-driver/drivers/aws/resources/CommonAwsFunc.go
cloud-control-manager/cloud-driver/drivers/aws/resources/PublicIPHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VNetworkHandler.go
cloud-control-manager/cloud-driver/interfaces/resources/PublicIPHandler.go

VNetworkHandler
- CreateVNetwork() : Name 기반 적용 완료 - "CB-VNet-Subnet" 고정이름 사용 / 중복 생성 체크
- DeleteVNetwork() : Name 기반 적용 완료 - "CB-VNet-Subnet" 고정이름 사용
- GetVNetwork() : Name 기반 적용 완료 - "CB-VNet-Subnet" 고정이름 사용
- ListVNetwork() : Name 기반 적용 완료 / "CB-VNet-Subnet" 검색후 리턴
KeyPairHandler : Name 기반으로 동작
PublicIPHandler
- CreatePublicIP() : Name 기반 적용 완료 / 중복 생성 체크
- DeletePublicIP() : Name 기반 적용 완료
- GetPublicIP() : Name 기반 적용 완료 / ** 다중 Result 체크 안 함. - 가장 마지막 결과 리턴 **
--> 공통 I/F의 PublicIPInfo 구조체에 Id string 필드 추가
- ListPublicIP() : Name 기반 적용 완료 / Name Tag없는 PublicIP는 목록에서 제외
SecurityHandler
- CreateSecurity() : Name 기반 적용 완료 / 보안그룹명 기반으로 동작
- DeleteSecurity() : Name 기반 적용 완료 / 보안그룹명 기반으로 동작
- GetSecurity() : Name 기반 적용 완료  / 보안그룹명 기반으로 동작
- ListSecurity() : Name 기반 적용 완료 / 보안그룹명 기반으로 동작 …

Key 필드를 Id 기반에서 Name Tag 기반으로 로직 변경

---

cloud-control-manager/cloud-driver/drivers/alibaba/build_driver_lib.sh
cloud-control-manager/cloud-driver/drivers/alibaba/main/TR.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMSpecHandler.go

윈도우즈에서는 문제 없었으나 Mac에서 구동시 패키니 오류가 있는 것을 봐서는
API 버전 차이에 따른 예외로 추정되어서 임시 확인용으로 에러만 없애 놓음.
resources/ImageHandler.go:159:38: undefined: ecs.Image
resources/VMHandler.go:312:44: undefined: ecs.Instance
resources/VMSpecHandler.go:22:56: undefined: ecs.InstanceType
현재 etcd 관련 goalng Build 오류로 동작 확인은 못함.
go: github.com/coreos/bbolt@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

ecs 패키지 오류 임시 처리

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/KeyPairHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go

CommonAwsFunc.go
Default CB VPC(“CB-VNet”) & Default CB Subnet (“CB-VNet-Subnet”)
→ VPC와 Subnet은 1개만 허용하고 내부에서 자동으로 처리되기 때문에 NameId 기반으로 구현됨.
ImageHandler.go
GetImage() : SystemId 기반으로 조회
Image Name을 Return 정보의 NameId에 셋팅 함.
KeyPairHandler.go
KeyName을 사용하지만 IID에서 SystemId의 값을 이용하도록 수정.
ListKey() : KeyName을 사용하기 때문에 NameId & SystemId모두 동일한 값 리턴
Return : irs.IID{*keyPair.KeyName, *keyPair.KeyName}
CreateKey() : NameId로 생성
Return : IID.NameId에는 전달 받은 NameId를 IID.SystemId에는 생성된 KeyName 할당
GetKey() : keyIID.SystemId로 조회
DeleteKey() : keyIID.SystemId로 삭제
SecurityHandler.go
CreateSecurity()
→ 내부에서 자동으로 Default CB VPC(“CB-VNet”) ID를 찾아서 사용 함.
→ GroupName 필드에 securityReqInfo.IId.NameId 설정 함.
→ Name Tag에 securityReqInfo.IId.NameId 설정 함.
Tag 실패시 에러 로그만 남기고 예외는 발생 시키지 않음.
ListSecurity()
→ 내부에서 자동으로 …

NameId 기반의 로직에서 SystemId 기반으로 로직 변경

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go
cloud-control-manager/cloud-driver/interfaces/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/interfaces/resources/VMHandler.go

[공통 인터페이스]
- VMHandler : 외부에서 접근 가능하도록 subnetIID와 vpcIID의 첫 Field명을 대문자로 변경
- SecurityHandler : 외부에서 접근 가능하도록 vpcIID --> VpcIID로 수정
[VMHandler]
- Subnet&VpcIID 반영
[SecurityHandler]
- VpcIID 전달 받는 방식으로 로직 변경
- 목록의 경우 CB-VNet에서만 조회했었으나 전체 VPC 영역에서 조회되도록 수정
[VPCHandler]
- 구현된 기능 없음

SubnetIID & VpcIID 추가 적용및 VpcHandler 기능제거

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/CommonAwsFunc.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VPCHandler.go

GetVPC : 완료
ListVPC : 완료
CreateVPC : 완료
**[아래 순서로 진행하다가 에러 발생시 중단하고 에러 리턴]**
- VPC생성
- VPC에 NameTag 추가
- VPC에 PublicIp 할당을 위해 IGW(인터넷게이트웨이) 생성
- IGW에 NameTag 추가
- VPC와 IGW 연결(Attach)
- VPC의 라우팅 테이블에 IGW 추가
- Subnet 생성 (Subnet 수 만큼 반복)
-- Subnet에 NameTag 추가
-- VPC의 라우팅 테이블에 생성된 Subnet 추가
-- 생성도중 에러 발생시 VPC 생성 중단
DeleteVPC : 완료
**[아래 순서로 처리하다가 에러 발생시 중단하고 에러 리턴]**
- VPC 하위의 모든 서브넷 제거
- 라우팅 테이블에 추가된 IGW 제거
-- VPC의 라우팅 테이블 정보 조회
-- 라우터 제거
- VPC에 연결된 모든 IGW 삭제
-- IGW 정보 조회 (IGW 수만큼 아래 과정 반복)
---- IGW 분리
---- IGW 제거
- VPC 제거

VPCHandler 1차 완료

---

cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMHandler.go

- VM 정보 조회
-  NetworkInterface  / VMUserId  내용 추가
--> NetworkInterface 항목에 할당된 인터페이스 Id 설정
-->  VMUserId 항목에는 root 설정
- VM Start(생성) 시 전달 받은 VMUserPasswd 필드 기능 적용
--> 알리의 경우 VM 생성 시 계정을 추가하는 기능은 없고, root 사용자의 비밀번호를 설정하는 기능은 있기 때문에 VM 생성 시 VMUserPasswd  의 값이 존재할 경우 root 사용자의 비밀번호를 요청된 값으로 설정 하며 VM 리턴 정보에 VMUserId 에는 root를 VMUserPasswd 에는 사용자가 설정한 값을 리턴하도록 기능 추가 함.
비밀번호는 8-30자로서 대문자, 소문자, 숫자 및/또는 특수 문자가 포함되어야 합니다.

알리 클라우드 VM핸들러 보완

---

cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go

- 이미지 목록 조회시 SystemId로 VM 생성 시 이용 가능하도록 SystemId를 이미지 URL을 리턴하도록 수정
- StartVM의 VmReqInfo.ImageIID.SystemId의 값은 Image Name대신 Image URL이 입력되어야 정상 동작하도록 수정
- StartVM의 리턴 정보 중 ImageIID.NameId의 값은 VmReqInfo.ImageIID.NameId값을 리턴하도록 수정

이미지 핸들러와 VM핸들러 수정

---

cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMSpecHandler.go

Alibaba VmSpecHandler의 MEM 규격을 GB에서 MB로 변경 ( GPU의 메모리 정보는 조회가 안되기 때문애 VM 메모리만 변경 함.)

Alibaba VmSpecHandler의 MEM 규격을 MB로 변경

---

cloud-control-manager/cloud-driver/drivers/aws/AwsDriver.go
cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VMSpecHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VPCHandler.go

AWS 드라이버의 이슈 #231 처리 (Available Zone 관련 개선이 필요함)
- Connection 생성 시 Region의 Zone 정보 입력 필수
- VPC 생성 시 Subnet은 사용자가 Region 정보에 지정한 Zone에만 생성 됨. (Region.Zone)
- VMSpecHandler의 ListVMSpec() / ListOrgVMSpec()의 조회 범위를 Region에서 사용자가 Region 정보에 지정한 Zone 범위로 제한
- VMSpecHandler의 ListVMSpec() / ListOrgVMSpec()에 전체 페이지의 데이터를 가져오도록 페이징 처리 추가
*참고, 페이징 처리에 따른 AWS 라이브러리 오류가 발생할 경우 최신 버전의 라이브러리를 사용할 것*
- VMSpecHandler.ExtractVMSpecInfo()의 spew.Dump()들 제거및 Log Level을 Info에서 Debug로 변경

이슈 #231 처리

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/CommonAwsFunc.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VPCHandler.go

- #255 AWS VPC 삭제 시 "InvalidRoute.NotFound"예외는 무시하도록 기능 변경
- #255 보완 작업으로 라우트 삭제전 0.0.0.0 설정 여부 조회하도록 로직 추가
- #258 예외의 경우 에러나 개선 사항은 아니며 특정 객체들의 필드 값을 문자열로 자동 맵핑시 이용하는 ConvertKeyValueList()에서 구조체나 배열을 비롯하여 NIL등 단일 String으로 단순 변환되지 않는 값들에 대해서는 변환이 불가능하기 때문에 향후 해당 필드들에 대한 참고를 위해 Error로 로그를 남기고 있으며,
cb의 경우 지정된 필드 외의 추가 정보들도 최대한 많이 남겨 달라고 요청이 있었기 때문에 AWS의 전체 오브젝트의 값을 단순 변환하기 때문에 위와 같은 현상들이 많이 발생하고 있음.
변환 함수 입장에서는 에러로 남기는게 향후에 찾기 무난하기 때문에 에러로 남기고 있으나 에러의 오해 소지가 있어서 요청에 의해 Warn으로 하향 조정했으며 필요시 Debug로 내려도 무관함.

#255 / #258 예외 보완

---

cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/CommonAwsFunc.go
cloud-control-manager/cloud-driver/drivers/aws/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VMSpecHandler.go
cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/ImageHandler.go

- AlibabaCloud 이미지 핸들러의 리턴 정보에 NameId 추가
- AWS 스펙및 이미지 핸들러의 Log 정보를 줄이기 위해 Info에서 Debug로 낮춤.
- AWS 이미지 핸들러의 리턴 정보의 NameId값을 SystemId로 통일
- AWS 이미지 핸들러의 리턴 정보중 Name 태그가 없는 이미지들이 존재해서 예외추가
- GCP 이미지 핸들러의 목록 조회 결과 값의 NameId를 SystemId와 동일한 URL 값으로 변경
*중요* GCP의 경우 이미지 조회는 NameId 기반으로 조회하도록 수정되어있는 상태라서 URL기반인 SystemId 기반으로 변경이 필요함.
현재는 급하게 목록의 NameId만 URL 기반으로 우선 반영해놨음.

로그레벨 일부 정리및 이미지 핸들러의 NameId 변경

---

cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/ImageHandler.go

- GCP의 GetImage() 기능도 Url기반으로 반영 완료
ProjectId를 전달 받지 않기 때문에 전달 받은 URL에서 ProjectId를 추출하는 형태로 구현되어 있으며,
전체 이미지 목록을 대상으로 테스트하지 않았기에 만약을 위해 기존의 FindImageInfo() 함수를
Name 기반에서 Url기반으로 수정하고 해당 함수를 사용하는 GetImageByUrl()을 추가해 놓음.
참고로, FindImageInfo() 함수 로직은 ListImage()에서 사용되는 전체 프로젝트의 이미지 목록에서 일치하는 Url을 찾는 방식임.

이슈 #239에 의해 GetImage()를 URL 기반으로 조회하도록 기능 변경

---

Dockerfile
conf/grpc_conf.yaml

- Suppose a case: Tumblebug -(gRPC call)-> Containerized Spider
---
Before: (gRPC call does not reach)
```JSON
{
"message" : "rpc error: code = Unavailable desc = write tcp 127.0.0.1:50184->127.0.0.1:50251: write: connection reset by peer"
}
```
```JSON
{
"message" : "rpc error: code = Unavailable desc = connection closed"
}
```
---
After: (gRPC call does reach)
```JSON
{
"message" : "rpc error: code = Internal desc =  error while calling CCMService.CreateKey() method: aws-us-east-1: does not exist! "
}
```
---
Reason:
The line `addr: 127.0.0.1:50251` in `grpc_conf.yaml` makes CB-Spider listen only for local loopback address (`127.0.0.1`),
making the gRPC port unreachable from other host/container.
The line `addr: :50251` resolves the problem.

Update grpc_conf.yaml and Dockerfile

---

api-runtime/grpc-runtime/common/cbconnection.go
api-runtime/grpc-runtime/config/config.go
interface/api/ccm.go
interface/api/cim.go
interface/cli/cbadm/proc/connectinfos.go
interface/grpc_conf.yaml

- 클라이언트의 grpc_conf.yaml 에서 서버주소 정보 위치 변경
- spidercli 아래에 server_addr 항목에서 설정
- cbadm connect-infos 정보 출력에서 protobuf struct 대신에 map 을 사용하여 protobuf 와의 관계를 제거함

Update grpc_conf.yaml and Remove protobuf struct from cbadm

---

utils/driver-build-docker/1.driver-build-container-run.sh
utils/driver-build-docker/2.build/ncp-build.sh

- Plugin용  NCP driver object 파일 생성을 위한 ncp-build.sh 작성
- Driver build 작업용 container 이름 변경 : cloud-twin-dev  -> driver-build

NCP driver - Plugin mode build 적용

---

api-runtime/grpc-runtime/common/cbmessage.go
conf/grpc_conf.yaml
interface/cli/cbadm/cmd/gclient.go
interface/cli/spider/cmd/gclient.go
utils/grpc-support-docker/data/prometheus/prometheus.yaml

- json.Marshal 함수는  <,>, & 문자를 escape 하고 있어 원래대로 다시 변환함
- CLI 에러 출력도 output format 으로 출력하게 함
- prometheus listening port 를 9092 에서 9096 으로 변경 (dragonfly port 와 충돌 해결 위해서)

Fix grpc api

---

cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/SecurityHandler.go

AWS/ALIBABA/TENCENT의 경우 Inbound / Outbound에 대한 간단한 CIDR 테스트는 진행했음.
[참고사항1]
- AWS의 경우 CIDR에 123.456.789.123/**0** 처럼 /32가 아닌 /0으로 잘 못 입력할 경우 API에서 별도의 오류 없이 정상적으로 등록되며 실제 처리된 결과는 사용자가 입력한 CIDR이 아닌 AWS 자체적으로 0.0.0.0/0으로 등록되니 참고... 
- 다른 CSP도 동일한지 확인해 보지 않았으며 123.456.789.123/**32** 처럼 정상적인 경우만 테스트해 봤음.
[참고사항2 -GCP 이슈]
- GCP의 경우 이전 이슈가 해결되지 않은 상태로 있어서 논의가 필요하기에 별도로 작업후 커밋 예정
--> GCP의 경우 보안 그룹 생성시 1개의 보안그룹 명에는 1개의 Inbound or Outbound만 셋팅할 수 있음.
그래서 기존에는 SecurityReqInfo.Direction 정보를 이용했지만 Inbound와 Outbound를 동시에 요청할 경우와 SecurityRuleInfo 배열의 첫번째 요소의 값을 이용하거나 Name 정보를 추가하는 방안 중 결정되지 않은 상태임.
현재는 SecurityReqInfo.Direction  값이 있으면 이용하고 없으면 가장 많이 사용되는 Inbound로 동작하도록 설정되어있음.
--> 현재 CIDR의 경우에도 동일하게 각 Port마다 설정하는 방식이 아닌 보안 정책에 1개만 셋팅 가능함.
즉, 1개의 정책(Inbound or Outbound 택1)에 여러 개의 Port 정보만 등록하는 방식이라 CIDR도 …

AWS/ALIBABA/TENCENT - 보안그룹에 CIDR 반영

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/ImageHandler.go

몇 개 이미지를 살펴 볼 경우 윈도우즈는 Platform("windows") 정보가 존재하며 리눅스 계열은 Platform정보는 없고 PlatformDetails("Linux/UNIX")만 존재하는 듯. - 
윈도우즈 계열은 PlatformDetails에는 "Windows with SQL Server Standard"처럼 세부 정보가 있어서 Platform 정보가 있으면 Platform 정보를 GuestOS에 할당하고
Platform정보가 없는 경우 PlatformDetails 항목의 값을 사용하도록 했음.
이미지에 대한 세부 내용을 참고할 수 있도록 KeyValue에 Description 정보도 추가함.

AWS - 이미지 정보에 GuestOS및  Description KeyValue추가

---

cloud-control-manager/cloud-driver/drivers/alibaba/AlibabaDriver.go

- 이슈 #409  에 의해 API 클라이언트의 타임아웃을 30초로 설정함.
자동 재시도 기능 활성화및 최대 재시도 횟수를 5회로 함게 설정함.
config.Timeout = time.Duration(30) * time.Second //time.Millisecond
config.AutoRetry = true
config.MaxRetryTime = 5
- 기존에 사용하던 credentials.BaseCredential은 deprecated 되어서 credentials.AccessKeyCredential로 인증 방식을 변경함.

Alibaba 이슈 #409에 의해 타임아웃 및 RetryTime 설정

---

api-runtime/rest-runtime/CBSpiderRuntime.go
api-runtime/rest-runtime/test/connect-config/9.mock-auth-conn-config.sh
api-runtime/rest-runtime/test/full-test/9.mock-auth-test.sh
api-runtime/rest-runtime/test/full-test/mock-auth_full_test.sh
setup.env

- Rest Server 에 Auth 기능 추가
- rest auth 관련 test script 추가
- setup.env 에 API_USERNAME, API_PASSWORD 변수 추가

Add rest auth

---

cloud-control-manager/CloudDriverHandler_dynamic.go
cloud-control-manager/cloud-driver/call-log/gen4test/gen_calllog.go

- CB-Spider에서 tencent driver 활용시 dynamic mode(plug-in mode) 지원을 위해 tencent driver 추가
- Call log 수집 대상 cloud OS에 tencent, NCP, NCP VPC driver 추가

CB-Spider에 driver 추가 반영

---

api-runtime/rest-runtime/CBSpiderRuntime.go
api-runtime/rest-runtime/CCMRest.go
api-runtime/rest-runtime/docs/docs.go
api-runtime/rest-runtime/docs/swagger.json
api-runtime/rest-runtime/docs/swagger.yaml
cloud-control-manager/cloud-driver/interfaces/resources/SecurityHandler.go

[REST API - Request call 의 JSON body 예시를 표시하는 방법]
[옵션 1] - `func createKey` 참조
```Go
// JSONResult's data field will be overridden by the specific type
type JSONResult struct {
//Code    int          `json:"code" `
//Message string       `json:"message"`
//Data    interface{}  `json:"data"`
}
// createKey godoc
// @Summary Create SSH Key
// @Description Create SSH Key
// @Tags [CCM] Access key management
// @Accept  json
// @Produce  json
// @Param keyPairCreateReq body JSONResult{ConnectionName=string,ReqInfo=JSONResult{Name=string}} true "Request body to create key"
// @Success 200 {object} resources.KeyPairInfo
// @Failure 404 {object} SimpleMsg
// @Failure 500 {object} SimpleMsg
// @Router /keypair [post]
func createKey(c echo.Context) error {
cblog.Info("call createKey()")
var req …
```

Add another Swagger pilot codes

---

cloud-control-manager/cloud-driver/drivers/mock/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/mock/resources/KeyPairHandler.go
cloud-control-manager/cloud-driver/drivers/mock/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/mock/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/mock/resources/VPCHandler.go
cloud-control-manager/cloud-driver/drivers/mock/test/image_test.go
cloud-control-manager/cloud-driver/drivers/mock/test/vpc_test.go

- DeleteCSPResource() 함수에서 리소스 삭제할 때 SystemId 를 이용하고 있음
- mock driver 에서 리소스 삭제할 때 NameId 를 사용하고 있어 SystemId 로 변경함
- MockVMHandler 의 ListVM() 에서 결과를 복사해서 리턴함

Fix delete csp resource for mock driver

---

cloud-control-manager/cloud-driver/drivers/azure-plugin/AzureDriver-lib.go
cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go
cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/azure/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/VMSpecHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/VPCHandler.go
go.mod
go.sum

[go sdk version change]
- 이전 : azure-sdk-for-go v51.2.0
- 현재 :  azure-sdk-for-go v55.5.0
[go library import version change]
1. compute
- 이전 : github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-06-01/compute
- 현재 : github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2021-03-01/compute
- 이슈 : 새로운 버전에서 PowerOff 함수에 skipShutdown(강제종료옵션), Delete 함수에 forceDeletion(강제삭제옵션) 파라미터가 추가되어 default값인 false 전달
2. network
- 이전 : github.com/Azure/azure-sdk-for-go/services/network/mgmt/2018-04-01/network
- 현재 : github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-02-01/network
3. resources
- 이전 : github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2017-05-10/resources
- 현재 : github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2020-10-01/resources

[Azure] go sdk 버전 업그레이드

---

api-runtime/grpc-runtime/interceptors/authjwt/auth.go
api-runtime/grpc-runtime/jwt-gen/jwt_gen.go
go.mod
go.sum

- Replace jwt-go with currently-being-maintained ver
- As-is: https://github.com/dgrijalva/jwt-go
- To-be: https://github.com/golang-jwt/jwt
- Related CB-Tumblebug issue: https://github.com/cloud-barista/cb-tumblebug/issues/656
- Related CB-Tumblebug PR: https://github.com/cloud-barista/cb-tumblebug/pull/661
- Related Dependabot alert: https://github.com/cloud-barista/cb-spider/security/dependabot/go.mod/github.com%2Fdgrijalva%2Fjwt-go/open

Replace jwt-go with currently-being-maintained ver

---

utils/driver-build-docker/2.build/ncp-build.sh

NCP driver build 과정 전에, 필요한 package를 다운로드 받아 오류 발생을 방지함.
- 다운로드 받아 설치하는 package들 :
go get -v github.com/NaverCloudPlatform/ncloud-sdk-go-v2@v1.1.7
go get -v github.com/appleboy/easyssh-proxy
go get -v github.com/sfreiberg/simplessh

Get needed packages before NCP driver building process

---

cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMSpecHandler.go
cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VMSpecHandler.go
cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/VMSpecHandler.go

**AWS** - Zone기반
- API는 Zone기반으로 구현되어 있으며 일부 로그 등에 사용된 파라메터의 Region 이용 부분을 세션의 Region으로 대체
**Alibaba**
- 파라메터의 Region 대신 세션의 Region으로 대체
**GCP** - Zone기반
- GetVMSpec()의 리턴 값에 사용된 파라메터의 Region 값 대신 세션의 Region 값으로 대체
**Tencent** - Zone 기반
- 이미 Zone기반으로 구현되어 있어서 변동 사항 없음

개선안 I및 이슈 #417 반영

---

cloud-control-manager/cloud-driver/drivers/openstack/resources/KeyPairHandler.go

- Openstack keypair 관리 로직 개선
> 생성 및 삭제 시 리소스 존재 유무 체크 및 에러 메세지 구체화
- cloud-init 스크립트 
> 공통 cloud-init 사용 불가 : subflatform 기능 미제공

[openstack] - 키페어 관리 로직 개선 (이슈 #480)

---

cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/tencent/main/conf/Test_Config.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/VMHandler.go
cloud-driver-libs/cloudos_meta.yaml

개선 기능및 이슈 #348에 의한 RootDisk 및 사이즈 변경 기능 지원
- GCP / Alibaba / Tencent RootDisk 설정 기능 추가
- 사이즈에 "default"로 설정되면 각 CSP별 고정된 값으로 셋팅(GCP:10GB / Alibaba:40GB / Tencent:50GB)
- Type이 지정되지 않으면  CSP 기본 옵션으로 생성 (디스크 관련 옵션 설정하지 않음)
- Size가 지정되지 않으면 CSP 기본 옵션으로 생성 (디스크 관련 옵션 설정하지 않음)
- 전달 받은 Type이 있으면 디스크 타입을 해당 값으로 설정
- 전달 받은 Size가 있으면 디스크 사이즈를 해당 값으로 설정
GCP - RootDisk 설정 기능 추가
---
GCP는 디스크 타입 지정 없이 사이즈만 지정도 가능
사용 가능 디스크 타입 : **pd-standard/pd-balanced/pd-ssd/pd-extreme**
Default 스토리지 : 10GB / 스토리지 지정 시 최소 10GB 이상이어야 함.
asia-northeast3-a 존에서 f1-micro 스펙으로 테스트 완료
RootDiskSize: "12", 
RootDiskType: "pd-ssd",
RootDiskSize: "12", 
RootDiskType: "pd-balanced",
RootDiskSize: "Default", //10GB
Alibaba - RootDisk 설정 기능 추가
---
알리바바는 디스크 타입 지정 없이 사이즈만 지정 가능
사용 가능 디스크 타입  : …

GCP/Alibaba/Tencent RootDisk 및 사이즈 변경 기능 지원 (이슈 #348)

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/VMHandler.go

개선 기능및 이슈 #348에 의한 AWS RootDisk 변경 기능 지원및 Tencent 지원 방식 개선
---
- AWS RootDisk RootDisk 설정기능 추가
- Tencent RootDisk 설정 방식도 다른 CSP와 동일하게 동작하도록 변경
- 사이즈에 "default"로 설정되면 각 CSP별 고정된 값으로 셋팅(AWS:8GB / Tencent:50GB)
- Type이 지정되지 않으면 CSP 기본 옵션으로 생성 (디스크 관련 옵션 설정하지 않음)
- Size가 지정되지 않으면 CSP 기본 옵션으로 생성 (디스크 관련 옵션 설정하지 않음)
- 전달 받은 Type이 있으면 디스크 타입을 해당 값으로 설정
- 전달 받은 Size가 있으면 디스크 사이즈를 해당 값으로 설정
AWS - RootDisk 설정 기능 추가
--
- 사용 가능 디스크 타입 : standard/io1/io2/gp2/sc1/st1/gp3
- Default 스토리지 : 8GB / 스토리지 지정 시 Image Size 보다 작으면 에러 남.
- 디스크 타입 및 디스크 사이즈 개별 지정 가능
- ap-northeast-1a리전에서 t2.micro 스펙으로 테스트 했음.
**[테스트 옵션및 결과]**
VMSpecName: "t2.micro"
RootDiskType: ""
RootDiskSize: ""
--> gp2, 8GB
VMSpecName: "t2.micro"
RootDiskType: "standard"
--> standard, 8GB
VMSpecName: "t2.micro"
RootDiskSize: "12"
--> gp2, 12GB …

개선 기능및 이슈 #348에 의한 AWS RootDisk 및 사이즈 변경 기능 지원및 Tencent 방식 개선

---

api-runtime/grpc-runtime/common/cbconnection.go

Fix grpc recv message max size

---

cloud-control-manager/cloud-driver/drivers/openstack/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go

- RootDisk Size 지정
- RootDisk Size 지정을 위한 Volume Create 생성 옵션
- RootDisk Volume의 타입 이원화로 Image 정보 metadata 내 지정 삽입
- ImageName이라는 메타데이터가 웹 콘솔내에 보이지만 api에서 찾을 수 없음 => 사용자 지정 metadata로 삽입
- image metadata 파싱 에러
- Image의 metadata => keyValueList 과정 중 string이 아닌 경우 파싱 에러 발견으로 코드 수정

[openstack] RootDisk Size 지정(이슈 #348)

---

CHANGELOG.md
README.md

`v0.3.0` 의 태그명은 `v0.3.0-espresso` 가 맞는데,
`v0.4.0` 부터는 태그명도 `v0.4.0` 라서
이를 Changelog에 반영하였으며
그 외에도 마크다운을 약간 업데이트 하였습니다. 😊

Tidy markdown documents

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/CommonAwsFunc.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go

AWS에서 키페어 없는 VM 생성 기능을 지원하기 때문에 키페어를 VM정보의 필수 항목에서 옵션으로 변경 함.

AWS VmHandler - Nil 키페어 이슈 처리 (이슈#573)

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go

- AWS VM  생성 시 RootDisk 관련 정보는 사용자 요청과 상관 없이 생성된 VM 정보를 기반으로 리턴 하도록 변경
- 볼륨 사이즈 사전 체크 조건에 블럭디바이스 맵핑 정보에 있는 EBS의 볼륨 사이즈 정보로 비교하도록 로직 추가
result.Images[0].BlockDeviceMappings[0].Ebs.VolumeSize
- 사용될 일은 없지만 혹시라도 "default" 사이즈가 요청 되었을 때 API 기본 값이 사용되도록 아무런 작업도 하지 않도록 수정

AWS 드라이버 #536 루트 디스크관련 이슈 보완

---

cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go

[VMInfo] RootDeviceName / VMBlockDisk 값 설정 (이슈 #536)
- Cloudit, Ibm-vpc, Azure - "Not visible in Azure" 설정
- Openstack - RootDeviceName mount path 설정

[VMInfo] RootDeviceName / VMBlockDisk 값 설정

---

cloud-control-manager/cloud-driver/drivers/cloudit/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/cloudit/main/conf/config.yaml.sample
cloud-control-manager/cloud-driver/drivers/cloudit/resources/CommonClouditFunc.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/VPCHandler.go

[Cloudit] VPC 개선 cb-store 저장 및 활용 (이슈 #576)
- VPC 단일 생성 기능 제공
- VPC 내 서브넷 관리를 위한 cb-store 데이터 & CSP 데이터 조합 
- 서브넷관리를 위해 cb-store에 데이터 저장 
- 콘솔 등의 환경에서 subnet 삭제등으로  cb-store와 실데이터 싱크를 위해 실제 subnet 존재 확인등의 로직 추가
- VPC 서브넷 생성 시 CIDR 값의 실패시 생성가능한 서브넷 리스트 제공

[Cloudit] VPC 개선 cb-store 저장 및 활용

---

cloud-control-manager/cloud-driver/drivers/cloudit/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go

- VM : 최대 45자로 생성시  적응형 IP ID가 45글자가 넘어가 생성불가
- 적응형 IP의 이름과 vm이름을 동일하게 생성
- SecurityGroup: 최대 45자로 생성시 Rule ID가 45글자가 넘어가 생성불가
-  rule의 이름을  Direction과 인덱스 조합으로 생성

[Cloudit] VM,SecurityGroup id 최대 길이값 버그 개선 #589

---

cloud-control-manager/cloud-driver/drivers/cloudit/client/dna/subnet/Request.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go

- VM 생성 실패시 Resource 반환 #589 이슈3
- Resource 반환 함수 정의 TerminateVM에 적용
- VM 생성시 subnet 확인 중 VPC 관계 확인 추가
- 기존 Cloudit의 네트워크는 subnet을 기준으로 하여 VM 생성시 VPC 확인을 하지 않았으나, Cloudit VPC 적용에 따른 VPC, subnet 확인 로직 변경
- Cloudit API 변경에 따른 API Client 함수 제거
- Cloudit V5 미제공 API 제거

[Cloudit] VM 생성 실패시 자원 반환 및 VM VPC-subnet 체크, API Client 함수 제거 #589

---

.gitignore
cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/VPCHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMHandler.go

Cloudit/Azure/Ibm 에 대한 Max-Length에 따른 생성 불가 오류, 버그 픽스하였습니다.(#594)(#596)
- OpenStack도 금주내에 확인 후 적용 예정입니다.
[Cloudit]
- cloudos_meta.yaml 기준 
|VPC|Subnet|SecurityGroup|KeyPair|VM|
|---|---|---|---|---|
|0|45|45|0|45|
- 위에 명시되지 않은 VPC, KeyPair도 45로 동일하게 테스트하였습니다.
- max-Length 관련 문제는 발견되지 않았습니다.
- 위와 별개로 VM, SecurityGroup에서 VPCInfo 누락했던 부분이 있어 수정했습니다.
[Azure]
- cloudos_meta.yaml 기준 
|VPC|Subnet|SecurityGroup|KeyPair|VM|
|---|---|---|---|---|
|64|80|64|80|64|
- SecurityGroup Rule, PublicIP, VNIC,OS ComputerName 의 Name 생성 방식이 변경되었습니다.
[IBM]
- cloudos_meta.yaml 기준 
|VPC|Subnet|SecurityGroup|KeyPair|VM|
|---|---|---|---|---|
|63|63|63|63|63|
- FloatingIP Name 생성 방식이 변경되었습니다.
OpenStack은 금주내에 테스트 후 반영하도록 하겠습니다.

[Cloudit/Azure/Ibm] Max-Length Issue Fix #594 #596

---

api-runtime/rest-runtime/test/full-test/13.nhncloud-test.sh
api-runtime/rest-runtime/test/full-test/nhncloud-full_test.sh
cloud-driver-libs/cloudos_meta.yaml

O Update cloudos_meta.yaml
- Add NHNCloud RootDiskType
: Supports 'default', 'General_HDD' and 'General_SSD' type of RootDiskType
O Update NHN Cloud driver full-test scripts
- Add RootDiskType and RootDiskSize parameter in StartVM() script for RootDiskType and RootDiskSize specifying test
O 관련된 NHN Cloud update PR : https://github.com/cloud-barista/nhncloud/pull/34

Add NHNCloud RootDiskType, Update NHN Cloud driver full-test scripts

---

cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMHandler.go

[ALIBABA] Panic when creating a VM with increasing root disk size https://github.com/cloud-barista/cb-spider/issues/586 이슈
- (AS-IS) old 한 image를 이용할 경우 image 정보를 받아오지 못하는 경우 발생
- (TO-BE) 이미지의 크기를 조회하는 GetImageSize function 추가
: 이미지 정보를 조회하는 DescribeImages의 ShowExpired = true 설정하면 old image 정보도 가져올 수 있음

Issue #586 - Update Alibaba VMHandler

---

api-runtime/rest-runtime/test/each-test/13.nhn-4.vm-rootdisk-1.sh
api-runtime/rest-runtime/test/each-test/13.nhn-4.vm-rootdisk-2.sh
api-runtime/rest-runtime/test/each-test/nhn-vm-rootdisk-test-1.sh
api-runtime/rest-runtime/test/each-test/nhn-vm-rootdisk-test-2.sh

- Add NHN Cloud RootDiskType and RootDiskSize specifying test scripts
- Test scripts : In case of u2 type of VMSpec
- api-runtime/rest-runtime/test/each-test/13.nhn-4.vm-rootdisk-1.sh
- api-runtime/rest-runtime/test/each-test/nhn-vm-rootdisk-test-1.sh
- Test scripts : In case of not u2 type of VMSpec
- api-runtime/rest-runtime/test/each-test/13.nhn-4.vm-rootdisk-2.sh
- api-runtime/rest-runtime/test/each-test/nhn-vm-rootdisk-test-2.sh

Add NHN Cloud RootDiskType and RootDiskSize specifying test scripts

---

utils/driver-build-docker/2.build/ncp-build.sh

- Update NCP Cloud Driver Build Script in Container (ncp-build.sh)
- Update Go SDK version
- ncloud-sdk-go-v2 : v1.4.1 -> v1.4.4

Update NCP driver Build Script in Container (update SDK version)

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/SecurityHandler.go

AWS 보안 그룹 핸들러에 룰 추가 / 룰 삭제 기능 반영
- 기본 룰 생성 확인 완료
- Inboud / Outbound에 각가 1개 및 2개의 룰 추가 기능 확인 완료
- Inboud / Outbound에 각가 1개 및 2개의 룰 제거 기능 확인 완료
**[고려 및 개선 사항]**
- 룰 추가 시 보안 그룹이 존재하는지는 체크하지만 보안 그룹 안에 존재하는 룰의 검증은 체크하지 않음.
즉, AAA룰의 인바운드에 80 / 8080 포트를 추가하려 할 때 AAA룰이 존재하는지는 체크하지만...
AAA 룰 안에 이미 80이나 8080 포트가 존재하는지는 사전 검증하지 않음(제거도 동일)
--> [참고] AWS API의 경우 보안 그룹에 삭제할 룰이 존재하든 존재하지 않는 룰 제거 API 호출은 무조건 성공임.
만약, 에러를 리턴하고 싶으면 사전 검증 로직이 추가되어야 함.

AWS 보안 그룹  기능 개선(룰 추가 / 룰 삭제)

---

cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/azure/main/conf/config.yaml.sample
cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/VPCHandler.go

- AddRule, RemoveRule 기능 추가
- 시험 항목에 대한 테스트 완료.
- portRange, protocol등 CB <-> Azure 포매팅 수정
- portRange의 all CB => -1 or 1-65535 => Azure "*"
- ptotocol의 all CB => all => Azure "*"
- 핸들러 기능 개선 
- 핸들러 별로 SystemId, NameId 기준이 다른 경우 개선
- 테스트 용이성 및 기능 통일
- 적용 핸들러 VPC, SecurityGroup
- TestResource 수정

[Azure] AddRule, RemoveRule 기능 추가 및 핸들러 기능 개선

---

cloud-control-manager/cloud-driver/drivers/cloudit/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/cloudit/main/conf/config.yaml.sample
cloud-control-manager/cloud-driver/drivers/cloudit/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go

- AddRule, RemoveRule 기능 추가
- 시험 항목에 대한 테스트
- Cloudit은 TCP/UDP 2가지만을 제공(ICMP 미제공)
- ICMP 외 테스트 완료
- portRange CB <-> Cloudit 포매팅 수정
-  portRange의 all CB => -1 or 1-65535 => Cloudit 1-65535
- Rule 이름 변경 
- 기존 index 방식 시 추가 삭제시 중복 가능성 존재 => 랜덤 값으로 변경
- Rule 이름 중복이여도 Error는 발생하지 않음
- 핸들러 기능 개선 
- 핸들러 별로 SystemId, NameId 기준이 다른 경우 개선
- 테스트 용이성 및 기능 통일 
-  적용 핸들러 VM, VPC, SecurityGroup

[Cloudit] AddRule, RemoveRule 기능 추가 및 핸들러 기능 개선

---

.gitignore
cloud-control-manager/cloud-driver/drivers/openstack/connect/OpenStack_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/openstack/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/openstack/main/conf/config.yaml.sample
cloud-control-manager/cloud-driver/drivers/openstack/resources/CommonOpenStackFunc.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/VPCHandler.go

OpenStack은 장기간 테스트 및 기능 점검이 되지 않아, 기능추가 하며 버그 수정 등의 내용도 있습니다.. 
- 테스트 코드 개선
- 테스트 코드 수정
-  AddRule, RemoveRule 테스트 추가
- VPC 핸들러 개선
- VPC 생성 실패시 리소스 반환 로직 추가 
- 삭제 플로우 개선
- vm 존재 확인 추가 - vm이 존재 할 경우 서브넷 삭제시 도중 실패 방지
- VPC maxlen 이슈 수정
- router 생성시 VPC 이름과 동일하게 생성
- VM 핸들러 개선 및 버그 픽스
- VM-서브넷 IP 할당 로직 추가
- OpenStack에는 서브넷 지정이 아닌 서브넷 내의 IP 입력방식(fixedip)
- 현재 vm이 지정된 서브넷에 생성되지 않아, API 단에서 IP주소 생성하여 할당으로 변경
- VM 생성 실패시 clean 로직 추가
- 핸들러별 SystemId, NameId 기준이 다른 경우 개선
- SystemId, NameId 둘중 하나만 있어도 조회가능하도록 수정(기능 통일)
- 적용 핸들러 : Image, VM, VPC
- SecurityGroup : AddRule, RemoveRule 적용 후 추가
- AddRule, RemoveRule 기능 추가 및 버그 픽스
- portRange, ptotocol input에 맞도록 Ibm 포매팅 수정
- portRange의 all CB => -1 or 1-65535 => Openstack 1-65535
- 생성 시 Default Rule로 인해 생성 실패 버그 수정
- 1. SG 생성 후 Default Rule과 Req의 Rule …

[Openstack] AddRule, RemoveRule 기능 추가 및 핸들러 기능 개선

---

cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/SecurityHandler.go

Alibaba, GCP, Tencent 보안 그룹 핸들러에 룰 추가 / 룰 삭제 기능 반영
1. 기본 룰 생성 확인 완료
- Inboud / Outbound에 각각 1개 및 2개 이상의 룰 추가 기능 확인 완료
- Inboud / Outbound에 각각 1개 및 2개 이상의 룰 제거 기능 확인 완료
2. Alibaba : 기존 Rule 추가 관련 function이 존재했음
- 기존 AuthorizeSecurityRules 를 AddRules로 이름 변경
- 기존 RevokeSecurityRules 를 RemoveRules로 이름 변경
[고려 및 개선 사항]
3. ADD Rules에서 INBOUND/OUTBOUND 가 같이 있는경우 (리스트 이므로)
- GCP : 불가. one direction만 가능.
- TENCENT : 불가. Cannot not add at the same time
-> inbound 추가 후 outbound 추가를 따로했을 때는 가능
- ALI : 같이 있어도 가능.
4. RemoveRule에서 모든 rule을 지우려고 하면
- ALI : 허용
- GCP : 허용안함. 최소 1개의 Rule이 존재해야 함.
- TENCENT : 허용
5. TestResource 보완
- AddRules, RemoveRules 추가(ALI, GCP, TENCENT)

Alibaba, GCP, Tencent 보안 그룹 기능 개선(룰 추가 / 룰 삭제)

---

cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go

https://github.com/cloud-barista/cb-spider/issues/482#issuecomment-1111430312
- AddRules/RemoveRules return 후 CSP가 반영위한 소요 시간 필요
- (안1)에 관련해서 조사해보겠습니다.
[azure-03.inbound-case-03.sh-Test:2022.04.27-19:32:25]
- SecurityGroup Rule의 포트가 뒤집혀 있던 버그 개선하였습니다.
테스트 결과는 issue 하단에 코멘트로 추가하겠습니다.

[Azure]SG-Rule 버그 픽스 (#482)

---

cloud-control-manager/cloud-driver/drivers/openstack/main/conf/config.yaml.sample
cloud-control-manager/cloud-driver/drivers/openstack/resources/ImageHandler.go
test/sg-rules-validation-cli/common/openstack-inno/setup.env

- OpenStack - Image 정보 관련
- OpenStack은 User NameId(ubuntu 18.04 LTS)의 identity가 보장되지 않기에 SystemId 기준으로 사용
- Image조회 방식 변경 및 Image Get/List 반환 값 변경
- 테스트 변수 변경

[OpenStack] Image 조회 방식 변경

---

cloud-control-manager/cloud-driver/drivers/alibaba/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/SecurityHandler.go

- Alibaba의 보안 그룹은 Basic / Advanced 2가지가 있음
- Basic의 outbound default : all open
- Advanced의 outbound default : all closed
- Advanced로 보안 그룹 생성 & 생성 시 outbound all open (outbound/ALL/-1/-1) 추가
- https://github.com/cloud-barista/cb-spider/issues/482#issuecomment-1120173588 의 Alibaba 이슈 보완
- Alibaba Inbound/Outbound Test 완료

Alibaba 보안 그룹 기능(보안 그룹 생성) 보완

---

cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go
cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go

[Azure] OutBound 및 공통이슈 개발 방안 적용 
- 추가 제거 방식 변경  
- 기존 : SecurityGroup자체 업데이트로 기능 제공
- 신규 : rule 추가 / 삭제 구현
- default Rule등의 추가로 SecurityGroup자체 업데이트로 기능 제공이 제한되어 변경
- default Rule 추가
-  Azure outbound
- Azure의 outbound는 Azure 자체(사용자 수정 불가)의 default 규칙으로 인해, Allow상태가 기준
- 타 CSP(aws) outbound
- Deny가 원칙이나, 사용자가 수정 가능한 default 규칙이 삽입되어 Allow 상태
- 위 default Rule을 삭제할 경우, Deny 상태로 전환
- Azure 기능 제공
- Azure에서 타 CSP 동일한 기능 제공을 위해 outbound를 0.0.0.0/0에서 Deny 규칙을 생성 
- 해당 Rule은 keyValue에선 보이나, SecurityGroup.SecurityRules로는 보이지 않음
- 사용자가 부여가능한 우선순위중 최하위(4096)
- Azure에서 타 CSP 동일한 기능 제공을 위해 outbound를 0.0.0.0/0에서 Allow 규칙을 생성 
- SecurityGroup.SecurityRules로 보이며, 삭제 가능
- 위 2개의 default Rule 생성으로 outbound를 0.0.0.0/0 Allow 규칙이 기본값으로 들어가며, 해당 룰을 삭제시 Outbound가 Deny되는 기능 제공 가능 
- outbound/Inbound 생성시 Cidr 매핑 …

[Azure] OutBound 및 공통이슈 개발 방안 적용

---

cloud-control-manager/cloud-driver/drivers/cloudit/resources/SecurityHandler.go

- securityGroup 생성시 default Rule 추가
- 타 CSP 동일한 기능 제공을 위해 outbound를 0.0.0.0/0 규칙을 생성하여 제공
- Rule 추가/삭제시 기존 Rule에 따른 에러 리턴
- 추가 : 존재하는 Rule 추가 시 에러
- 제거 : 존재하지 않는 Rule 삭제 시 에러
- Cloudit의 SecurityGroup은 VPC 연관이 없기에 default VPC 정보 제공 제거
- Cloudit 내에서 VM ssh 접속 문제 이슈는 현재 파악중입니다. 
- 조만간 위 이슈에 대해서 공유드리겠습니다.
해당 머지에 대한 outbound Test 결과는 이슈(https://github.com/cloud-barista/cb-spider/issues/482) 코멘트로 추가하겠습니다.
코드 변경에 따른 영향이 있을까 Inbound Test 수행 결과 모두 성공입니다.

[Cloudit] OutBound 및 공통이슈 개발 방안 적용

---

test/sg-rules-validation-cli/common/gcp/setup.env

GCP에 
projects/gce-uefi-images/global/images/ubuntu-1804-bionic-v20200317 (deprecated)
이미지가 사용 중단되어 있습니다.
projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20220505
로 변경하여,
테스트하면 좋을 것 같습니다.
CB-TB 차원에서는, 25개 리전에 대해 VM 생성 및 SSH 접속까지는 확인 하였습니다.
https://github.com/cloud-barista/cb-tumblebug/pull/1113
(참고: ssh 관련 오류가 발생하는 경우가 있어서 CB-TB 이슈 공유 드립니다.: https://github.com/cloud-barista/cb-tumblebug/issues/1112)

Update deprecated GCP image id for test

---

cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go

- rule 생성시 default Rule 중복적으로 추가하는 부분 수정

[Azure] SecurityGroup 생성시 rule이 2개일 경우 생성 안되는 현상 수정

---

cloud-control-manager/cloud-driver/drivers/openstack/resources/ImageHandler.go

이슈 (#641 )
- Openstack의 경우 Image에 OS와 관련된 정보가 없기에, Image의 이름을 GuestOS로 정보를 제공

[Openstack] ImageInfo 내 GuestOS 정보 추가

---

cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/VMHandler.go
cloud-driver-libs/cloudos_meta.yaml

- VM 생성 요청시 RootDiskType 및 RootDiskSize 기본값("", or "default") 처리 방법 변경
(https://github.com/cloud-barista/cb-spider/issues/660#issuecomment-1140721384 및 https://github.com/cloud-barista/cb-spider/issues/660#issuecomment-1140962549)
- 기본값 입력 시 아무것도 수행하지 않고 CSP에게 RootDiskType 및 size를 자동 생성으로 맡기는 방법으로 변경
- 테스트 결과
<html>
<body>
<h3>Tencent</h3>
Spec: SA2.MEDIUM2
Image: img-pi0ii46r
Type | Size | Result
-- | -- | --
“” | “” | CLOUD_PREMIUM / 50 으로 생성
“” | 60 | CLOUD_PREMIUM / 60 으로 생성
“” | 10 | ERROR: Root Disk Size must be larger then the image size (50 GB).
default | default | CLOUD_PREMIUM / 50 으로 생성
default | 60 | CLOUD_PREMIUM / 60 으로 생성
default | 7 | ERROR: Root Disk Size must be larger then the image size (50 GB).
CLOUD_PREMIUM | “” | CLOUD_PREMIUM / 50 으로 생성
CLOUD_SSD | “” | CLOUD_SSD / …

Tencent, Alibaba Rootdisk type, size 로직 보완 - 이슈#660 반영

---

cloud-control-manager/cloud-driver/drivers/openstack/OpenStackDriver.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go

[Openstack]VMHandler - VolumeClient 안전 처리
- NLB 기능 개발을 위해, openstack loadBalancer(octavia)가 설치된 새로운 팜을 이용하던 중, 발견한 버그 수정사항입니다.
- Volume을 제공하지 않는 경우와, Volume을 제공하지만, VolumeClient의 버전차이로 인해, 패닉에 빠지는 경우 수정사항입니다.
- NLB 기능과 직접적인 연관은 없으나, 버그픽스, 또 현재 테스트중인 팜, 이전 테스트팜에서 호환되도록 수정된 사항이라, NLB기능 PR전 해당 PR요청드립니다.
[적용사항]
- VolumeClient 버전 호환 및 VolumeClient 미제공 Openstack의 경우 패닉 방지
- VolumeClientV2 제공하던 것을 VolumeClientV2가 없을시 VolumeClientV3로 연결
- VolumeClientV2, VolumeClientV3 모두 없을 시, VolumeClient이 쓰이는 내부 코드에서 안전 처리 및 RootDiskSize 지정시 Error리턴(Volume을 이용한 방식)

[Openstack]VMHandler - VolumeClient 안전 처리

---

cloud-control-manager/cloud-driver/drivers/cloudit/ClouditDriver.go
cloud-control-manager/cloud-driver/drivers/cloudit/client/dna/loadbalancer/Request.go
cloud-control-manager/cloud-driver/drivers/cloudit/connect/Cloudit_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/cloudit/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/cloudit/main/conf/config.yaml.sample
cloud-control-manager/cloud-driver/drivers/cloudit/resources/NLBHandler.go

- 제공 불가 기능
- ChangeListener : Port, Protocol 변경 불가
- Listener 
- Protocol : TCP Only
- Cloudit NLB Listener Protocol: HTTP, HTTPS, TCP 제공
- CB-Spider NLB Listener Protocol: TCP, UDP 제공
- Port, Protocol 변경 불가
- Cloudit의 기능상 Listener의 Port, Protocol 를 변경할 수 없습니다.
- Port 범위 제한 1~65534
- 65535는 Cloudit에서 제공되는 통계페이지로서 고정(cloudit 내에서 지정가능 옵션이나, cb-spider에서 65535 고정)
- VMGroup 
- Protocol : TCP Only
- VMGroup과 Listener의 프로토콜이 같도록 설정되어, Listener Protocol이 TCP인 경우만 제공
- Protocol 변경 불가, port 변경 가능
- Cloudit의 기능상 VMGroup의 Protocol 를 변경할 수 없습니다.
- HealthCheck Protocol, Port 변경 불가
- Protocol : TCP, HTTP 
- Cloudit NLB HealthCheck Protocol: HTTP, TCP 제공
- Port, Protocol 변경 불가
- Cloudit의 기능상 HealthCheck의 Protocol을 변경할 수 없습니다.
- HealthCheck의 port는 VMGroup에 지정된 멤버들의 포트로 연결되어, vmGroup의 포트 변경시, 변경됩니다.
- …

[Cloudit] NLB 기능 개발

---

cloud-control-manager/cloud-driver/drivers/openstack/OpenStackDriver.go
cloud-control-manager/cloud-driver/drivers/openstack/connect/OpenStack_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/openstack/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/NLBHandler.go

- 사전 조건: Openstack 내의 octavia(openstack loadbalancer) 가 설치되어야 합니다.
- NLBHandler는 LoadBalancer API와 통신가능한 NLBClient의 존재 여부에 따라 기능 제공합니다.(추후, 제공 서비스 조회 방식으로  개선 예정)
- LoadBalancer가 설치되지 않은 Openstack의 경우, 제공하지 않는다는 에러 리턴합니다.
- ex: Failed to List NLB. err = this Openstack cannot provide LoadBalancer. Please check if LoadBalancer is installed 
- Listener 
- Protocol : TCP Only
- Openstack NLB Listener Protocol: HTTP, TCP 제공
- CB-Spider NLB Listener Protocol: TCP, UDP 제공
- Protocol 변경 불가, port 변경 가능
- VMGroup 
- Protocol : TCP Only
- VMGroup과 Listener의 프로토콜이 같아야 서로 연결 가능, Listener Protocol이 TCP인 경우만 제공
- Protocol 변경 불가, port 변경 가능
- HealthCheck 
- Protocol : TCP, HTTP, HTTPS
- Protocol 변경 가능, port 변경 불가
- HealthCheck의 port는 VMGroup에 지정된 멤버들의 포트로 연결되어, vmGroup의 포트 변경시, 변경됩니다.
- Interval, …

[Openstack]NLB 기능 개발

---

cloud-control-manager/cloud-driver/drivers/aws/AwsDriver.go
cloud-control-manager/cloud-driver/drivers/aws/connect/AwsCloudConnection.go
cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/CommonAwsFunc.go
cloud-control-manager/cloud-driver/drivers/aws/resources/NLBHandler.go

AWS NLB 드라이버 구현 1차 완료
[특이 사항]
- AWS는 NLB 생성 시 Subnet정보가 필수이며 향후 VPC에 존재하는 다른 VM추가 기능을 고려해서 **VPC에 포함된 모든 서브넷중 AZ별로 1개의 서브넷을 랜덤으로 추가해서 NLB를 생성**했음.
- AWS는 생성된 그룹 정보 변경이 불 가능하기에 ChangeVMGroupInfo 미지원
- ELB의 경우 프로토콜에 따라서 설정 가능한 값들이 다르며 NLB는 제약 사항이 더 심한데 NLB  생성이나 리스너 및 헬스체커의 속성 값 변경 요청에서 숫자는 0 이상인 경우 , 문자열은 ""이 아닌 경우에 한해서만 해당 값을 이용하도록 했음.
따라서, 생성 및 수정 시 필요 없는 필드의 값들은 0이나 ""로 전달하면 됨.

AWS NLB 핸들러 추가

---

cloud-control-manager/cloud-driver/drivers/gcp/connect/GCP_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/NLBHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/NLBHandler.go

Tencent
- VMHandler.go, NLBHandler.go: 맥락 상 에러가 아닌데 에러로 출력하는 부분 수정(cblogger.Errorf -> cblogger.Infof)
- https://github.com/cloud-barista/cb-spider/issues/649#issue-1236555422
- IID에 NameId 값 Set(VPC, VM)
- HealthCheckerInfo 값을 입력하지 않아도 생성되도록 수정
- 기존: HealthCheckInfo 값이 없을 때 다음과 같은 에러 생성 -> HealthCheck.TimeOut should be 2~60 등
- 현재: HealthCheckInfo 값이 없어도 HealthChecker 생성
- default: Protocl: TCP / Port: Real server port(null) / Timeout: 2sec / Interval: 5sec / Threshold: 3sec
- CreateNLB :
. 생성 전 존재하는 리소스인지 체크
. 생성 중 오류 시 리소스 회수
- DeleteNLB :
. 호출하는 function이 1개로 별도 회수로직 필요없음.
GCP
- CreateNLB :
. 생성 전 존재하는 리소스인지 체크
. 생성 중 오류 시 리소스 회수
- DeleteNLB :
. 삭제 전 존재하는 리소스인지 체크
. 3개의 리소스 중 일부만 있는 경우 일부만 삭제

GCP, Tencent NLBHandler 보완

---

cloud-control-manager/cloud-driver/drivers/aws/resources/KeyPairHandler.go

- Update AWS KeyPairHandler CLOUDLOGSCHEMA
: [ Bug fix ] ResourceType: call.SECURITYGROUP  =>  ResourceType: call.VMKEYPAIR

Update AWS KeyPairHandler CLOUDLOGSCHEMA (Fix ResourceType)

---

cloud-control-manager/cloud-driver/drivers/openstack/resources/NLBHandler.go

Openstack 팜 구축으로 기존에 시행하지 못했던 NLB 테스트 진행중, GetVMGroupHealthInfo 이 제대로 동작하지 않아, 수정하였습니다.(테스트 결과에 메모로 남겨두었습니다.)
- vmGroup Member OperatingStatus 체크조건 식 변경
- 리턴 값에 Error가 포함된 부분 수정

[Openstack] GetVMGroupHealthInfo 버그 픽스

---

test/nlb-test-curl/common/check-nlb-curl-test.sh
test/nlb-test-curl/common/check-nlb-ssh-test.sh
test/nlb-test-curl/common/prepare-nlb-test.sh
test/nlb-test-curl/nhncloud/setup.env

- Update CB-Spider NLB Test Scripts
- Add NHN Cloud setup.env in order to test NHN Cloud NLB functions
- Update prepare-nlb-test.sh
: Apply CSP name to keypair name as a parameter in order to create the keypair with proper name
- Update check-nlb-ssh-test.sh and check-nlb-curl-test.sh
: Present NLB Address and NLB Port which is calling during NLB Test using ssh and curl commands

Update NLB Test Scripts - Add NHN Cloud setup.env and Update prepare-nlb-test.sh

---

cloud-control-manager/cloud-driver/drivers/azure/resources/CommonAzureFunc.go
cloud-control-manager/cloud-driver/drivers/azure/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go

- 1. CreateDisk 시 type/Size 기본 값 설정 (https://github.com/cloud-barista/cb-spider/issues/717#issuecomment-1228418584)
- Size의 경우 콘솔의 기본값인 1024로 설정하였습니다. 
- 2. VM 내 DataDiskIIDs 정보 추가 (https://github.com/cloud-barista/cb-spider/issues/717#issuecomment-1228407758)

[Azure] DiskHandler Type/Size, VMHandler VM내 DataDisk 정보 추가 (#717)

---

cloud-control-manager/cloud-driver/drivers/openstack/OpenStackDriver.go
cloud-control-manager/cloud-driver/drivers/openstack/connect/OpenStack_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/openstack/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go

- Disk핸들러 구현을 위한 Connect 및 CreateHandler 부분 수정
- VolumeClient v2,v3 기능 제공을 위한 Connection, ConnectCloud 변경
- Openstack의 Vloume(Cinder)의 버전에 따라 생성할 Client가 달라지고, 타 서비스도 버전에 따라 분기될 가능성이 있음
- 타 Client 도 추후 버전이 나뉘어 제공될 경우, 기능 추가
- OpenStackCloudConnection의 Client 이름 변경
- Disk핸들러 구현
- DiskHandler 기능 구현
- VMHandler VMInfo 반영
- 핸들러 단의 VolumeClient v2, v3 통일식
- 핸들러 생성시, V3 버전 혹은 V2 버전으로 1개만 넣어주는 방식

[Openstack] 디스크 핸들러 구현

---

api-runtime/rest-runtime/test/connect-config/13.nhncloud-conn-config.sh
api-runtime/rest-runtime/test/full-test/13.nhncloud-test.sh

- Apply Separated Availability Zone to NHN Cloud Connection config and Test Code
- Before
- region: KR1
- region: KR2
- region: JP1
- After
- region: KR1
- zone: kr-pub-a
- zone: kr-pub-b
- region: KR2
- zone: kr2-pub-a
- zone: kr2-pub-b
- region: JP1
- zone: jp-pub-a
- zone: jp-pub-b
Related Issue) https://github.com/cloud-barista/nhncloud/issues/85

Apply Separated Availability Zone to NHN Cloud Connection config and Test Code

---

.github/workflows/build-amd64-container-image.yaml
.github/workflows/prow-commands.yml
.github/workflows/publish-multi-arch-container-images.yaml

**GitHub actions runner의 OS 중 하나인 Ubuntu 18.04가 Deprecated 예정 입니다. (2022년 12월 1일 까지)**
관련하여 workflow의 구동 환경을 ubuntu-latest(현재 20.04)로 업데이트 하는 것이 좋을 것 같습니다 ^^ 
NOTE - Cloud-Barista의 개발/테스트를 위한 공식 OS(Ubuntu 22.04)와는 관련이 없습니다. CB-Spider는 container image build를 통해 코드 필드 성공 여부를 테스트하고 있기 때문입니다.
Ref: [GitHub Actions: The Ubuntu 18.04 Actions runner image is being deprecated and will be removed by 12/1/22](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/)

Upgrade the actions runner OS

---

cloud-control-manager/cloud-driver/drivers/cloudit/client/ace/disk/Request.go
cloud-control-manager/cloud-driver/drivers/cloudit/client/ace/server/Request.go
cloud-control-manager/cloud-driver/drivers/cloudit/client/ace/snapshot/Request.go
cloud-control-manager/cloud-driver/drivers/cloudit/connect/Cloudit_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/cloudit/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/MyImageHandler.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go

[Cloudit] DiskHandler, MyImageHandler 기능 구현
- Cloudit DiskHandler 기능 구현
-  Cloudit은 Disk Size가 지정되지 않을 경우 오류를 반환하므로, Disk Size가 지정되지 않은 경우 50Gb로 설정하도록 하였습니다.
- Cloudit은 Disk를 생성할 Cluster ID를 지정하지 않을 경우 오류를 반환하므로, DiskHandler::CreateDisk의 DiskReqInfo 파라메터에 Key-Value 형태로 Cluster ID를 전달받도록 하였습니다.
- Cloudit MyImageHandler 기능 구현
- Cloudit은 VM + Data Disk를 조합한 단일 이미지를 생성하는 기능을 제공하지 않으므로, VM과 Data Disk들의 스냅샷을 생성하고, 생성된 스냅샷들을 MyImage와 연결할 수 있는 메타데이터를 스냅샷 이름에 저장하도록 하였습니다.
- 상기 과정에서 스냅샷의 이름이 자동으로 생성되며, 메타데이터를 저장할 공간을 확보하기 위하여 MyImage의 이름의 길이를 최대 35자로 제한하였습니다.
- Cloudit MyImage to VM 기능 구현

[Cloudit] DiskHandler, MyImageHandler 기능 구현

---

utils/driver-build-docker/2.build/ncp-build.sh
utils/driver-build-docker/2.build/ncpvpc-build.sh

- Update NCP driver, NCPVPC driver build script in a container
- Update ncloud-sdk-go-v2 version
:  v1.4.4 -> v1.5.2

Update NCP/NCPVPC driver build script - ncloud-sdk-go-v2 version -> v1.5.2

---

api-runtime/rest-runtime/test/connect-config/14.ncpvpc-conn-config.sh

- Update NCP VPC connection config
- Add Japan region and sub zones as new availability zones for NCP VPC
: Applied code to conn. config : Region : JPN, Zones : JPN-4 and JPN-5

Update NCP VPC connection config : Add Japan region and zones as new availability zones

---

utils/driver-build-docker/2.build/nhncloud-build.sh

- Update NHN Cloud connection driver build script - Remove go get nhncloud repo.
- Related Issue) https://github.com/cloud-barista/nhncloud/issues/101
- Related PR) https://github.com/cloud-barista/nhncloud/pull/107

Update NHN Cloud conn. driver build script - Remove go get nhncloud repo.

---

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMHandler.go

- Disk Type이 default일 경우, 기본값이 적용되지 않는 오류 수정
- VM 생성 시, 지정한 데이터 디스크를 장착하는 기능 추가
- VM 조회 시, 장착된 데이터 디스크의 정보를 반환하도록 수정

[IBM-VPC] Disk 기능시험 결과 오류 수정

---

cloud-control-manager/cloud-driver/drivers/openstack/resources/AnyCallHandler.go

CB-SP에서 오픈스택을 위해 TenantId 정보가 아닌 ProjectID 정보를 입력받고 관리하는 것으로 판단되므로, 이를 반영함

Fix result(PorjectID) of anycall/getConnectionInfo() for openstack

---

cloud-control-manager/cloud-driver/drivers/azure/resources/NLBHandler.go

CB-Spider-API-CSP적용-가능여부-및-이슈-2차분석-2022.07.11 버그 수정(#791)
Azure HealthCheck TimeOut 값 유효성 체크 추가/ CreateNLB, ChangeHealthCheckerInfo
Timeout 0, -1 일 경우만 생성되도록 변경 => 값 -1로 리턴
Timeout 0, -1 이 아닌 경우 (예제의 '10'같은 경우) => 에러 리턴 {"message":"Failed to Create NLB. err = Azure NLB does not support timeout."}
=>
[오후 2:11:31]    ==> {"message":"Failed to Create NLB. err = Azure NLB does not support timeout."}
CB-Spider-API-CSP적용-가능여부-및-이슈-2차분석-2022.07.11 버그 수정
Azure HealthCheck TimeOut 값 유효성 체크 추가/ CreateNLB, ChangeHealthCheckerInfo
Timeout -1 일 경우만 생성되도록 변경 => 값 -1로 리턴
Timeout -1 이 아닌 경우 (예제의 '10'같은 경우) => 에러 리턴 {"message":"Failed to Create NLB. err = Azure NLB does not support timeout."}

[Azure]NLB HealthCheck Test 버그 수정

---

cloud-control-manager/cloud-driver/drivers/alibaba/resources/CommonHandler.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/MyImageHandler.go

**[Alibaba] Check remained resources when vm snapshot timeout**(https://github.com/cloud-barista/cb-spider/issues/790) 
**[120s timeout의 적합성 확인]**
- 대기 시간을 600s로 재설정
**[오류 발생 시 중간 생성 자원 삭제]**
- Timeout 발생 시 생성 중인 MyImage 삭제 로직 추가

[Alibaba] VM Snapshot 과정 중 Timeout 이슈 보완

---

cloud-driver-libs/.cloud-init-tencent/cloud-init

[Tencent] Debian OS cb-user permission denied 이슈 보완
기존 cloud-init의 경우 cb-user의 ssh key 파일 정보 조회를 curl을 이용해서 인스턴스의 메타 정보를 조회하는 방식입니다.
curl -s http://169.254.0.23/latest/meta-data/public-keys/0/openssh-key
하지만, Debian OS의 경우 curl이 없기 때문에 ssh key 파일을 조회할 수 없어서 임시 방편으로 OS 계정에 있는 .ssh파일을 복제하는 방식으로 수정했습니다.
텐센트의 경우 대부분의 Linux 계정은 root 이지만 Ubuntu의 경우 ubuntu를 사용하기 때문에 아래처럼 반영했습니다.
cp -r /root/.ssh/ /home/cb-user/;
cp -r /home/ubuntu/.ssh/ /home/cb-user/;
os에 따라서는 해당 계정 폴더가 없어서 cloud-init 로그에 에러는 발생하겠지만 Debian과 Ubuntu 모두 정상 동작하는 것을 확인했습니다.

[Tencent] Debian OS cb-user permission denied 이슈 보완

---

cloud-control-manager/cloud-driver/drivers/alibaba/main/pmks_test/ClusterHandler_test.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go
cloud-control-manager/cloud-driver/drivers/alibaba/utils/alibaba/alibaba_api.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go

- 노드그룹 최초 삭제, 변경시 발생하는 에러 핸들링 코드 추가
- 노드가 추가/삭제 중인경우에 노드 ID가 빈 문자열로 조회되는 경우, 노드정보에 추가하지 않도록 변경

[Alibaba] 버그 수정

---

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMHandler.go

Windows VM 생성 시,
- 사용자가 제공한 VM 비밀번호로 VM을 생성하도록 수정
- VM 생성 이후 1회만 VM 비밀번호 반환
- Windows 비밀번호 복잡성 조건 예외처리

[IBM-VPC] Windows VM 사용자 제공 비밀번호 설정

---

cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go
cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/azure/resources/MyImageHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go

- VMHandler: 
- VMUserId, VMUserPasswd 지원 - Azure의 user 생성 정책상, cb-user라는 유저생성하여, VM 생성후 Administrator 유저 생성 후  cb-user 제거
- Image OS 구분 로직 추가
- MyImageHandler: 
- Window SnapShot을 위한 VM 내부 작업에 대한 PowerShell 추가 참고 [https://learn.microsoft.com/ko-kr/azure/virtual-machines/windows/upload-generalized-managed] - 해당 작업을 위해, Suspend인 VM은 Running으로 바꾼후 위 작업 후, 다시 Suspend후 일반화 수행
- 버그 수정: 리소스 그룹단위가 아닌 모든 MyImage가져오는 버그 수정

[Azure] WindowOS 지원

---

cloud-control-manager/cloud-driver/drivers/openstack/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go

- VMHandler:
- VMUserId, VMUserPasswd 지원
- Image OS 구분 로직 추가
- Openstack의 특성상 VM 생성시, 고려사항이 많아 복잡도가 증가하여, 구조의 변경이 있습니다.
- Disk 유무, Cinder 유무, MyImage, PublicImage 별로 if 처리 되던 것을 보기 편하도록 함수로 변경한 부분이 있어 변경점이 많습니다.   
- MyImage 기반 생성 테스트 완료
- MyImage에서 변경사항은 없습니다.
Openstack은 Window 이미지를 제공하지 않아, 사용자가 Window 이미지를 만들어야합니다. 해당 가이드라인은 [이슈에 등록](https://github.com/cloud-barista/cb-spider/issues/805#issuecomment-1303036845)해놓겠습니다.(markdown 원본이 필요하실 경우 슬랙으로 전달드리겠습니다.)

[Openstack] Window OS 지원

---

cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go

Window HostName 관련 변경사항 아래와 같습니다. Azure와 Cloudit만 변경되었습니다.
[Azure] : 15글자이상일 경우 뒤에서 자르기
[IBM-VPC] : 15글자 이상시, IBM내부에서 15글자로 잘려서 지정됨(변경사항X)
[Cloudit] : 15글자이상일 경우 뒤에서 자르기
[Openstack] : 15글자 이상시, Cloudbase-init에 의해 15글자로 잘려서 지정됨(변경사항X)

[Inno] Window ComputerName 제한

---

cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go

[해당 코멘트](https://github.com/cloud-barista/cb-spider/issues/805#issuecomment-1303066319)관련 적용사항입니다.
- Azure, Ibm-VPC, Cloudit, Openstack 모두 Password 체크 함수 공통으로 변경했습니다.
- WindowType Driver별 내부에서 처리는 구현되어 있어 변경사항 없습니다.

[InnoCommon] Window Password 제한 및 WindowType 관련 적용사항

---

cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go

[Azure] Remove Req's SSH Key Info in the driver when WindowsOS #833
- Window VM 생성시, KeyPair의 값이 존재하는 경우 에러로 리턴 => 검사하지 않도록 변경
- CSP 별로 KeyPair의 필요 여부가 다름 => Azure에서 에러를 리턴하기보단, 이용하지 않는 방향으로 수정

[Azure]Window시 KeyPair 존재 시 에러 제거

---

cloud-control-manager/cloud-driver/drivers/cloudit/resources/MyImageHandler.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go

- 정지된 Windows VM 시작 시, SSH 접근 가능 여부 체크 생략
- Windows VM Reboot 시, SSH 접근 가능 여부 체크 생략
- Windows MyImage 생성 시, 원본 VM이 종료되어야만 MyImage를 생성할 수 있도록 수정    
- Windows VM을 정지하지 않고 MyImage를 생성한 뒤, 해당 MyImage로 VM을 생성할 경우, VM 생성에 실패하는 오류를 발견하였습니다.
- 해당 오류는 NTFS 파티션이 unsafe 상태이나, Hostname을 변경하기 위해 해당 파티션을 마운트하는 과정에서 발생하였습니다.
- https://libguestfs.org/guestfs.3.html (WINDOWS HIBERNATION AND WINDOWS 8 FAST STARTUP 항목)
- 따라서 Windows VM의 MyImage를 생성하는 과정에서 원본 VM이 정지되었는지 확인하는 과정을 추가하였습니다.

[Cloudit] Window VM 관련 오류 수정

---

utils/driver-build-docker/2.build/ncp-build.sh
utils/driver-build-docker/2.build/ncpvpc-build.sh

- Update NCP go SDK version in NCP Classic and NCP VPC build scripts
: Update NCP go SDK v1.5.2 -> v1.5.3

Update NCP go SDK ver. to 1.5.3 in NCP Classic and NCP VPC build scripts

---

cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go

[AWS:VM] Assign {RootDiskType or RootDiskSize} to empty array
- https://github.com/cloud-barista/cb-spider/issues/857
- VMHandler에서 input.BlockDeviceMappings 객체 생성 코드가 주석 처리되어 에러 발생
- 주석 처리 해제함

[AWS:VM] ISSUE #857 보완

---

cloud-driver-libs/.cloud-init-ncpvpc/cloud-init-windows

- Add NCPVPC Cloud-init script file for MS Windows OS
- Note :  NCPVPC only supports Visual Basic as a Cloud-init script

Add NCPVPC Cloud-init script file for MS Windows OS

---

cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go

타기능 부착을 위해 VM 생성시, 버그사항을 발견하여 수정합니다.
윈도우 생성시, Password가 14글자 이상시 아래와 같은 확인 문구 출력.
```
The password entered is longer than 14 charactors. Computers
with Winodows prior to windows 2000 will not be able to use
this account. Do you want to continue this operation? (Y/N) [Y]:
```
해당 응답에 답을 하지 않아, 대기되어 Y로 지정 하기 위해 /Y 추가.
MyImage에서 사용하는 패스워드 변경은 해당 문제가 없음을 확인하였습니다.

[Azure] Window 생성시 14글자 이상 Password 지정시, 확인 문구 스킵 추가

---

cloud-driver-libs/.cloud-init-ncpvpc/cloud-init-centos

- Add cloud-init script for CentOS and Rocky Linux
- Note : CentOS and Rocky Linux uses 'wheel' group instead of 'sudo' group of Ubuntu

Add cloud-init script for CentOS and Rocky Linux

---

cloud-control-manager/cloud-driver/drivers/azure/resources/MyImageHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go

- Azure: OS의 종류를 이미지와 독립적으로 획득하는 로직 추가 및 GetVM시 Platform 제공
- OpenStack: OS의 종류를  이미지와 독립적으로 획득하는 로직 추가 및 GetVM시 Platform 제공
- IBM-VPC: OS의 종류를 이미지와 독립적으로 획득하는 로직 추가 및 GetVM시 Platform 제공
- Cloudit: Cloudit 로직 확인 결과, 이미지를 기반으로 생성한 VM 또는 스냅샷이 존재할 시, 해당 이미지 삭제가 불가능하여 기존 로직을 유지하였으며, GetVM시 Platform을 제공하도록 수정하였습니다.

[InnoCommon] VMInfo.Platform 추가

---

cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
go.mod

- Azure, IBM-VPC, Cloudit, Openstack 적용 (#862)
- 작업중,  Platform가 잘못전달되는 케이스가 있어 같이 수정했습니다.
- Azure :  getOSTypeByMyImage 함수 내 윈도우를 리턴해야하는 경우.  
- Cloudit : mappingServerInfo 함수 내 리눅스를 리턴해야하는 경우.

[InnoCommon]] VM Platform 정보 변경

---

utils/driver-build-docker/2.build/ncp-build.sh
utils/driver-build-docker/2.build/ncpvpc-build.sh

- Update NCP GoSDK version in NCP Classic and NCP VPC driver build script
- version v1.6.4 -> v1.6.6

Update NCP GoSDK version in NCP Classic and NCP VPC driver build script

---

cloud-control-manager/cloud-driver/drivers/gcp/GCPDriver.go
cloud-control-manager/cloud-driver/drivers/gcp/connect/GCP_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/gcp/main/conf/Test_Config.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/CommonHandler.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/RegionZoneHandler.go
cloud-control-manager/cloud-driver/interfaces/CloudDriver.go
cloud-control-manager/cloud-driver/interfaces/connect/CloudConnect.go

[+Region/Zone] GCP Cloud Driver Implementation #910
특이사항 
Region Zone 정보 조회를 위한 IAM Role 세팅이 되어 있어야 한다.
* required Compute Engine IAM ROLE : ### **compute.regions.list**
ListRegionZone 구현
- 모든 Region에 대한 Zone 이름은 확인가능하나, ZoneList의 Zone의 Status를 위해 각 Zone을 조회함.
ListOrgRegion 구현
ListOrgZone 구현

#910 [+Region/Zone] GCP Cloud Driver Implementation

---

cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/CommonHandler.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/RegionZoneHandler.go

GCP region zone
- drvCapabilityInfo true 
- keyvalue func add and fix
--  ConvertToString() , ConvertKeyValueList()

region zone keyvalue and drvCapabilityInfo GCP

---

api-runtime/rest-runtime/test/region-zone-test/14.ncpvpc-region-zone-test.sh
api-runtime/rest-runtime/test/region-zone-test/8.ncp-region-zone-test.sh
api-runtime/rest-runtime/test/region-zone-test/region-zone_test.sh

- Add NCP Classic and NCP VPC RegionZoneHandler Test Scripts using CB-Spider API
- Add NCP Classic driver RegionZoneHandler Test Scripts
- Add NCP VPC driver RegionZoneHandler Test Script

Add NCP Classic / NCP VPC driver RegionZoneHandler Test Scripts using CB-Spider API

---

cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/azure/resources/RegionZoneHandler.go

- Implement GetRegionZone()
- Speed up ListRegionZone() from about 10sec to 5sec.

[+Region/Zone] Implement GetRegionZone() to Azure Cloud Driver

---

cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go

- Rename testRegionZoneHandlerPrint() to testRegionZoneHandlerListPrint()

[+Region/Zone] Fix a wrong function name in Test_Resources

---

api-runtime/rest-runtime/test/connect-config/15.ktcloudvpc-conn-config.sh
api-runtime/rest-runtime/test/region-zone-test/15.ktcloudvpc-region-zone-test.sh
api-runtime/rest-runtime/test/region-zone-test/region-zone_test.sh
cloud-control-manager/CloudDriverHandler_common.go

- Apply Region Info to KT Cloud VPC
: There was only Zone info before.
- Update CloudDriverHandler_common.go
- Update 15.ktcloudvpc-conn-config.sh
- Add KT Cloud VPC RegionZoneHandler Test Code
- Add 15.ktcloudvpc-region-zone-test.sh
- Udate region-zone_test.sh

Apply Region Info to KT Cloud VPC, and Add KT Cloud VPC RegionZoneHandler Test Code

---

cloud-control-manager/cloud-driver/drivers/azure/resources/RegionZoneHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/RegionZoneHandler.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/RegionZoneHandler.go

- Fixed by this discussion.
https://github.com/cloud-barista/cb-spider/pull/984#discussion_r1430764360
- Remove a useless variable in RegionZoneHandler of Azure, IBM and OpenStack.

[+Region/Zone]  Remove a useless variable in RegionZoneHandler

---

cloud-control-manager/cloud-driver/call-log/calllogger.go
cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go
cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/azure/resources/CommonAzureFunc.go
cloud-control-manager/cloud-driver/drivers/azure/resources/PriceInfoHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/RegionZoneHandler.go

- Implement all of 2 functions of PriceInfoHandler
- ListProductFamily()
- GetPriceInfo()

[+Price] Implement Azure's PriceInfoHandler

---

cloud-control-manager/cloud-driver/drivers/azure/resources/PriceInfoHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/RegionZoneHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/IBMCloudDriver.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/connect/Ibm_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/PriceInfoHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/RegionZoneHandler.go
cloud-control-manager/cloud-driver/drivers/openstack/OpenStackDriver.go
cloud-control-manager/cloud-driver/drivers/openstack/connect/OpenStack_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/RegionZoneHandler.go

- Implement PriceInfoHandler
- Call wait.Done() when error occurrs (Fix go routine may not end when error occurred.)
- Call wait.Done() when error occurrs (Fix go routine may not end when error occurred.)
- Fix typo in GetPriceInfo()
- Fix not available message of PriceInfo
- Call wait.Done() when error occurrs (Fix go routine may not end when error occurred.)

[+Price, +Region/Zone] Implement IBM's PriceInfoHandler and fix some drivers

---

cloud-control-manager/cloud-driver/drivers/aws/resources/PriceInfoHandler.go

#998 issue
GetAttributeValues 로 ListProductFamily 변경
- 컴퓨팅 인프라 관련 서비스로 한정
[As-Is]
```
[
"A4B",
"AWSAmplify",
"AWSAppFabric",
"AWSAppRunner",
"AWSAppSync",
"AWSApplicationMigrationSvc",
"AWSB2Bi",
"AWSBackup",
"AWSBillingConductor",
... 중략 ...
"translate"
]
```
[To-Be]
```
[
"CPU Credits",
"Compute Instance (bare metal)",
"Compute Instance",
"Data Transfer",
"Dedicated Host",
"EBS direct API Requests",
"Elastic Graphics",
"Fast Snapshot Restore",
"Fee",
"IP Address",
"Load Balancer",
"Load Balancer-Application",
"Load Balancer-Network",
"NAT Gateway",
"Provisioned Throughput",
"Storage Snapshot",
"Storage",
"System Operation"
]
```

[Price:AWS] ListProductFamily() #998

---

cloud-control-manager/cloud-driver/drivers/ktcloud/KtCloudDriver.go
cloud-control-manager/cloud-driver/drivers/ktcloud/connect/KtCloud_Connection.go
cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_NLBHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloud/main/goget-ktsdk.sh
cloud-control-manager/cloud-driver/drivers/ktcloud/main/test_nlb.sh
cloud-control-manager/cloud-driver/drivers/ktcloud/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloud/resources/NLBHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VMHandler.go
go.mod
go.sum

- Add KT Cloud Classic NLBHandler methods
- Add KT Cloud Classic NLBHandler test codes
- Update KtCloudDriver.go
-  Add NLBClient
- Update KtCloud_Connection.go
-  Add Connection to NLBHandler
- Add GetVmNameWithId() method
- Update go.mod/go.sum
- Update ktcloud-sdk-go version

Add KT Cloud Classic (G1/G2 platform) NLBHandler features

---

cloud-control-manager/CloudDriverHandler_common.go

- GCP price info 를 가지고 오기 위해서 BillingAccountID 를 CredentialInfo 에 셋팅이 필요합니다.
- GCP Credential 을 등록 시 key value 에 아래 정보 추가하고 등록을 하였습니다.
`{"Key":"BillingAccountID", "Value":"billingAccounts/xxxxxx-xxxxxx-xxxxxx"}` 
- 사용자가 입력한 credential 정보를 CredentialInfo struct 로 매핑하는 부분에서
- BillingAccountID 를 매핑하는 코드가 누락되어 있는 것을 확인하였습니다.
- 원활한 웹 테스트를 위해 해당 부분 코드 추가하였습니다.

Add billing account id from credential to CredentialInfo struct

---

cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/VMHandler.go

- Update DeleteInitScript() method
: Errors occur even though it has been deleted.
- Modify Code to Check for Success after InitScript Deletion
- Related Issue) https://github.com/cloud-barista/cb-spider/issues/1022

Update DeleteInitScript() method - Modify Code to Check for Success after InitScript Deletion

---

cloud-control-manager/cloud-driver/drivers/gcp/main/conf/Test_Config.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/PriceInfoHandler.go

- Credential Info 에서 BillingAccountID 가 참조되는 코드가 테스트 파일에 존재해서 해당 부분 삭제했습니다.
- GCP PriceInfoHandler.go 에 개발용으로 추가된 프린트문을 삭제했습니다.(#1031 )

GCP Driver - Remove unnecessary code lines.

---

cloud-control-manager/cloud-driver/drivers/ncpvpc/main/Test_VMHandler.go
cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/VMHandler.go

- Update NCP VPC VMHandler
-  Remove 'NameID: "N/A"'
: This makes an error on CB-Spider like below
```
[CLOUD-BARISTA].[ERROR]: 2024-02-05 23:32:25 VMManager.go:1152, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.getSetNameId() - ncpvpc-korea1-config, oh-test-vpc-1, N/A: does not exist! 
[CLOUD-BARISTA].[ERROR]: 2024-02-05 23:32:25 VMManager.go:1059, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.getVMInfo() - ncpvpc-korea1-config, oh-test-vpc-1, N/A: does not exist! 
```
- Update NCP VPC Test code

Update NCP VPC VMHandler - Remove 'NameID: "N/A"'

---

cloud-control-manager/cloud-driver/drivers/ktcloud/resources/NLBHandler.go

- Update NLBHandler DeleteNLB() method
- Apply RemoveVMs() with VM NameIDs to Delete NLB VMs

Update KT Cloud Classic NLBHandler DeleteNLB()

---

cloud-control-manager/cloud-driver/drivers/ktcloud/resources/NLBHandler.go

- Update KT Cloud Classic NLBHandler
- Remove 'NameID: "N/A"' code
: This makes an error on CB-Spider

Update KT Cloud Classic NLBHandler - Remove 'NameID: "N/A"' code

---

cloud-control-manager/cloud-driver/drivers/azure/resources/PriceInfoHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/RegionZoneHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/PriceInfoHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/RegionZoneHandler.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/RegionZoneHandler.go

- [Azure: Sort order of regions](https://github.com/ish-hcc/cb-spider/commit/d2445545413863499acbfb2a7a3d808d73c2ae2a)
- [Azure: Fix parsing of price data](https://github.com/ish-hcc/cb-spider/commit/b7712ec11bc0d8deb8d6f7ddfbf435398b01bda7)
- [IBM: Show only resource specific attributes](https://github.com/ish-hcc/cb-spider/commit/bcde993ea26e51bec7d33f8bb05f1660d068868f)
- [IBM: Sort order of regions](https://github.com/ish-hcc/cb-spider/commit/4748d7fa6d7c6cf1650cfead934dde4cd82ac9b5)
- [OpenStack: Sort order of regions](https://github.com/ish-hcc/cb-spider/commit/e4f58b8bcc48fe72beb3eab81c87f867c2af4bec)

[+Price, +Region/Zone] Fix Price and Region/Zone handlers of Azure, IBM and OpenStack

---

cloud-control-manager/cloud-driver/drivers/aws/AwsDriver.go
cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/CommonHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/RegionZoneHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/TencentDriver.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/VMSpecHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/VPCHandler.go

- 출력 되는 로그 메시지 영어로 변경하였습니다.
- The output log message has been changed to English.
```
##AS-IS
cblogger.Error("Connection 정보에 Zone 정보가 없습니다.") 
##TO-BE
cblogger.Error("Connection information does not contain Zone information.") 
```

[Tencent] Change All Error Messages to English #1053

---

cloud-control-manager/cloud-driver/drivers/azure/resources/PriceInfoHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/PriceInfoHandler.go

Azure and IBM do not provide pricing policy info,so show these attributes as NA.

[+Price] Show PricingPolicyInfo attributes as NA

---

.github/workflows/korean-checker.yaml

This PR will add the `korean-checker.yaml` workflow. 
The workflow is triggered by a pull request (PR) targeting the main branch.
```yaml
on: 
pull_request:
branches:
- 'master'
paths:
- '**.go'
```
The workflow checks if Korean is included in texts to print or log as follows:
```go
fmt.Println("안녕하세요, 세계!")
log.Println("한글 로깅 추가")
```
The workflow will
- **return failure** if the changed section in a PR **includes Korean**.
- **return success** if the changed section does **NOT include Korean**.
(sample) The workflow will add comments when Korean is detected.
See details: https://github.com/yunkon-kim/test-on-github-actions/pull/151
Close #1064
--- 
Note - If every Korean text should be checked (like `// 한글`), modify the workflow as follows. (Additional tests will be required.)
```diff
- …
```

Add `korean-checker.yaml` workflow

---

cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMHandler.go

- [Bug Fix] Does not include RootDisk in DataDisk List in NHN Cloud VMHandler
- Before : Includes RootDisk in DataDisk List
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1063

[Bug Fix] Does not include RootDisk in DataDisk List in NHN Cloud VMHandler

---

.github/workflows/korean-checker.yaml

This PR will replace `secret.GITHUB_TOKEN` with `secret.CB_GITHUB_ROBOT_PAT`.
(Summary)
- The `GITHUB_TOKEN` is scoped to the current repository (i.e., forked repo). 
- The `GITHUB_TOKEN` does **NOT have permission to add comments on PRs opened in the upstream repo** from the forked repo.
- On the other hand, `CB_GITHUB_ROBOT_PAT` can be scoped as desired (`repo` scope is assigned)
- **Therefore, comments can be added on the PR with `CB_GITHUB_ROBOT_PAT`**.
Ref: https://github.com/actions/github-script?tab=readme-ov-file#using-a-separate-github-token
In my opinion, this PR should be merged as is. And then, we can check for permission issues in the next PR.
(Until then, I'd like to keep #1070 open.)

Replace the GITHUB_TOKEN with a PAT

---

cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go

Tencent에서는 default container runtime을 docker로 지정되어 있기에 별도의 설정이 없는 경우 container runtime이 docker로 설정되고 있습니다.
현재 K8s 1.24 이후 containerd만 지원하고 있기 때문에 기본값을 containerd로 설정하도록 업데이트하였습니다.
fix #1011

Set default container runtime as containerd (fix #1011)

---

cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go

RemoveNodeGroup API 호출 후 바로 GetCluster API 호출한 경우 관련 노드 정보가 없는 경우 0 인덱스 접근을 차단합니다.
fix #1012

Prevent to access index out of range [0] with length 0

---

cloud-control-manager/cloud-driver/drivers/gcp/resources/PriceInfoHandler.go

- billing account api 호출 시 권한 에러 (403) 가 발생하는 경우 logging 만 한 후 continue 로 반복
- 불필요한 반복을 통해 자원 낭비
- googleapi 의 에러인지 확인 후 403 코드를 반환한 경우 error 를 반환하고 api 호출 종료
- 권한이 없는 경우 불필요한 반복 제거

Resolve #1076 - Remove unnecessary repetition when configuration doesn't have any permission to billing account

---

cloud-control-manager/cloud-driver/drivers/nhncloud/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/nhncloud/resources/MyImageHandler.go
cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMHandler.go

- Update NHN Cloud DiskHandler and MyImageHandler
- Add getNhnVolumeList() method and Update getBootableVolumeID() method
- Since an error occurs from getBootableVolumeID() method after the Bug Fix of https://github.com/cloud-barista/cb-spider/pull/1071
- Update NHN Cloud VMHandler
- Apply 'tzdata' package to prevent 'unknown time zone "Asia/Seoul"' error
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1062
```
Ref)
The error message 'unknown time zone Asia/Seoul' occurs when your Go program tries to load the "Asia/Seoul" time zone using 'time.LoadLocation("Asia/Seoul")', but the Go runtime is unable to find the time zone database. 
This problem typically arises in one of the following scenarios :
- The time zone data is not installed on your system: The Go runtime …
```

Update NHN Cloud getBootableVolumeID() method, and Apply 'tzdata' package to prevent 'unknown time zone ~' error

---

cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMSpecHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VMSpecHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/VMSpecHandler.go

***
- VMSpec 등록시 등 인스턴스 스펙 정보를 추출하는 함수(ExtractVMSpecInfo) 호출시 불필요한 에러 메시지가 출력되고 있습니다.
- 출력 되는 메시지는 영어로 부탁 드립니다.
***
***
- 불필요한 메시지 삭제
- 출력 되는 메시지 영어로 변경 완료
***

Resolve #1027 - [Alibaba] When creating VM Spec, I always got an unnecessary error message.

---

cloud-control-manager/cloud-driver/drivers/ktcloud/resources/MyImageHandler.go
cloud-control-manager/cloud-driver/drivers/ncpvpc/README.md

- Update NCP VPC README.md
- Add reference links for using VPC and Subnet (about available Private IP range)
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1035
- Update KT Cloud Classic MyImageHandler
- Fix Typo

Update NCP VPC README - Add reference links for using VPC and Subnet (about available Private IP range)

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/PriceInfoHandler.go

- 기존 ProductFamily : AmazonEC2 → CPU Credits ~ System Operation 변경
- 기존 NextToken 인자 값 고려 X → NextToken 값이 있다면 세팅 후 다음 상품 정보 조회
- ProductFamily 변경
- ProductFamily 목록
"productFamily": "CPU Credits",
"productFamily": "Compute Instance (bare metal)",
"productFamily": "Compute Instance",
"productFamily": "Dedicated Host",
"productFamily": "EBS direct API Requests",
"productFamily": "Elastic Graphics",
"productFamily": "Fast Snapshot Restore",
"productFamily": "Fee",
"productFamily": "Load Balancer",
"productFamily": "Load Balancer-Application",
"productFamily": "Load Balancer-Network",
"productFamily": "NAT Gateway",
"productFamily": "Provisioned Throughput",
"productFamily": "Storage Snapshot",
"productFamily": "Storage",
"productFamily": "System Operation",
- ServiceCode → AmazonEC2 고정
- …

AWS PriceInfo reset ProductFamily and add NextToken logic

---

cloud-control-manager/cloud-driver/drivers/ktcloud/README.md
cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_VMHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloud/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VMHandler.go
cloud-driver-libs/cloudos_meta.yaml

- Update KT Cloud Classic VMHandler 
- Simplify the CreatePortForWarding Preliminary process and Add Time-sleep after Creation of a Public IP
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1061
- Update Validation checking process for Root disk Type/Size specification
: Apply KT Cloud constraints on Root Disk Type/Size
- Update KT Cloud Classic DiskHandler  
- Update related to supporting Data Disk Type
- Update KT Cloud Classic README.md
- Add Root/Data disk Type/Size related notices
: Apply KT Cloud constraints on Root Disk Type/Size
- Update CloudOS Meta-info for KT Cloud Classic
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1060

Simplify the CreatePortForWarding Preliminary process, and Apply KT Cloud constraints on Root Disk Type/Size

---

.github/workflows/korean-checker-post-comment.yaml
.github/workflows/korean-checker.yaml

Related to #1070, #1080
This PR will resolve a secrets (e.g., GITHUB_TOKEN) access permission issue of korean-checker workflow.
**Cause of issue**
- When a PR is opened from the forked repo, there is no permission to access secrets on the upstream repo.
- The secret was needed to leave a PR comment, but an error occurred because it could not be accessed.
**To resolve this issue securely, 2 workflows are needed.**
- `korean-checker.yaml` workflow: it has read permission and checks Korean text.
- `korean-checker-post-comment.yaml` workflow: it has write permission and leaves a comment on a PR.
(See [Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/))
<ins>Afterwards, …

Update workflows to check Korean texts on PR

---

cloud-control-manager/cloud-driver/drivers/ncp/main/Test_ImageHandler.go
cloud-control-manager/cloud-driver/drivers/ncp/resources/ImageHandler.go

- Update NCP Classic ImageHandler
- Add CheckWindowsImage() method for CB-Spider server
- Related issues
- https://github.com/cloud-barista/cb-spider/issues/1041 
- https://github.com/cloud-barista/cb-spider/issues/1045

[NCP Classic] Add CheckWindowsImage() method for CB-Spider server

---

cloud-control-manager/cloud-driver/drivers/aws/resources/CommonAwsFunc.go
cloud-control-manager/cloud-driver/drivers/aws/resources/PriceInfoHandler.go

Issue - #1089 
- Product Family(Compute Instance, Storage, Load Balancer-Network)에 해당하는 ProductInfo 값 매칭 및 불필요한 값 제거
- CommonAwsFunc.go
- func ReplaceEmptyWithNAforComputeInstance()
- func ReplaceEmptyWithNAforStorage()
- func ReplaceEmptyWithNAforLoadBalancerNetwork()
- 각 ProductFamily에 해당하는 값들만 출력
- Compute Instance ProductFamily 반환값
- Storage ProductFamily 반환값
- Load Balancer-Network 반환값
---
- Matching ProductInfo values and removing unnecessary values for the Compute Family (Compute Instance, Storage, Load Balancer-Network)
- CommonAwsFunc.go
- func ReplaceEmptyWithNAforComputeInstance()
- func ReplaceEmptyWithNAforStorage()
- func ReplaceEmptyWithNAforLoadBalancerNetwork()
- Output only values corresponding to each ProductFamily
- Output Compute Instance ProductFamily
- Output …

AWS Matching the corresponding ProductFamily values

---

cloud-control-manager/cloud-driver/drivers/azure/resources/PriceInfoHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/RegionZoneHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/PriceInfoHandler.go

- [Azure: Make filtering to work as a full matching](https://github.com/cloud-barista/cb-spider/commit/aced0c290afe2b8ea0550365ae529ee1e89e9ba3)
- [Azure: Get only physical regions](https://github.com/cloud-barista/cb-spider/pull/1092/commits/bbc4319a955275c1275ebedf1a4dd1edea53cce3)
```
This will fix the issue of resources not showing in some regions.
Got the hint from : https://stackoverflow.com/questions/69508883/azure-regions-what-does-stage-mean
Regions can be referenced from : https://azure.microsoft.com/en-us/explore/global-infrastructure/geographies/#geographies
As of February 23, 2024, resources are still not available in the regions below.
- brazilus
- eastusstg
```
- [IBM: Make filtering to work as a full matching](https://github.com/cloud-barista/cb-spider/commit/beb49886252fa8 …

[+Price, +Region] [Azure, IBM] Make filtering to work as a full matching, Fix resources are not showing in some regions

---

cloud-control-manager/cloud-driver/drivers/alibaba/resources/KeyPairHandler.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/MyImageHandler.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/PriceInfoHandler.go

***
- GPU가 없을 경우: GPU 및 GPU Memory 값 통일 필요
- 둘다 값을 제공하지 않던지, 둘다 0 값으로 제공하든지
- VolumeType: NA ~ 이후 값은 productFamily 입력값이 Storage 관련된 값일 경우 제공하는 정보로 compute인 'ecs'의 경우 삭제 필요
- 무시해도 되는 메시지라면 로그 출력시 Error() 대신, Info() 또는 Debug()등 처리하도록 수정 필요  
***
***
-  Storage 맵핑시 빠트린 것인지, NA인지 확인 필요 : NA 처리
- GPU 및 GPU Memory 값 통일 필요  : 값 없으면 NA 처리 
- 무시해도 되는 메시지라면 로그 출력시 Error() 대신, Info() 또는 Debug()등 처리하도록 : 수정 완료
- 추가로 Alibaba 작업 진행시 한글 -> 영문명 변경 처리  및 무시 메시지라면 error - > info 또는 Debug 변경 작업 
***

feature isseu1073 240219

---

cloud-control-manager/cloud-driver/drivers/tencent/resources/CommonHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/CommonTencentFunc.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/MyImageHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/NLBHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/PriceInfoHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/VMSpecHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/VPCHandler.go

Related Issue - https://github.com/cloud-barista/cb-spider/issues/1090
1. Price 조회 결과 개수 확인
- 236개 규모 확인 → O
- 총 pricing policy개수 : 610개이지만 중복 price가 374로 확인 610-374 = 236
- 236개의 규모 O
- 텐센트 클라우드에서는 각각의 pricing policy로 보지만 spider의 price는 인스턴스 타입별로 묶이기 때문
- Policy - SPOTPAID가 누락되어 수정
- Price조회 결과에서 POSTPAID, SPOTPAID 값이 정상적으로 인식되지 않아 결과값에서 누락됨
- 처리완료
- POSTPAID → cvm.ItemPrice 객체 반환
- SPOTPAID → *cvm.ItenPrice 포인터 반환
2. Price 조회 결과 목록 수정
- ProductFamily - Storage 관련 Product Info값 제거
**[기타]**
- log level 수정 : error 가 아닌 부분 → cblogger.Debug()
---
1. Check the number of Price lookup results
- 236 Size Check → O
- Total number of pricing policies: 610 but duplicate price is 374 confirmed 610-374 = 236
- 236 magnitude O
- In Tencent Cloud, each pricing policy is viewed, but the price of spider …

[Tencent] Remove storage ProductFamily and add SPOTPAID missing

---

api-runtime/rest-runtime/admin-web/AdminWeb-VM.go
cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_VMHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloud/resources/MyImageHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VMHandler.go

- Update KTCloud Classic VMHandler
- Apply blank("") option as a Default RootDiskType and RootDiskSize for Spider server
- Ref : https://github.com/cloud-barista/cb-spider/wiki/Disk-and-Driver-API
- Related issue : https://github.com/cloud-barista/cb-spider/issues/1061
- Update VM Termination Logic
- Update AdminWeb
- Update KTCloud Default Image/Spec info for Spder API based Testing
- Update KTCloud Classic MyImageHandler
- Handle if created MyImage does not exist

[KT Cloud Classic] Apply blank("") option as a Default RootDiskType and RootDiskSize for Spider, and Update VM Termination Logic

---

.github/workflows/korean-checker-post-comment.yaml

This PR will modify the workflow to make comments only when Korean texts are included in later PRs.
<ins>I'd like to open this PR in advance.</ins> (I think it's okay if it will be decided later.)
**Why it is needed**
: In the current workflow, comments are left both when the PR contains Korean text and when it does not.
: There are definitely pros and cons to leaving a comment, even when it doesn't include Korean text.
- Pros: Check results clearly
- Cons: Too many comments
**Proposal**
: I think it would be good **to merge or close this PR at an appropriate time later**.
- If merged: Only make a comment if Korean texts are included.
- If closed: Make a comment both when Korean texts are included and when it does not.
Note - no conflict with other PR is expected.

Modify workflow to make comments only when Korean texts are included

---

cloud-control-manager/cloud-driver/drivers/aws/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/VPCHandler.go

[AWS] Add Default Region/Zone to Connection and Allow API Calls to Specify Target Zone
VPC는 Region base, Subnet은 zone base 이므로
subnet 생성시 zone parameter가 있으면 해당 zone을 사용하도록 보완.
VPCs are based on Regions and Subnets are based on zones, when creating a subnet, if a zone parameter is provided, it should be adjusted to use the specified zone
if reqSubnetInfo.Zone != ""{
zoneId = reqSubnetInfo.Zone
}
Disk는 zone base이므로 생성시 zone parameter가 있으면 해당 zone을 사용하도록 보완.
Disks are based on zones, when creating a disk, if a zone parameter is provided, it should be adjusted to use the specified zone.
if diskReqInfo.Zone != ""{
zone = diskReqInfo.Zone
}

[AWS] Add Default Region/Zone to Connection and Allow API Calls to Specify Target Zone by #1067

---

cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_MyImageHandler.go
cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/nhncloud/resources/MyImageHandler.go
cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMHandler.go
cloud-driver-libs/.cloud-init-nhncloud/cloud-init-windows

- Update NHN Cloud ImageHandler
- Add isPublicImage() method
- Update NHN Cloud MyImageHandler
- Add isPublicImage() method
- Add CheckWindowsImage() method
- Update NHN Cloud VMHandler
- Add Windows OS Image Supporting features
: Support Windows VM Login with 'cb-user' account using cloud-init
- Update NHN Cloud 'cloud-init-windows' script
- Related issue : https://github.com/cloud-barista/cb-spider/issues/1136

[NHN Cloud] Add Windows OS Image Supporting features (Login with 'cb-user' account)

---

cloud-driver-libs/cloudos_meta.yaml

NHNCloud에서 제공하는 클러스터의 최대 이름 길이(32자)를 설정합니다.
https://docs.nhncloud.com/ko/Container/NKS/ko/user-guide/#_2

Set idmaxlength of cluster for NHNCloud

---

api-runtime/rest-runtime/test/connect-config/15.ktcloudvpc-conn-config.sh
cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VPCHandler.go

- Update KT Cloud VPC - VPCHandler
- Update DeleteVPC() method
- Leave 'NLB-SUBNET' subnet without Deletion during DeleteVPC() processes
- Update KT Cloud VPC - VMHandler
- Update getFirewallRuleIDs() method
- [Bug Fix] Remove Outbound Firewall Rules, too, during VM Termination processes
- Update KT Cloud VPC connection config (15.ktcloudvpc-conn-config.sh)
- Add Comments for Credential Info
- Ex) Add Comment for menu to get the Project ID of the account

[KT Cloud VPC] Update getFirewallRuleIDs() - Includes Outbound Rules to Remove, Update DeleteVPC() - Leave NLB-SUBNET without Deletion

---

api-runtime/rest-runtime/admin-web/AdminWeb-VM.go
cloud-control-manager/cloud-driver/drivers/ktcloudvpc/README.md
cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VMHandler.go
cloud-driver-libs/cloudos_meta.yaml

- Update cloudos_meta.yaml
- Add KT Cloud VPC disk type/size and idmaxlength values
- Update AdminWeb-VM.go
- Add KT Cloud VPC default Ubuntu Image name and Spec name
- Update KT Cloud VPC VMHandler
- Add Default disk size validation codes for Linux and Windows OS
- Update KT Cloud VPC DiskHandler
- Remove spew.Dump code in GetDisk() method

[KT Cloud VPC] Add disk type/size and idmaxlength values to cloudos_meta, Add default Ubuntu Image name and Spec name for AdminWeb-VM

---

cloud-control-manager/cloud-driver/drivers/nhncloud/NHNCloudDriver.go
cloud-control-manager/cloud-driver/drivers/nhncloud/connect/NHN_CloudConnection.go
go.sum

NHNCloud 중 NKS를 지원하는 리전만 container-infra를 접근할 수 있도록 수정하였습니다.
fix #1161

Prevent to access to container-infra in nhncloud's jpn region

---

api-runtime/rest-runtime/test/connect-config/11.ktcloud-conn-config.sh
cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_ImageHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloud/main/config/config.yaml.sample
cloud-control-manager/cloud-driver/drivers/ktcloud/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloud/resources/RegionZoneHandler.go

- Update KT Cloud Classic ImageHandler and Test Code of it
- In case, Failed to find the Image, returns an error
- Remove Unnecessary Logs during Find an Image Info with Image(Template) ID
- Related issue : https://github.com/cloud-barista/cb-spider/issues/1160
- Remove HA(KimHae) region from RegionZoneHandler, Connection config and config.yaml
- Related issue : https://github.com/cloud-barista/cb-spider/issues/1145

[KT Cloud Classic] Update ImageHandler : In case Failed to find the Image, returns an error, and Remove HA(KimHae) region

---

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VPCHandler.go

- [Support setting zone for VPC](https://github.com/ish-hcc/cb-spider/commit/900621a96947d795ed85092a206623a6225a9efb)
- [Support setting zone for disk](https://github.com/ish-hcc/cb-spider/commit/86a8e8e3101974b8a0a6aa4f9124cbc26efd0806)

IBM: Support zone setting for IBM Driver

---

cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go

**[작업 방향]**
- 제안해주신 방법처럼 
- 400 bad request `~not support live migration` 에러 발생하는 경우
- OnHostMaintenance 설정을 TERMINATE 로 변경하여 
- 재요청을 하는 방식으로 수정했습니다.
- 다만 google 에서 `not support live migration` 에러 메시지를 변경하는 경우 정상 작동하지 않을 리스크가 있습니다.
<br>
**[작업 내용]**
- GPU 기능을 테스트하기 위한 임시 조치 코드를 제거
- 게스트 가속기가 있는 인스턴스 인스턴스 생성시 400 에러와 함께 'not support live migration' 구문이 에러에 포함되어 있는 경우 'OnHostMaintenance'를 'TERMINATE'로 설정하여 VM 생성 요청을 다시 보내는 코드를 추가
<br>
**[테스트]**
- 로컬 spider admin web 에서
1. `machine type: e2-standard-2`
2. `machine type: g2-standard-4` -> GPU 머신 유형
- 상기 2개의 머신 타입으로 프로비저닝 -> 기대 동작대로 작동 확인
<br>
**[참고사항]**
- 인스턴스 유지 보수 중 라이브 마이그레이션 제한 사항의 경우 GPU 가 연결된 vm 뿐만 아니라,
- 다른 조건의 vm 도 포함되는 것으로 보입니다. ([링크](https://cloud.google.com/compute/docs/instances/live-migration-process?hl=ko#limitations))

[GCP:GPU] Fix to Provision VMs with GPU Accelerators

---

cloud-control-manager/cloud-driver/drivers/alibaba/resources/CommonHandler.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMHandler.go

Related Issue - #1149 
[DescribeAvailableSystemDisksByInstanceType]
- DescribeAvailableResource Api로 인스턴스 타입 별 사용 가능한 SystemDisk목록을 가져온다
[StartVM]
- RootDiskType : Default 일 때
- DescribeAvailableSystemDisksByInstanceType API로 입력받은 InstanceType의 사용 가능한 DiskType 목록을 받아온다
- 받아온 DiskType 목록과 Alibaba Meta 정보의 RootDiskType 목록과 비교하여
- Meta 정보의 리스트 중에 지원 가능한 DiskType 중 처음으로 오는 값을 찾아 세팅한다
- RootDiskType : 설정 값이 있을 때
- 받은 Disk타입이 위에서 받은 지원 가능한 Disk목록을 이용해여 유효한지 체크한다
- 있다면 세팅하고 없다면 에러 리턴
---
[DescribeAvailableSystemDisksByInstanceType]
- Get a list of available SystemDisk by instance type with DescriptAvailableResourceApi
[StartVM]
- RootDiskType : Default 일 때
- Obtain a list of available disk types of InstanceType entered by the DescriptAvailableSystemDisksByInstanceType API
- Compare the received …

[Alibaba] Resolve issue : Default RootDiskType Option When Creating VM

---

cloud-control-manager/cloud-driver/drivers/ncp/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/ncp/resources/NLBHandler.go
cloud-control-manager/cloud-driver/drivers/ncp/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/ncp/resources/VMSpecHandler.go
cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/RegionZoneHandler.go
cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/VMHandler.go

[ NCP Classic ]
- Update VMHandler, VMSpecHandler, DiskHandler, NLBHandler
- Update GetRegionNo()
- Add checkAndSetRegionNoList()
: Set as global map parameter to get region num. of each region code to reduce CSP API calls
- Update GetZoneNo()
- Add checkAndSetZoneNoList()
: Set as global map parameter to get zone num. of each zone code to reduce CSP API calls
[ NCP VPC ]
- Adjust the Time Sleep to reduce CSP API calls
- Update RegionZoneHandler
- Update logging

[NCP Classic/VPC] Update VMHandler GetRegionNo()/GetZoneNo() and Adjust the Time Sleep to Reduce CSP API calls

---

api-runtime/rest-runtime/test/connect-config/13.nhncloud-conn-config.sh
cloud-control-manager/cloud-driver/drivers/nhncloud/main/conf/config.yaml.sample
cloud-driver-libs/cloudos_meta.yaml

- Update NHN Cloud Credential Info > API identity_endpoint URL
- Ref) https://www.nhncloud.com/kr/support/notice/detail/4145
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1195
- Note) For reference, cloud resources end-point information (for each zone) are found in the provider client information after first authentication in NHN Cloud Go SDK.
- Update Cloud OS Meta info for KT Cloud VPC NLB name length to create NLB successfully through API call

[NHN Cloud] Update Credential Info > identity_endpoint URL

---

cloud-control-manager/cloud-driver/drivers/alibaba/resources/CommonHandler.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMHandler.go

https://github.com/cloud-barista/cb-spider/issues/1148
- VM 생성중 제공하지 않는 ImageID를 인자로 입력 시 다음과 같이 에러 원인과 관련 없는 메시지 출력을 다음과 같이 수정함.
Before
```
return ecs.Image{}, errors.New("no result")
```
After
```
return ecs.Image{}, errors.New("no result with request image IID(NameId/SystemId) : " + imageIID.NameId + "/" + imageIID.SystemId)
```

[Alibaba:VM] Incorrect Error Message When Using Unsupported ImageID During VM Creation #1148

---

cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VMHandler.go

- Update KT Cloud VPC > VMHandler
- Add time.Sleep to Prevent Errors after each Firewall Rule Creation API call
- Note) A plurality of calls to create a Firewall Rule causes errors
: "json: cannot unmarshal string into Go struct field AsyncJobResult.nc_queryasyncjobresultresponse.result of type job.JobResult"

[KT Cloud VPC] Add time.Sleep to Prevent Errors after each Firewall Rule Creation API call

---

cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VPCHandler.go

- Prevent 'Failed to Get VPC ID' error in case of Get/List of VM info. when there is No Portforwarding Rule
- Update VPCHandler
- Adjust time.Sleep for Adding Subnet

[KT Cloud VPC] Prevent an Error in case of Get/List of VM info. when there is No Portforwarding Rule

---

cloud-control-manager/cloud-driver/drivers/nhncloud/README.md
cloud-control-manager/cloud-driver/drivers/nhncloud/resources/NLBHandler.go

- Update VPCHandler
- Use VPC ID instead of VPC Name to get the first Subnet ID
- Update README.md
- Add Notice of Internet Gateway Setting
- Add Notice of User Password Setting Method for MS Windows VM

[NHN Cloud] Use VPC ID instead of VPC Name to get the first Subnet ID, and Add Notice of Internet Gateway Setting

---

cloud-control-manager/cloud-driver/drivers/ktcloud/resources/CommonKtCloudFunc.go
cloud-control-manager/cloud-driver/drivers/ktcloud/resources/KeyPairHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VMSpecHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/CommonKTCloudFunc.go
cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/MyImageHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/NLBHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/ncp/resources/CommonNcpFunc.go
cloud-control-manager/cloud-driver/drivers/ncp/resources/NLBHandler.go
cloud-control-manager/cloud-driver/drivers/ncp/resources/PriceInfoHandler.go
cloud-control-manager/cloud-driver/drivers/ncp/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/NLBHandler.go
cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/PriceInfoHandler.go
cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/nhncloud/resources/CommonNhnCloudFunc.go
cloud-control-manager/cloud-driver/drivers/nhncloud/resources/NLBHandler.go

- Update NCP Classic/VPC driver, NHN Cloud driver, KT Cloud Classic/VPC driver
- Remove fmt.Print and spew.Dump statements
- Related issue : https://github.com/cloud-barista/cb-spider/issues/1207

[Domestic Cloud Drivers] Remove fmt.Print and spew.Dump statements

---

cloud-control-manager/cloud-driver/call-log/calllogger.go
cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/interfaces/resources/TagHandler.go

- Change the way set config file path
os.Getenv("CBSPIDER_PATH")+ "/config/config.yaml" --> confPath := os.Getenv("CBSPIDER_TEST_CONF_PATH")
- Added TAG resources to calllogs
`	TAG           RES_TYPE = "TAG"
`
- fixed typos in variable names for interfaces
resTyp --> resTyp**e**

Added TAG resources to calllogs and fixed typos in variable names for interfaces

---

api-runtime/rest-runtime/admin-web/AdminWeb-VM.go

- Update NCP Classic/VPC VMImage Name for VM Creation Testing on CB-Spider AdminWeb
- Corresponding region/zone :  KR/KR-1

[NCP Classic/VPC on AdminWeb] Update VMImage Name for VM Creation Testing

---

cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/NLBHandler.go

- Update NCP VPC NLBHandler
- Return Debug message instead of Error message when NLB does not exist. (After NLB termination)
- Related issue : https://github.com/cloud-barista/cb-spider/issues/1207

[NCP VPC] Return the Debug message instead of Error message when NLB does not exist.

---

cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMSpecHandler.go
go.mod
go.sum

- Update NHN Cloud VMSpecHandler
- Add 'VMSpecType' info to VMSpec KeyValue info
- Update nhncloud-sdk-go version

[NHN Cloud] Add 'VMSpecType' info to VMSpec KeyValue info

---

cloud-control-manager/cloud-driver/drivers/aws/AwsDriver.go
cloud-control-manager/cloud-driver/drivers/aws/connect/AwsCloudConnection.go
cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/TagHandler.go
cloud-control-manager/cloud-driver/interfaces/resources/TagHandler.go

Implementing the FindTag feature

Implementing the FindTag feature

---

cloud-control-manager/cloud-driver/drivers/azure/resources/ImageHandler.go

- Prevent request limit while getting image list
Related Issue: #1260

Azure: Prevent request limit while getting image list

---

cloud-control-manager/cloud-driver/drivers/azure/resources/ImageHandler.go

- [Only get latest image verison](https://github.com/cloud-barista/cb-spider/commit/d4ef599103008ce07483ec8c9a2ed79f779217b7)
- [Get cached image list when requesting again within 1 hour](https://github.com/cloud-barista/cb-spider/commit/574b3005253ca35980ca70ad8dba6c0482cfaa92)
- New request: List appeared within about 10 minutes.
- Request again: List appeared within about 30 seconds.

Azure: Improve of getting image list

---

cloud-control-manager/cloud-driver/drivers/azure/resources/ClusterHandler.go

AZ가 없을때 AvailabilityZones 필드를 설정하지 않도록 수정하여 클러스터 생성이 실패하지 않도록 합니다.
fix #1246

Fix to create cluster for non AZ region in azure

---

.github/workflows/korean-checker.yaml

Korean checker에서 Unbalanced quote으로 인해 발생한 에러를 해결하기 위한 PR 입니다.
* Ref) https://github.com/cloud-barista/cb-spider/pull/1271#issuecomment-2275921517
테스트 하기에 마땅하지 않은 관계로, 우선 master에 적용한 후 대응하도록 하면 좋을 것 같습니다. 
* 따라서, 당분간 Korean checker 결과는 개의치 마시고, PR review 및 merge를 진행하시기 바랍니다.

Fix error by the unbalanced quote in Korean checker workflow

---

.github/workflows/korean-checker.yaml

This PR will fix a bug in whitespace trimming in the Korean checker workflow.

Bugfix: Whitespace trimming in the Korean checker workflow

---

cloud-control-manager/cloud-driver/drivers/alibaba/resources/PriceInfoHandler.go

https://github.com/cloud-barista/cb-spider/issues/1274
- Price 정책은 존재하지만, detail price 데이터가 없을때, 발생하는 오류 입니다.
- Infof 로 에러 대신하도록 수정했습니다.
```
cloud-control-manager/cloud-driver/drivers/alibaba/resources/PriceInfoHandler.go
...
} else {
// return irs.PricingPolicies{}, errors.New("No Price Data") // https://github.com/cloud-barista/cb-spider/issues/1274
cblogger.Infof("No Price Data at PricingId[%s]", pricingPolicy.PricingId)
return pricingPolicy, nil
}
...
```

alibaba fix price data is nil

---

cloud-control-manager/cloud-driver/drivers/aws/resources/RegionZoneHandler.go

@dev4unet @powerkimhub 
https://github.com/cloud-barista/cb-spider/issues/1292
```
sess, err := session.NewSession(&aws.Config{
+ Credentials: regionZoneHandler.Client.Config.Credentials,
Region:      region.RegionName,
})
if err != nil {
cblogger.Error(err)
}
tempclient := ec2.New(sess)
```
Credentials: regionZoneHandler.Client.Config.Credentials 추가하여 기존 세션만 생성되던 부분 수정했습니다.

AWS Region/Zone list lookup error in AdminWeb

---

cloud-control-manager/cloud-driver/drivers/azure/resources/ClusterHandler.go
go.mod
go.sum

UpgradeCluster() API 호출시 클러스터(master) 업그레이드 후 포함된 노드그룹(nodepool in azure)들의 업그레이드를 요청하도록 수정하였습니다.

[azure:pmks] upgrade nodegroups when upgrading a cluster

---

cloud-control-manager/cloud-driver/drivers/aws/AwsDriver.go
cloud-control-manager/cloud-driver/drivers/aws/connect/AwsCloudConnection.go
cloud-control-manager/cloud-driver/drivers/aws/resources/AnyCallHandler.go

- aws cost explorer 사용을 위해 aws anycall handler 에 cost exeplorer client 추가
- aws cost explorer 의 getCostAndUsageWithResources 호출을 위한 함수 구현
---
getCostWithResource 함수는 지정된 매개변수에 따라 AWS Cost Explorer에서 AWS 리소스의 비용 및 사용량 데이터를 쿼리한다. spider 의 aws anycall handler 를 확장해서 기능을 구성했다.
```go
func getCostWithResource(anyCallHandler *AwsAnyCallHandler, callInfo irs.AnyCallInfo) (irs.AnyCallInfo, error)
```
**`anyCallHandler`**
- 타입: *AwsAnyCallHandler
- 설명: AWS 호출 핸들러로, AWS Cost Explorer 클라이언트에 접근 가능
**`callInfo`**
- 타입: irs.AnyCallInfo
- 설명: 요청에 대한 정보를 포함하며, 응답으로 업데이트
callInfo 매개변수는 **requestBody** 키 아래에 JSON 본문을 포함해야 한다. 이 JSON은 `CostWithResourceReq `구조에 맞아야하며 `CostWithResourceReq `는 다음과 같은 구조를 가진다.
**`StartDate: string`**  required
- 설명: 비용 및 사용량 보고서의 시작 날짜 (형식: YYYY-MM-DD)
- 조회 조건에 포함
**`EndDate: …

initialize aws cost explorer getCostAndUsageWithResource anycall handler function

---

cloud-control-manager/cloud-driver/drivers/alibaba/connect/AlibabaCloudConnection.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/CommonHandler.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/VPCHandler.go

@powerkimhub 
- https://github.com/cloud-barista/cb-spider/issues/1299 
- 위 이슈에 대한 PR입니다.
- getSubnet()
- CommomHandler.go로 이동
- startVM() 
- zone 체크 로직 추가

[Alibaba] resolve issue of Incorrect Zone-based control for VM

---

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/resources/CommonHandler.go

[[AWS:MyImage] Access Nil Pointer](https://github.com/cloud-barista/cb-spider/issues/1314) bug fixed.
If the SnapshotId cannot be retrieved, it delivers the message below.
"The SnapshotId information could not be found in the block device mapping(Ebs) information, please try again in a moment"

Resolved SnapshotId bug when deleting MyImage (Issue #1314)

---

cloud-control-manager/cloud-driver/drivers/openstack/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go

- [Add support to get VM's zone information](https://github.com/cloud-barista/cb-spider/commit/efbfbb2ff3633927ff72d055058d6dc295c8c9ac)
- [Fix floatingip API issue](https://github.com/cloud-barista/cb-spider/commit/8657aae1a829084cd44e4f02069474c56541c0a6)
- [Set target zone in disk handler](https://github.com/cloud-barista/cb-spider/commit/4c079bf121f6fbe832849f4a15d177845556477a)
- 특이사항
- OpenStack에서 Disk는 Zone에 의존되지 않음.
- AdminWeb을 통해 다른 Zone에 생성한 Disk도 드라이버 수준에서 Test_Resources.go를 통해 정상적으로 Attach 됨.
- AdminWeb의 VM Provisioning Info에서도 생성한 VM의 Zone 정보와 Attach된 다른 존에 있는 Data Disk 정보가 올바르게 표시됨

[OpenStack] Fix zone control

---

cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/azure/resources/ClusterHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/DiskHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/KeyPairHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/MyImageHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/NLBHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/VPCHandler.go

- Implement ListIID() for all resources.

[Azure] Implement ListIID()

---

cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go
cloud-control-manager/cloud-driver/drivers/azure/resources/ClusterHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/CommonAzureFunc.go
cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go

- Support of getting scale set VM info
- This fixes issue of getting information of node group VMs.
- Related issue: https://github.com/cloud-barista/cb-spider/issues/1353

[Azure] Support of getting scale set VM info

---

cloud-control-manager/cloud-driver/drivers/openstack/resources/VMSpecHandler.go

- Remove a wrong key-value in VMSpec

OpenStack: Remove a wrong key-value in VMSpec

---

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMSpecHandler.go

- Return Gpu Info data based on Profile Name pattern
- [Mfr]-[?]-[Mem(GB)]x[Count][Mdoel]
- gx2-16x128x2v100 -> 2 NIVIDIA V100 131072(MB)

Ibm: add Disk, GPU information in VMSpec

---

cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ImageHandler.go

NHN: Add more VM image info

---

cloud-control-manager/cloud-driver/drivers/gcp/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/VMSpecHandler.go
go.mod
go.sum

Tencent 는 
- Spec 정보에 Disk 지원하지 않음.
- Spec 정보에 GPU의 count 외 정보가 없음. 별도의 gpu info api도 없음
- cpu clock의 경우 CPU의 기본 주파수(Base Frequency)와 최대 터보 주파수(Max Turbo Frequency) 를 병기하고 있음
ex) 기본주파수/터보주파수 :   "Frequency": "-/3.1GHz", "Frequency": "2.5GHz/-", "Frequency": "2.5GHz/3.1GHz",
기본주파수를 base로 둘다 있으면 기본주파수,  터보주파수만 있으면 터보주파수를 사용하도록
api 버전 변경 : 기존 DescribeInstanceTypeConfigs가 DescribeZoneInstanceConfigInfos로 변경됨.
as-is 
github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.964
github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm v1.0.493
to-be
github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.1064
github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm v1.0.1064

Issue 1396 metadata vmspec for tencent

---

api-runtime/rest-runtime/admin-web/html/vm.html

**I upgraded the Disk Selection UI to use checkboxes**(VM Creation with disk is also available).
1. No disks are Available in the Zone
<p aligh='center'>
</p>
---
2. Disks are Available in the Zone
<p aligh='center'>
</p>

Enhance UI of Disk Selection in VM Creation Phase

---

.github/workflows/continuous-delivery.yaml

[Enable linux/arm for the continuous-delivery image build](https://github.com/cloud-barista/cb-spider/commit/04a12592d593a79d1b71b66f91d514efd18ea454) for Mac users.

Enable linux/arm for the continuous-delivery image build

---

cloud-control-manager/cloud-driver/drivers/ncp/README.md
cloud-control-manager/cloud-driver/drivers/ncp/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/ncp/resources/MyImageHandler.go
cloud-control-manager/cloud-driver/drivers/ncp/resources/VMHandler.go
cloud-control-manager/cloud-driver/drivers/ncp/resources/VMSpecHandler.go
cloud-control-manager/cloud-driver/drivers/ncpvpc/README.md
cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/VMSpecHandler.go

- Update NCP Classic VMSpecHandler
- Update GetVMSpec() to include 'CorrespondingImageIds' parameter for return value
- Update NCP VPC VMSpecHandler
- Update ListVMSpec() : Remove duplicate VMSpec info
- Update GetVMSpec() to include 'CorrespondingImageIds' parameter for return value
- Enhance Supported VM Spec Info
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1396 
- Update NCP Classic/VPC README.md
- Add caveats for specifying VMSpec when creating a VM
- Update NCP Classic ImageHandler, MyImageHandler
- Change the first letter of non-major functions to lowercase

[NCP Classic/VPC] Update VMSpecHandler - Update ListVMSpec() / GetVMSpec() and Enhance Supported VM Spec Info

---

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/NLBHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/SecurityHandler.go
cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/TagHandler.go

- Fix loadbalancer connection issue
- 로드밸런서에서도 Security Group을 지정하도록 되어 있었습니다.
- 기존에는 Default Security Group으로 설정되면서 내부 통신만 허용이 되면서 외부 접근이 차단되었습니다.
- VM에서 사용중인 첫번째 Security Group을 지정하도록 하여 문제를 해결하였습니다.
- IBM SDK로는 로드밸런서 생성시 1개의 Security Group만 지정 가능합니다.
- [IBM: Need to set security group when creating NLB](https://github.com/ish-hcc/cb-spider/commit/40acce2cef6aea59dd619de3501577371e201026)
- [IBM: Make available to check security group by system ID](https://github.com/ish-hcc/cb-spider/commit/bf6a537bc2f3626dbb41d76df787aa16eadd92d3)
- SSH 22번 포트 기준 LoadBalancer를 생성할때
- VM의 22번 포트를 기존 VM의 Public IP 로 접근이 가능하다가
- LoadBalancer를 생성하고 나면 LoadBalancer Public IP로만 22번 포트 접근이 가능합니다
- VM 내에서 nginx를 구동하여 테스트를 추가로 해보았는데, 기존 VM Public IP로 nginx 80포트 접근은 가능합니다.
- 테스트 구성
- LoadBalancer - 퍼블릭
- DNS - …

IBM: Fix loadbalancer connection issue

---

cloud-driver-libs/region/ktcloud_region_meta.yaml
cloud-driver-libs/region/ktcloudvpc_region_meta.yaml

[KT Cloud Classic/VPC]
- Enhance Supported RegionZone Info
- Add ktcloud_region_meta.yaml (Missed file when committing)
- Add ktcloudvpc_region_meta.yaml (Missed file when committing)
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1389

[KT Cloud Classic/VPC] Add region_meta.yaml files

---

cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/ImageHandler.go
cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VMSpecHandler.go

[KT Cloud VPC(D platform)]
- Update ImageHander
- Change OS Disk Size value in VM Image info
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1463
- Update VMSpecHandler
- Change Disk Size value in VMSpec info

[KT Cloud VPC(D platform)] Change Disk Size value in VMImage and VMSpec info

---

cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VMSpecHandler.go

[KT Cloud Classic(G1/G2 platform) connection driver]
- Update VMSepcHandler
- Update ListVMSpec() : Shorten the execution time

[KT Cloud Classic] Update ListVMSpec() - Shorten the execution time

---

cloud-control-manager/cloud-driver/drivers/gcp/resources/VMSpecHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/VMSpecHandler.go

Invalid VCpu Clock : VCpu에서 "Clock" 정보 미제공 혹은 오표기  
"N/A", "", "NA" -> "-1"로 변경 ( GCP, Tencent )

Vmspec Meta. set clock default value as -1 #1396

---

cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go
cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMHandler.go

NHNCloud의 클러스터 생성시 노드의 최소 루트디스크 크기가 20GB에서 30GB로 변경된 것으로 파악되었으며, 본 PR은 이를 반영합니다.
콘솔 상 VM의 루트디스크 크기는 여전히 20GB가 최소값으로 확인됩니다. @innodreamer

chore: [nhncloud/cluster] apply default cluster's node root disk size

---

cloud-control-manager/cloud-driver/drivers/aws/resources/ClusterHandler.go
cloud-control-manager/cloud-driver/drivers/aws/resources/CommonHandler.go

본 PR은 타 CSP와 달리 볼륨을 사용할 수 없는 상황을 개선하기 위한 것으로,
클러스터 생성시 addon인 aws-ebs-csi-driver와 eks-pod-identity-agent를 설치하고, 노드그룹 생성시 내부적으로 생성되는 노드에 대한 metadata option 중 http-put-response-hop-limit 값을 2로 변경합니다.
더불어 IAMRole 설정이나 OIDC 설정 등은 불필요한 것으로 파악되어 관련 코드를 제거합니다.
fix #1487

[AWS:PMKS] enable aws-ebs-csi-driver and eks-pod-identity-agent by default

---

cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go

본 PR은 NHNCloud의 Cluster에 대해, image name에 image id를 입력한 경우 제대로 처리하지 못하는 버그를 수정합니다.

fix: [cluster] support imagename as imageid in nhncloud

---

cloud-control-manager/CloudDriverHandler_common.go
cloud-control-manager/cloud-driver/drivers/aws/AwsDriver.go
cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/aws/main/stsTest/GenStsInfo.go
cloud-control-manager/cloud-driver/interfaces/CloudDriver.go

Summary
Added STS (Security Token Service) authentication support to the AWS driver.
Details
- No impact on existing behavior: the previously unused Token field is now utilized for STS-based authentication.
- Explicitly added the CredentialInfo.StsToken field for STS support.
- Verified basic functionality using the main/Test_Resources.go test.
- Added main/stsTest/GenStsInfo.go for generating STS-based credential test data.
- Currently, the StsToken field is applied only to credential-related APIs. Additional updates to other relevant methods are still needed.

Add STS authentication support to AWS driver

---

cloud-control-manager/cloud-driver/drivers/alibaba/doc/README_FileSystem_Test.md
cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go
cloud-control-manager/cloud-driver/drivers/alibaba/resources/FileSystemHandler.go

For more details, please refer to the **[Alibaba Cloud NAS FileSystem Test Guide](https://github.com/MZC-CSC/cb-spider/blob/feature-filestorage-ali-jsyoo/cloud-control-manager/cloud-driver/drivers/alibaba/doc/README_FileSystem_Test.md)** file.
- Fixed some errors.
- Introduced a comprehensive README for Alibaba Cloud NAS FileSystem testing, detailing implementation, supported types, storage configurations, and testing procedures.
- Updated Test_Resources.go to streamline filesystem creation examples and improve tag management.
- Enhanced validation logic for StorageType and capacity settings in FileSystemHandler, ensuring compliance with filesystem type requirements.
The following are the final tested results.
- GetMetaInfo
- FileSystem List
- FileSystem Create (Basic Setup) – Executed …

Add Alibaba Cloud NAS FileSystem Test Guide and enhance filesystem handling

---

api-runtime/common-runtime/S3Manager.go
api-runtime/rest-runtime/admin-web/AdminWeb-S3.go
api-runtime/rest-runtime/admin-web/html/s3.html

- Added multi-key credential support for GCP, IBM, NHN, KT S3 access
- cf) [S3 Storage Guide](https://github.com/cloud-barista/cb-spider/wiki/S3-Storage-Guide/433f4a8e79947b526cd335c30c817387146ec51c) 
- Enhanced AdminWeb error handling with server error parsing

[S3] Support multi-key credentials and improve adminweb error handling

---

api-runtime/common-runtime/ClusterManager.go
api-runtime/rest-runtime/CBSpiderRuntime.go
api-runtime/rest-runtime/ClusterRest.go
api-runtime/rest-runtime/admin-web/html/cluster.html
api/docs.go
api/swagger.json
api/swagger.yaml
cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go
cloud-control-manager/cloud-driver/drivers/aws/AwsDriver.go
cloud-control-manager/cloud-driver/drivers/aws/connect/AwsCloudConnection.go
cloud-control-manager/cloud-driver/drivers/aws/resources/ClusterHandler.go
cloud-control-manager/cloud-driver/drivers/azure/resources/ClusterHandler.go
cloud-control-manager/cloud-driver/drivers/gcp/resources/ClusterHandler.go
cloud-control-manager/cloud-driver/drivers/ibm/resources/ClusterHandler.go
cloud-control-manager/cloud-driver/drivers/mock/resources/ClusterHandler.go
cloud-control-manager/cloud-driver/drivers/ncp/resources/ClusterHandler.go
cloud-control-manager/cloud-driver/drivers/nhn/resources/ClusterHandler.go
cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go
cloud-control-manager/cloud-driver/interfaces/resources/ClusterHandler.go

- Updated GetCluster API to provide kubeconfig
- Added dynamic token type (AWS, GCP) and static token type (other CSPs)
- Added temporary token API for kubectl and related tools
- Verified with kubectl and OpenLens deployments
<br>
- kubconfig example for AWS
```
apiVersion: v1
kind: Config
clusters:
- cluster:
server: https://7D23A46B1EFE6826611F2FD09D4813AC.gr7.ap-southeast-2.eks.amazonaws.com
certificate-authority-data: **********************
name: aws-sydney-cluster-0f5-d39o7061pc4tged15jv0
contexts:
- context:
cluster: aws-sydney-cluster-0f5-d39o7061pc4tged15jv0
user: aws-dynamic-token
name: aws-sydney-cluster-0f5-d39o7061pc4tged15jv0
current-context: aws-sydney-cluster-0f5-d39o7061pc4tged15jv0
users:
- name: aws-dynamic-token
user:
exec:
apiVersion: client.authentication.k8s.io/v1 …
```

[K8S] Support kubeconfig with dynamic token types
