cloud-barista/cb-spider

cloud-control-manager/cloud-driver/drivers/aws/AwsDriver.go, cloud-control-manager/cloud-driver/drivers/aws/build_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/aws/connect/AwsCloudConnection.go, cloud-control-manager/cloud-driver/drivers/aws/main/Sample/config/config.yaml, cloud-control-manager/cloud-driver/drivers/aws/main/Test_Create.go, cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/main/Test_VM.go, cloud-control-manager/cloud-driver/drivers/aws/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/PublicIPHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VNetworkHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VNicHandler.go
poc-cb-spider --> cb-spider로 경로 변경
=> 아메리카노 버전 통합 개발을 위한 Repo 변경

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/resources/PublicIPHandler.go
EC2에 Public IP할당하는 부분은 공통 I/F에 별도로 분리 필요 함.
=> PublicIPHanlder 기능 구현 완료

cloud-control-manager/cloud-driver/drivers/aws/AwsDriver.go, cloud-control-manager/cloud-driver/drivers/aws/connect/AwsCloudConnection.go, cloud-control-manager/cloud-driver/drivers/aws/main/Test_Create.go, cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/main/Test_VM.go, cloud-control-manager/cloud-driver/drivers/aws/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/PublicIPHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VNetworkHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VNicHandler.go, cloud-control-manager/cloud-driver/interfaces/resources/PublicIPHandler.go
잘 못된 Import 패키지 경로 수정
github.com/cloud-barista/cb-spider/cloud-driver
→ github.com/cloud-barista/cb-spider/**cloud-control-manager**/cloud-driver
공통 IF 파일 수정(**PublicIPHandler.go**)
cloud-driver/drivers/aws/resources/PublicIPHandler.go
→ 어제 반영한 최신 내용으로 대체
=> 공통 IF및 잘 못된 Impot 경로 수정

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VNetworkHandler.go, cloud-control-manager/cloud-driver/interfaces/resources/VNetworkHandler.go
VNetworkHandler 및 테스트 샘플구현(VPC)
AWS의 VPC 생성 / 조회 / 목록 / 삭제
Test_Resources.go의 handleVNetwork()에서 테스트 가능
=> VNetworkHandler 및 테스트 샘플구현(VPC)

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VNetworkHandler.go
- CB 라우팅 테이블 찾기 기능 추가
- CB 라우팅 테이블에 생성된 서브넷 연결 기능 추가 [AWS콘솔의 서브넷 연결 탭]
- CB 라우팅 테이블에 IGW 라우팅 생성 기능 추가 [AWS콘솔의 라우팅 탭]
=> VPC & IGW 라우팅 처리 완료

api-runtime/rest-runtime/test/aws/vm/get-status-test.sh, api-runtime/rest-runtime/test/aws/vm/get-test.sh, api-runtime/rest-runtime/test/aws/vm/list-status-test.sh, api-runtime/rest-runtime/test/aws/vm/list-test.sh, api-runtime/rest-runtime/test/aws/vm/reboot-test.sh, api-runtime/rest-runtime/test/aws/vm/resume-test.sh, api-runtime/rest-runtime/test/aws/vm/start-test.sh, api-runtime/rest-runtime/test/aws/vm/suspend-test.sh, api-runtime/rest-runtime/test/aws/vm/terminate-test.sh, api-runtime/rest-runtime/test/aws/vnetwork/create-test.sh, api-runtime/rest-runtime/test/aws/vnetwork/delete-test.sh, api-runtime/rest-runtime/test/aws/vnetwork/get-test.sh, cloud-control-manager/cloud-driver/drivers/aws/AwsDriver-lib.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go
├─vm - 테스트 대기 - 테스트 완료
│      get-status-test.sh  - 정상
│      get-test.sh - 정상
│      list-status-test.sh - 정상
│      list-test.sh - 정상
│      reboot-test.sh -  **서버 기능 미지원** - {"message":" is not a valid action!!"} 에러 발생
│      resume-test.sh -  **서버 기능 미지원** - {"message":" is not a valid action!!"} 에러 발생
│      start-test.sh - 정상
│      suspend-test.sh -  **서버 기능 미지원** - {"message":" is not a valid action!!"} 에러 발생
│      terminate-test.sh -  **서버 기능 미지원** - {"message":" is not a valid action!!"} 에러 발생
│      
└─vnetwork - 테스트 중 (get / list 정상 동작)
create-test.sh - 정상
delete-test.sh - **의존성 에러** : VPC에 새로 추가한 라우팅 및 라우터로 인한 의존성 발생으로 VPC는 제거 안됨.(Subnet만 제거됨)
get-test.sh - 정상
list-test.sh - 정상
=> VM & VNetwork 테스트 완료

api-runtime/rest-runtime/test/aws/vm/reboot-test.sh, api-runtime/rest-runtime/test/aws/vm/resume-test.sh, api-runtime/rest-runtime/test/aws/vm/start-test.sh, api-runtime/rest-runtime/test/aws/vm/suspend-test.sh
VM 제어 명령 호출 시 URL 호출에 쌍따옴표 추가로 정상 동작 확인완료
=> VM 제어 명령 호출 시 URL 호출에 쌍따옴표 추가로 정상 동작 확인완료

api-runtime/rest-runtime/test/azure/keypair/create-test.sh, api-runtime/rest-runtime/test/azure/keypair/delete-test.sh, api-runtime/rest-runtime/test/azure/keypair/get-test.sh, api-runtime/rest-runtime/test/azure/keypair/list-test.sh, cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/azure/resources/KeyPairHandler.go
- Azure ssh 라이브러리 기반 KeyPair 핸들러 개발
- KeyPair REST API 테스트 쉘 스크립트 추가
- 이슈사항
**VM 핸들러 StartVM() 시 KeyPair 핸들러 기반 로그인 처리 개발
(현재 Admin Id/Password 기반 VM 생성 및 로그인 처리)**
=> Azure KeyPair 기능 추가 및 REST API 테스트 프로그램 추가

cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/azure/main/Test_VM.go, cloud-control-manager/cloud-driver/drivers/azure/resources/CommonAzureFunc.go, cloud-control-manager/cloud-driver/drivers/azure/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
- Azure VM 생성 시 KeyPair 퍼블릭 키 값 기준 로그인 기능 추가
1) PublicKey 값 가져오는 공용 함수 개발
2) Azure StartVM() 실행 시 KeyName 기준으로 PublicKey String 값 조회 가져오는 기능 추가
3) Azure StartVM() 실행 시 ssh-key 기준 로그인 기능 테스트 프로그램 개발 (Test_VM)
=> Azure VM 생성 시 KeyPair 퍼블릭 키 값 기준 로그인 기능 추가

api-runtime/rest-runtime/test/aws/image/get-test.sh, cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VNetworkHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VNicHandler.go
VPC 삭제 에러 처리
- VPC 삭제전 할당및 생성된 IGW및 라우터 제거 로직 추가
ImageHandler Get 로직 보완
- 이미지 정보를 찾지 못한 경우 err 객체는 nil이지만, API 검색 결과에 저장된 정보가 없는 경우 에러 메시지 추가
=> VPC 삭제 에러 처리

api-runtime/rest-runtime/test/openstack/vnetwork/create-test.sh, api-runtime/rest-runtime/test/openstack/vnetwork/delete-test.sh, api-runtime/rest-runtime/test/openstack/vnetwork/get-test.sh, api-runtime/rest-runtime/test/openstack/vnetwork/list-test.sh, api-runtime/rest-runtime/test/openstack/vnic/create-test.sh, api-runtime/rest-runtime/test/openstack/vnic/delete-test.sh, api-runtime/rest-runtime/test/openstack/vnic/get-test.sh, api-runtime/rest-runtime/test/openstack/vnic/list-test.sh, cloud-control-manager/cloud-driver/drivers/openstack/resources/CommonOpenStackFunc.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VNetworkHandler.go
- OpenStack REST API 테스트 스크립트 추가 (vNetwork, vNic)
-- vNetwork - 테스트 완료
-- vNic - 테스트 완료
- OpenStack 가상 네트워크 생성/삭제 시 IGW 라우터 및 인터페이스 생성/삭제 로직 추가
=> OpenStack Rest Client 기반 Test 쉘 스크립트 추가 (VNetwork, VNic)

api-runtime/rest-runtime/test/openstack/vm/get-status-test.sh, api-runtime/rest-runtime/test/openstack/vm/get-test.sh, api-runtime/rest-runtime/test/openstack/vm/list-status-test.sh, api-runtime/rest-runtime/test/openstack/vm/list-test.sh, api-runtime/rest-runtime/test/openstack/vm/reboot-test.sh, api-runtime/rest-runtime/test/openstack/vm/resume-test.sh, api-runtime/rest-runtime/test/openstack/vm/start-test.sh, api-runtime/rest-runtime/test/openstack/vm/suspend-test.sh, api-runtime/rest-runtime/test/openstack/vm/terminate-test.sh, cloud-control-manager/cloud-driver/drivers/openstack/resources/PublicIPHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
- OpenStack REST API 테스트 스크립트 추가 (VM)
├─vm - 테스트 완료 (get-status/get/list-status/list/reboot/resume/suspend/terminate 완료)
│ get-status-test.sh
│ get-test.sh
│ list-status-test.sh
│ list-test.sh
│ reboot-test.sh
│ resume-test.sh
│ start-test.sh
│ suspend-test.sh
│ terminate-test.sh
│
- 이슈사항
start-test 실행 시 associateIP 관련 에러 발생 (해당 부분 에러 확인 후 수정 필요)
=> OpenStack Rest Client 기반 Test 쉘 스크립트 추가 (VM)

cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go
Azure 이미지 핸들러의 CreateImage() 실행 시 발생 버그 fix
=> 이미지 테스트 프로그램 생성 요청 파라미터 수정

api-runtime/rest-runtime/test/gcp/image/get-test.sh
generate gcp-driver-v.1.0.so file
=> generate gcp driverfile

api-runtime/rest-runtime/test/azure/image/get-test.sh
- Azure URN 기반 이미지 조회 테스트 스크립트 추가
=> Azure URN 기반 이미지 조회 테스트 스크립트 추가

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VNetworkHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VNicHandler.go
- [이슈 #57 요청 기능 반영] vNic 생성 시 기존에 존재하는 Name Tag의 경우 중복 생성되지 않도록 예외 처리 추가
이슈 #57 TODO: Implement duplication check in vnic creation process.
- 일부 핸들러들의 Get함수에서 API 실행 시 명시적 err이 발생하지 않는 경우에 대한 예외 메시지 추가
=> - [이슈 #57 요청 기능 반영] vNic 생성 시 기존에 존재하는 Name Tag의 경우 중복 생성되지 않도록 예외 처리 추가

api-runtime/rest-runtime/test/azure/cim-insert-test.sh, cloud-control-manager/CloudDriverHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/PublicIPHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VNetworkHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VNicHandler.go, cloud-control-manager/cloud-driver/interfaces/CloudDriver.go
- Azure RegionInfo ResourceGroup 파라미터 추가
-- Azure RegionInfo Credential 적용 및 ResourceHandler 호출 파라미터 일괄 변경
=> Azure RegionInfo ResourceGroup 파라미터 추가

cloud-control-manager/cloud-driver/interfaces/resources/VMHandler.go
VMStatus의 잘 못된 특수기호 수정 (**“** --> ")
Running  VMStatus = **“**Running**“** --> Running  VMStatus = "Running"
=> VMStatus의 잘 못된 특수기호 수정 (“ --> ")

api-runtime/rest-runtime/test/azure/vnic/create-test.sh, cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/azure/resources/CommonAzureFunc.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VNetworkHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VNicHandler.go
- Azure VNIc 생성 시 SecurityGroupId, PublicIPid 파라미터 포맷 변경 (Id->Name)
curl -X POST http://$RESTSERVER:1024/vnic?connection_name=azure-config01 -H 'Content-Type: application/json' -d '{
"Name": "CB-VNic",
"VNetName": "CB-Subnet",
**"SecurityGroupIds": ["CB-SecGroup"],
"PublicIPid": "CB-PublicIP"**
}' |json_pp
- Azure VM Status 정보 매핑
- Azure VMHandler 인터페이스 적용
- Azure 서브넷 삭제 시 VNetwork 자동 삭제 기능 추가
=> Azure VNic 생성 파라미터 포맷 변경 및 VM Status 관련 기능 적용

api-runtime/rest-runtime/test/azure/vm/start-test.sh, cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go, cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
- Azure VM 생성 시 VNIc 자동 생성 기능 추가
**CBVm-NIC 으로 {{VMName}}-NIC 규칙으로 자동 vNic 생성**
curl -X POST http://$RESTSERVER:1024/vm?connection_name=azure-config01 -H 'Content-Type: application/json' -d '{
"VMName": "CBVm",
"ImageId": "Canonical:UbuntuServer:18.04-LTS:18.04.201804262",
**"VirtualNetworkId": "CB-Subnet",
"PublicIPId": "CB-PublicIP",
"SecurityGroupIds": ["CB-SecGroup"],**
"VMSpecId": "Standard_B1ls",
"VMUserId": "cb-user",
"KeyPairName" : "CB-Keypair"
}' |json_pp
- Azure VM 삭제 시 OS Disk 함께 삭제 처리 기능 추가
=> Azure VM 생성/삭제 관련 기능 추가

cloud-control-manager/cloud-driver/drivers/aws/main/Test_VM.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go
VM Action에따른 사용되는 API와 리턴하는 정보
- Suspend :  **Stop** API 호출  / 리턴 : irs.VMStatus("Suspending")
- Resume : **Start** API 호출 / 리턴 : irs.VMStatus("Resuming")
- Reboot : Reboot API 호출 / 리턴 : irs.VMStatus("Resuming")
- Terminate : Terminate API 호출 -> 리턴 : irs.VMStatus("Terminating")
=> VM Action후 VM상태 정보 리턴 처리

cloud-control-manager/cloud-driver/drivers/azure/resources/VNetworkHandler.go
- Azure VNetwork 자동 삭제 처리 관련 파라미터 수정
=> Azure VNetwork 자동 삭제 처리 관련 파라미터 수정 (bugfix)

cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VNetworkHandler.go
Azure
- Azure VM 삭제 시 VNIc 자동 삭제 기능 추가
OpenStack
- OpenStack 서브넷 삭제 시 가상 네트워크 자동 삭제 기능 추가
=> Azure, OpenStack VMHandler 기능 추가

cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Vm.go, cloud-control-manager/cloud-driver/drivers/gcp/main/conf/Test_Config.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go
- KeyPairHandler 기능 추가
-- 저장&조회&삭제 시 KeyPairName을 소문자로 강제 치환함.
- VMHandler에 KeyPairName 조회 기능 추가
-- VM 생성시 Labels에 사용된 KeyPairName을 저장 후 조회시 전달 함.
=> - KeyPairHandler & VMHandler 기능 추가

cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Vm.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go
-KeypairHandler
-- vmUserId "cb-user" 고정 처리
-VMHandler
-- -Region return 처리
-- vmUserId "cb-user" 고정 처리
=> KeypairHandler&VMHandler modified

cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VNetworkHandler.go
- 일부 구간에 Default Value대신 사용자가 요청한 값이 사용되는 버그 수정
=> Vnet 생성 & 조회 버그 수정(일부 Default Value 강제 사용 누락 부분 반영)

cloud-control-manager/cloud-driver/drivers/gcp/resources/VNetworkHandler.go
* GCP network issue
-- vnet "cb-vnet" 고정 
-- region 에 따른 subnet 생성
=> change vNetworkHandler

cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Vm.go, cloud-control-manager/cloud-driver/drivers/gcp/main/conf/Test_Config.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VNetworkHandler.go
=> 요청된 리전에 VM할당 로직 추가

cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go
- #94 이슈 관련 SecurityGroup 조회 시 버그 fix
=> - SecurityGroup 조회 관련 버그 fix

cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/gcp/main/conf/Test_Config.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VNetworkHandler.go
=> 서브넷 카운트 버그 수정

api-runtime/rest-runtime/CBSpiderRuntime.go
=> CORS 처리 추가

cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go
- OpenStack VMHandler TerminateVM() 기능 bug fix
VM 삭제 시 VM ID 조회 부분 에러 수정
=> - OpenStack VMHandler TerminateVM() 기능 bug fix

api-runtime/rest-runtime/test/cloudit/image/get-test.sh, cloud-control-manager/cloud-driver/drivers/cloudit/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VNetworkHandler.go
- Cloudit VM Terminate 시 Not Found 예외 처리
- Cloudit ImageHandler GetImage() NameId 적용
- Cloudit Security, VNetwork NameID 조회 시 not found 예외 처리 추가
=> Cloudit NameId 관련 예외처리 기능 추가

cloud-control-manager/cloud-driver/drivers/cloudit/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VNetworkHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VNicHandler.go
- Cloudit VM, VNetwork, SecurityGroup 생성 시 중복 체크, 삭제 시 존재 여부 체크 예외처리 추가
- Cloudit VMHandler VM Status 조회 로직 수정
=> Cloudit ResourceHandler 예외 처리 및 VMHandler bug fix

cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VNetworkHandler.go
- OpenStack VM 생성 시 중복 체크, 삭제 시 존재여부 체크 추가
- OpenStack VNetwork 삭제 시 존재여부 체크 추가
=> OpenStack VM 생성, 삭제 로직 예외처리 추가

cloud-control-manager/cloud-driver/drivers/gcp/resources/VNetworkHandler.go
기존에 vNet 생성시 time sleep 으로 마냥 기다렸던 기능을
VNet 생성 후 체크 loop를 돌며 120초 이후에도 체크가 되지 않는다면 에러되게 처리 하였습니다.
=> add time loop at vNetworkHandler

api-runtime/rest-runtime/test/aws/keypair/create-test.sh, api-runtime/rest-runtime/test/aws/keypair/delete-test.sh, api-runtime/rest-runtime/test/aws/keypair/get-test.sh, api-runtime/rest-runtime/test/aws/publicip/create-test.sh, api-runtime/rest-runtime/test/aws/publicip/delete-test.sh, api-runtime/rest-runtime/test/aws/publicip/get-test.sh, api-runtime/rest-runtime/test/aws/security/create-test.sh, api-runtime/rest-runtime/test/aws/security/delete-test.sh, api-runtime/rest-runtime/test/aws/security/get-test.sh, api-runtime/rest-runtime/test/aws/vm/get-status-test.sh, api-runtime/rest-runtime/test/aws/vm/get-test.sh, api-runtime/rest-runtime/test/aws/vm/reboot-test.sh, api-runtime/rest-runtime/test/aws/vm/resume-test.sh, api-runtime/rest-runtime/test/aws/vm/start-test.sh, api-runtime/rest-runtime/test/aws/vm/suspend-test.sh, api-runtime/rest-runtime/test/aws/vm/terminate-test.sh, api-runtime/rest-runtime/test/aws/vnetwork/delete-test.sh, api-runtime/rest-runtime/test/aws/vnetwork/get-test.sh, api-runtime/rest-runtime/test/aws/vnic/create-test.sh
VNetwork - Name기반 수정및 테스트 완료
KeyPair - Name기반 수정및 테스트 완료
Security - Name기반 수정및 테스트 완료
PublicIp - Name기반 수정및 테스트 완료
VM - Name기반 수정및 테스트 완료
Image - Name기반 테스트 완료
**Vnic - ID 기반이라 핸들러 수정 필요**
=> Test스크립트 NameId 기반으로 변경 및 테스트 완료

cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go, cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/client/ace/specs/Request.go, cloud-control-manager/cloud-driver/drivers/cloudit/connect/Cloudit_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/cloudit/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/connect/OpenStack_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/openstack/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMSpecHandler.go
* Azure, OpenStack, Cloudit VM Spec 리소스 핸들러 추가
* VMSpecHandler 추가 함수
- ListVMSpec()
- GetVMSpec()
- ListOrgVMSpec()
- GetOrgVMSpec()
=> Azure, OpenStack, Cloudit VM Spec 리소스 핸들러 추가

cloud-control-manager/cloud-driver/drivers/gcp/GCPDriver-lib.go, cloud-control-manager/cloud-driver/drivers/gcp/connect/GCP_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/gcp/main/conf/Test_Config.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/interfaces/CloudDriver.go, cloud-control-manager/cloud-driver/interfaces/connect/CloudConnect.go, cloud-control-manager/cloud-driver/interfaces/resources/VMSpecHandler.go
• GCP VMSpecHandler 추가
- ListVMSpec()
- GetVMSpec()
- ListOrgVMSpec()
- GetOrgVMSpec()
=> GCP VMSpecHandler 추가

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Create.go, cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/main/Test_VM.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMSpecHandler.go
ListOrgVMSpec의 출력 결과에서 첫 번째 데이터만 출력하는 버그 수정
=> VMSpecHandler - ListOrgVMSpec 버그 수정

cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMSpecHandler.go
* Azure, OpenStack, Cloudit VMSpecHandler 수정
- Azure, OpenStack, Cloudit Region 정보 적용
참고: https://github.com/cloud-barista/cb-spider/issues/121#issuecomment-603202647
=> Azure, OpenStack, Cloudit VMSpecHandler 수정

cloud-control-manager/cloud-driver/drivers/azure/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMSpecHandler.go
* slack에서 전달받은 요청사항 기준으로 ListOrgVMSpec 리턴값 json 구조 변경
참고 URL: https://cloud-barista.slack.com/archives/CLFCLNFTJ/p1585211714021800
=> ListOrgVMSpec json 구조 변경

cloud-info-manager/connection-config-info-manager/ConnectionConfigInfoManager.go, cloud-info-manager/credential-info-manager/CredentialInfoManager.go, cloud-info-manager/driver-info-manager/DriverInfoManager.go, cloud-info-manager/region-info-manager/RegionInfoManager.go
Ref:
/driver
```JSON
{
"DriverLibFileName": "aws-driver-v1.0.so",
"DriverName": "aws-driver01",
"ProviderName": "AWS"
}
```
---
/credential
```json
{
"CredentialName": "aws-credential01",
"KeyValueInfoList": [
{
"Key": "ClientId",
"Value": ""
},
{
"Key": "ClientSecret",
"Value": ""
}
],
"ProviderName": "AWS"
}
```
---
/region
```json
{
"KeyValueInfoList": [
{
"Key": "Region",
"Value": "us-east-1"
}
],
"ProviderName": "AWS",
"RegionName": "aws-us-east-1"
}
```
---
/connectionconfig
```json
{
"ConfigName": "aws-us-east-1-config",
"CredentialName": "aws-credential01",
"DriverName": "aws-driver01",
"ProviderName": "AWS",
"RegionName": "aws-us-east-1"
}
```
=> Modify error messages

cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/ImageHandler.go
=> Image 정보에 GuestOS 정보 추가

cloud-control-manager/cloud-driver/drivers/gcp/resources/VMSpecHandler.go
=> modified VMSpecHandler

cloud-control-manager/cloud-driver/drivers/aws/AwsDriver-lib.go, cloud-control-manager/cloud-driver/drivers/aws/connect/AwsCloudConnection.go, cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/resources/CommonAwsFunc.go, cloud-control-manager/cloud-driver/drivers/aws/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VNetworkHandler.go.del, cloud-control-manager/cloud-driver/drivers/aws/resources/VNicHandler.go.del, cloud-control-manager/cloud-driver/drivers/aws/resources/VPCHandler.go, cloud-control-manager/cloud-driver/interfaces/CloudDriver.go, cloud-control-manager/cloud-driver/interfaces/connect/CloudConnect.go
=> 공통 I/F에 VPCHandler 반영

cloud-control-manager/cloud-driver/drivers/azure/AzureDriver-lib.go, cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/azure/main/Test_VM.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
<br/>
* IId 개정 인터페이스 적용
1. VMHandler (적용 완료)
<br/>
* VMHandler nested flow 관련 추가 로직 적용
1. VM 삭제 시 PublicIP, VNic, OS Disk 삭제 로직 추가
<br/>
=> [Azure Driver] IId 개정 인터페이스 적용 및 VMHandler 추가

cloud-control-manager/cloud-driver/drivers/openstack/main/Test_VM.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
<br/>
* IId 개정 인터페이스 적용
1. VMHandler
=> [OpenStack Driver] IId 개정 인터페이스 적용 (VMHandler)

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go
=> VM 목록 조회 버그 수정

cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go
Private Subnet도 강제로 Public Ip가 할당하도록 EC2의 네트워크 스펙 정의
=> Private Subnet의 Ec2에 Public Ip 할당로직 추가

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go
VM 정보에 SubnetIID및 StartTime필드 반영
=> VM 정보 조회 버그 Fix

cloud-control-manager/cloud-driver/drivers/gcp/GCPDriver-lib.go, cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Vm.go, cloud-control-manager/cloud-driver/drivers/gcp/main/conf/Test_Config.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go
VMHandler 
- 테스트용 Test_Vm 수정 및 테스트 완료
- VMHandler IID 반영 완료
=> [GCP]VMHandler IID 반영 및 테스트 완료

cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMHandler.go
- VM 상태 정보 현행화
- VM 생성 후 정보 전달
- [이슈] **VM상태 종회에서 Reboot 과 Resume시 발생하는 Starting 상태의 처리 방안 필요**
- Pending -> Creating
- Running -> Running
- Stopping -> Suspending
- Stopped -> Suspended
- **Starting --> Resuming? or Rebooting? or 다른 상태 값?을 결정해야 함.**
=> 알리 클라우드 버그 수정

cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
=> [Azure Driver] VMHandler mappingServerInfo bug fix

cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/KeyPairHandler.go
- 키 페어 폴더 없을 경우 자동 생성 로직 추가
- 키 페어 조회 및 삭제시 Not Found 예외 추가
- 키 페어 목록 조회 시 키 페어 폴더 없을 경우 KeyPairInfo{}
=> GCP 키페어 예외 처리 추가

cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/main/old/Test_Resources.go.old, cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/SecurityHandler.go
GCP 보안그룹의 요청 Port에 -1(All or Nothing) 기능 적용
- FromPort & ToPort 둘 다 -1 또는 둘 중 하나라도 -1 이면서 다른 포트가 공백이면 All로 처리
- FromPort & ToPort 둘 중 하나에 -1이 사용되면 -1이 사용되지 않은 Port의 값을 이용
- FromPort & ToPort 모두 공백이면 All로 처리
=> 보안그룹 룰 변경 및 확인

cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/SecurityHandler.go
#197 이슈 적용
[Azure]
* SecurityHandler Create/Get 로직 수정
[OpenStack]
* SecurityHandler Get 로직 수정
=> [Azure, OpenStack] SecurityHandler ICMP rule 인터페이스 적용

cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go
VM 정보
- Create와 Get에서의 NameId & SystemId 값 불 일치 통일
- ImageIId 정보 수정
- StartTime 정보 추가
- VMSpecName 정보 추가
VM 상태 정보 목록
- NameId & SystemId 값 불 일치 통일
=> GCP VM핸들러 리턴 정보 보완

cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/KeyPairHandler.go
[OpenStack]
- KeyPairHandler mapping 정보 수정
[Azure]
- SecurityHandler Create() bug fix
=> [Azure, OpenStack] KeyPairHandler, SecurityHandler 수정

cloud-control-manager/cloud-driver/drivers/openstack/OpenStackDriver-lib.go, cloud-control-manager/cloud-driver/drivers/openstack/build_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/openstack/resources/CommonOpenStackFunc.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
#211
기존 소스코드가 아니라 이전 버전으로 롤백되어 소스코드가 커밋된 것 같네요.
해당 이슈 관련하여 기존 소스코드 적용 및 lib 파일 추가를 하였습니다.
=> OpenStack 기존 소스코드 적용 및 OpenStackDriver-lib 파일 추가

cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
https://github.com/cloud-barista/cb-spider/issues/211#issuecomment-630529608
해당 이슈 관련 VMHandler 파라미터 정보 수정
=> OpenStack VMHandler 생성 파라미터 변경

cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
OpenStack Driver
* Public IP 정보 출력
Cloudit Driver
* VMSpec 조회 시 단위 수정 (GB to MB)
=> Openstack, Cloudit 수정 사항 적용

cloud-control-manager/cloud-driver/drivers/cloudit/main/Test_VM.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/CommonClouditFunc.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/SecurityHandler.go
VPCHandler
* DeleteVPC() bug fix
VMHandler
* StartVM() bug fix
=> Cloudit VMHandler, VPCHandler bug fix

cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/gcp/main/conf/Test_Config.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VPCHandler.go
- VPC 생성 및 삭제시 예외 처리 보완
- 보안 그룹의 SecurityReqInfo.Direction 정보가 없을 경우 INGRESS 규칙을 추가하도록 수정
=> GCP 드라이버 VPC & 보안그룹 로직 보완

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go
- VM 목록 및 Start시 Blank Name Tag 예외 처리
- 이슈 #240 처리
=> Name이 없는 경우 Name Tag 예외 추가 / #240 처리

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
=> 목록 수 출력하도록 Test Code 수정

api-runtime/apiserver.go, api-runtime/common-runtime/CCMCommon.go, api-runtime/grpc-runtime/CBSpiderGRPCRuntime.go, api-runtime/rest-runtime/CBSpiderRuntime.go, api-runtime/rest-runtime/CCMRest.go, api-runtime/rest-runtime/CIMRest.go, api-runtime/rest-runtime/SSHRUNRest.go, go.mod, setup.env
REST 에서 core logic 분리
CBGRPC_ROOT 환경변수 추가
google.golang.org/grpc 모듈은 v1.26.0 으로 replace 함
API 서버는 dual port 형식으로 통합( go run apiserver.go 로 서버 실행 )
=> seperate REST and core logic

api-runtime/grpc-runtime/common/cbmessage.go, interface/api/ccm.go, interface/api/cim.go, interface/api/request/connection.go, interface/api/request/credential.go, interface/api/request/driver.go, interface/api/request/image.go, interface/api/request/keypair.go, interface/api/request/os.go, interface/api/request/region.go, interface/api/request/request.go, interface/api/request/security.go, interface/api/request/ssh.go, interface/api/request/vm.go, interface/api/request/vmspec.go, interface/api/request/vpc.go, interface/api/test/test_api.go, interface/grpc_conf.yaml
Spider CIM API 포함 : NewCloudInfoManager() 생성함수 이용
Spider CCM API 포함 : NewCloudInfoResourceHandler() 생성함수 이용
=> add grpc client API

utils/docker/data/grafana-grpc/data/dashboards/cb-grpc-dashboard.json, utils/docker/data/grafana-grpc/provisioning/dashboards/all.yml, utils/docker/data/grafana-grpc/provisioning/datasources/all.yml, utils/docker/data/prometheus/prometheus.yaml, utils/docker/env.grafana, utils/docker/grpc-backend-compose.yaml, utils/docker/initdata.sh
도커를 이용하여 grpc backend server 구성
- prometheus 포함
- grafana 포함
- jaegertracing 포함
=> Add grpc backend server using docker

cloud-control-manager/cloud-driver/drivers/azure/resources/KeyPairHandler.go
#237 이슈 관련 로직 적용
- .ssh-azure 폴더 자동 생성 로직 적용
=> [Azure Driver] .ssh-azure 폴더 자동 생성 로직 적용

api-runtime/grpc-runtime/cert-gen/certificate.conf, api-runtime/grpc-runtime/cert-gen/gen_certs.sh, interface/api/ccm.go, interface/api/cim.go, interface/api/test/test_api.go, interface/cli/spider/cmd/gclient.go
- struct 타입을 지원하는 API 생성 함수 추가
- 인증서 생성 스크립트 추가
- spider cli 에서 cim 과 ccm API 를 동시에 Open 하는 것을 명령어에 따라 해당 API 하나만 Open 하게 수정
=> Add api create function by struct parameter and cert generation script

interface/api/ccm.go, interface/cli/spider/cmd/gclient.go, interface/cli/spider/cmd/keypair.go, interface/cli/spider/cmd/root.go, interface/cli/spider/cmd/security.go, interface/cli/spider/cmd/vm.go, interface/cli/spider/cmd/vpc.go, interface/test/spider/eachtest/keypair-delete-test.sh, interface/test/spider/eachtest/securitygroup-delete-test.sh, interface/test/spider/eachtest/vm-delete-test.sh, interface/test/spider/eachtest/vpc-delete-test.sh, interface/test/spider/fulltest/clear-tools/all_delete.sh, interface/test/spider/fulltest/clear-tools/except_vm_delete.sh, interface/test/spider/fulltest/full_test.sh
- DeleteSecurityByParam() API 에 force flag 추가
- DeleteKeyByParam() API 에 force flag 추가
- DeleteVPCByParam() API 에 force flag 추가
- TerminateVMByParam() API 에 force flag 추가
=> Add delete force flag to ccm api

cloud-control-manager/cloud-driver/drivers/azure/resources/ImageHandler.go
=> Azure 이미지 조회 기능 추가

cloud-control-manager/cloud-driver/drivers/azure/resources/ImageHandler.go
=> Azure 이미지 목록 조회 예외처리 추가

cloud-control-manager/cloud-driver/drivers/azure/resources/VPCHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VPCHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VPCHandler.go, go.mod, go.sum
- Azure, Cloudit, Openstack 기능 추가
- 기존의 vpc에 test 완료
- 인터페이스화 완료
=> [feature] Add and delete subnets in an existing VPC

cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/VPCHandler.go, cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VPCHandler.go
AWS / AlibabaCloud Subnet 추가/삭제 기능 추가
=> 이슈 #277 VPC 핸들러에 서브넷 추가/삭제 기능 추가

build_grpc_idl.sh
=> Fix include path

interface/api/test/test_api.go
=> Update test api

README.md
Modify `README.md`
Update `setup.env` directions
=> Modify README.md - add setup.env config related directions

cloud-control-manager/cloud-driver/drivers/aws/resources/VPCHandler.go
=> AWS VPCHandler에 HISCALL 적용

.github/workflows/docker-publish.yml
- For every commit in PR
- Do Docker build test
- For every merged PR
- Do Docker build
- Push Docker image to GitHub Container Registry (https://github.com/orgs/cloud-barista/packages)
=> Add Docker build test & push logic

cloud-control-manager/cloud-driver/drivers/azure/resources/ImageHandler.go
* Azure 이미지 목록 조회 로직 변경 (goroutine 기반 동작)
=> Azure 이미지 목록 조회 로직 변경 (goroutine 기반 동작)

cloud-control-manager/cloud-driver/drivers/alibaba/resources/VPCHandler.go, cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VPCHandler.go, setup.env
- AWS HisCall 적용
- GCP HisCall Log 추가
- Alibaba VPCHandler에 HisCall 적용
=> AWS / GCP HisCall 추가

cloud-control-manager/cloud-driver/drivers/azure-plugin/AzureDriver-lib.go, cloud-control-manager/cloud-driver/drivers/cloudit-plugin/ClouditDriver-lib.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/openstack-plugin/OpenStackDriver-lib.go
* 드라이버 Plugin 라이브러리 에스프레소 버전 기준 최신화
=> [CB-Spider] 드라이버 Plugin 라이브러리 에스프레소 버전 기준 최신화

api-runtime/common-runtime/CCMCommon.go, api-runtime/rest-runtime/CBSpiderRuntime.go, api-runtime/rest-runtime/CCMRest.go, cloud-control-manager/cloud-driver/drivers/mock/resources/VPCHandler.go
- VPC Subnet 를 위한 Common 함수 구현
- VPC Subnet 를 를 위한 Rest API 추가
- [Fix] Mock driver 의 AddSubnet() 함수에서 Subnet SystemId 설정
=> Add rest api for vpc subnet

api-runtime/rest-runtime/admin-web/AdminWeb-CCM.go
- AdminWeb Tool 에서 Subnet 을 추가하고 삭제할 수 있도록 기능 추가
=> Add adminweb for vpc subnet

cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/VPCHandler.go, cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VPCHandler.go
Alibaba Cloud 서브넷 추가시 VPC 목록에 추가된 서브넷의 NameId 정보 추가 - #330 이슈 Fix
=> Alibaba Cloud #330 이슈 Fix #331

api-runtime/rest-runtime/test/connect-config/8.ncp-conn-config.sh, api-runtime/rest-runtime/test/each-test/8.ncp-startvm-korea1.sh, api-runtime/rest-runtime/test/each-test/8.ncp-terminatevm.sh, api-runtime/rest-runtime/test/each-test/ncp-startvm-test.sh, api-runtime/rest-runtime/test/each-test/ncp-terminatevm-test.sh, build_all_driver_lib.sh, cloud-control-manager/CloudDriverHandler.go, cloud-control-manager/cloud-driver/call-log/gen4test/gen_calllog.go
- Update NCP, NCP VPC driver related files
=> Update NCP, NCP VPC driver related files

Dockerfile
- Fixes https://github.com/cloud-barista/cb-spider/runs/2285414727?check_suite_focus=true
```
buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: target stage prod could not be found
```
=> Fix error on auto build

cloud-control-manager/cloud-driver/drivers/openstack/cloud-config, cloud-control-manager/cloud-driver/drivers/openstack/connect/OpenStack_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
* OpenStack 드라이버 cloud-config 스크립트 파일 추가
* OpenStack 드라이버 VM 생성 시 UserData 옵션 추가
=> [SSH-User][OpenStack] OpenStack 드라이버 ssh user 설정 기능 추가

cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
=> [Azure Driver] CallLog elapsed time 개선 적용

cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go
- Cloudit 드라이버 StartVM main flow 개선
=> [Cloudit Driver] StartVM main flow 개선

cloud-control-manager/cloud-driver/drivers/openstack-plugin/OpenStackDriver-lib.go, go.mod, go.sum
=>  [OpenStack Driver] OpenStackDriver-lib 파일 최신화

cloud-control-manager/cloud-driver/drivers/azure/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/KeyPairHandler.go
- keyHandler mkdir 버그 수정 (mkdir -> mkdirall)
=> [AzureDriver][ClouditDriver] keyHandler mkdir 버그 수정

cloud-control-manager/cloud-driver/drivers/tencent/resources/SecurityHandler.go
Tencent - SecurityHandler CallLog 수정
=> Tencent - SecurityHandler CallLog 수정

cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/SecurityHandler.go
=> [Azure][OpenStack][Cloudit] SecurityHandler CIDR 적용

cloud-control-manager/cloud-driver/drivers/tencent/TencentDriver.go, cloud-control-manager/cloud-driver/drivers/tencent/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/VMSpecHandler.go
Tencent Driver - VMSpec 추가
- Connection 정보의 Zone 체크 로직 추가
- VmSpec 검색 조건은 Region이 아닌 Zone단위임.
- KeyPair 생성은 알파벳, 숫자, 밑줄(_)만 지원
- ImageHandler & SecurityHandler List() 메소의 페이징 처리 로직 추가해야 함.
현재는 리턴되는 값이 많지 않기 때문에 Limit 값을 Max 값인 100으로 설정해놨음.
=> Tencent Driver - VMSpec 추가

interface/cli/cbadm/proc/connectinfos.go
- conn config 가 존재하지 않을 경우 에러 발생하는 버그 수정
=> Fix list conn config

api-runtime/grpc-runtime/CBSpiderGRPCRuntime.go
- grpc_conf.yaml 에서 interceptors 항목이 존재하지 않을 경우 버그 발생하여 수정
=> Fix grpc server reflection server

api-runtime/apiserver.go, api-runtime/common-runtime/common.go, api-runtime/grpc-runtime/CBSpiderGRPCRuntime.go, api-runtime/rest-runtime/CBSpiderRuntime.go, bin/server-info.sh, go.mod, go.sum
- apiserver.go 에 cobra 통합 
=> ./cb-spider : 기존 서버 실행
=> ./cb-spider info : 서버 실행 정보 표시
- 전역변수로 GoServicePort 추가 : Go API 서비스 포트
- ServicePort 초기화를 init() 함수에서 수행하게 함
- rest api 추가 : /endpointinfo
=> Support server's endpoints info in terminal env

cloud-control-manager/cloud-driver/drivers/openstack/resources/CommonOpenStackFunc.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
- VMHandler StartVM() 로직 버그 수정
=> [OpenStack Driver] VMHandler StartVM() 로직 버그 수정

api-runtime/rest-runtime/test/connect-config/10.tencent-conn-config.sh, build_all_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/tencent-plugin/TencentDriver-lib.go, cloud-control-manager/cloud-driver/drivers/tencent-plugin/build_driver_lib.sh
=> tencent 빌드 스크립트 추가

api-runtime/rest-runtime/test/connect-config/10.tencent-conn-config.sh, api-runtime/rest-runtime/test/each-test/9.tencent-1.vpc.sh, cloud-control-manager/CloudDriverHandler_static.go, cloud-control-manager/cloud-driver/drivers/tencent/main/Test_Resources.go
- **tencent-conn-config.sh**의 Provider Name의 "tencent"를 대문자("**TENCENT**")로 변경
- **CloudDriverHandler**에 **TENCENT** 기능 추가및 VPC 생성및 조회만 테스트해 봄.
=> Tencent conn-config 수정및 CloudDriverHandler에 TENCENT 로직 반영

cloud-control-manager/cloud-driver/drivers/cloudit/client/ace/nic/Request.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go
- SG Rule Default 설정 기능 추가
- VM 생성 후 VNIC의 SG 설정 기능 버그 해결
* VM 생성 후 VNIC SG Attach 로직 추가
=> [Cloudit] Default Security Group Rule 추가 및 VM 생성 버그 해결

api-runtime/rest-runtime/test/connect-config/10.tencent-conn-config.sh, cloud-control-manager/cloud-driver/drivers/tencent/main/Sample/conf/configTencent.yaml, cloud-control-manager/cloud-driver/drivers/tencent/main/conf/Test_Config.go
- Tencent cloud driver test config file path를 기존의 환경변수, 기존의 디렉토리명으로 변경
(Tencent driver 초기 사용자의 혼돈 방지를 위함.)
=> Update Tencent cloud test config file path

cloud-control-manager/cloud-driver/drivers/alibaba/AlibabaDriver.go
기본 설정 값 확인이 안되어서 우선 타임아웃을 15초에 2회 자동 재시도로 수정.
향후 튜닝된 값이 확정되면 해당 값으로 변경하거나 Key/Value를 이용해서 외부에서 설정하도록 수정하면 좋을 것 같습니다.
=> 알리클라우드 - 타임아웃을 15초에 2회 자동 재시도로 수정

cloud-control-manager/cloud-driver/drivers/tencent/main/Test_Resources.go
O Tencent driver test code 보완
- VM Spec 조회시 conf 파일에서 받아온 Zone 정보 입력(Region 정보 아님)
- 혼동을 피하기 위해 conf 파일에서 받아온 Zone 정보 사용
- Zone 정보 변경하며 테스트시 계속 확인 위해 해당 Zone 정보 출력
=>  Update Tencent driver test code

cloud-control-manager/cloud-driver/drivers/tencent/resources/VMSpecHandler.go, conf/cloudos.yaml
웹도구에서 TENCENT 드라이버를 사용할 수 있도록 conf/cloudos.yaml 에 TENCENT 추가
=> 클라우드 OS목록에  Tencent 추가

cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
[OpenStack 드라이버]
- VM 프로비저닝 및 floating ip 연결 관련 예외처리 기능 추가
=> [OpenStack] VM 프로비저닝 및 floating ip 연결 관련 예외처리 기능 추가

interface/cli/spider/cmd/gclient.go, interface/cli/spider/cmd/vm.go
- spctl list image 명령어 에 대한 버그 수정
- spctl vm  terminatecsp 명렁어에 대한 버그 수정
=> Fix list image and vm terminatecsp for spctl

.gitignore, Makefile, interface/build_cli.sh, interface/cli/spider/cmd/root.go, interface/cli/spider/cmd/version.go, interface/cli/spider/cmd/vm.go
- spctl 에 version 명령어 추가 #431 
- spctl 에서 vm control 명령어 비활성함 #432
=> Add version command and vm control disable

cloud-control-manager/cloud-driver/drivers/azure/resources/ImageHandler.go
[Azure] Image 목록 조회 로직 변경
- ListImage() : 전체 이미지 version 목록이 조회되도록 로직 수정
=> [Azure] Image 목록 조회 로직 변경

api-runtime/rest-runtime/CBSpiderRuntime.go, api-runtime/rest-runtime/CCMRest.go, api-runtime/rest-runtime/CIMRest.go, api-runtime/rest-runtime/SSHRUNRest.go
- Unit 테스트를 위해 Echo 핸들러 함수를 private 함수에서 public 함수로 변경함
=> Update private to public for echo handler func

cloud-control-manager/cloud-driver/drivers/azure/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/KeyPairHandler.go
- replace keypair generation func to common packaged keypair generation func
- remove the 'CallLog for Hiscall' code and add cblogger
=> modify csp(Azure, Cloudit) keyPair generating code

cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/KeyPairHandler.go
- Call Log 제거
- KeyPair 생성을 Common 함수 사용으로 변경
=> GCP 키페어 생성 오픈소스 라이센스 이슈 처리 반영

cloud-control-manager/cloud-driver/drivers/cloudit/client/RestClient.go
- Cloudit 드라이버 RestClient 코드 개선
=> [Cloudit] RestClient 코드 개선

cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
- Check VM Status with two values names 'powerState' & 'provisioningState'
=> Bugfix Get VM Status(Azure) Func Code

setup.env
#458 이슈에서 언급한 바와 같이 CBSPIDER_ROOT 변수의 값을 동적으로 바꿀 수 있도록 수정하였습니다.
=> change 'CBSPIDER_ROOT' value dynamically(#458)

api-runtime/rest-runtime/admin-web/AdminWeb-CCM.go
- Fix Incorrect values setting when adding a new subnet in AdminWeb (#469)
=> Fix new subnet in AdminWeb

api-runtime/rest-runtime/test/connect-config/10.tencent-conn-config.sh, api-runtime/rest-runtime/test/full-test/10.tencent-test.sh, api-runtime/rest-runtime/test/full-test/tencent-full_test.sh, conf/testConfigTencent.yaml
- Add Tencent cloud driver Full test scripts (using CB-Spider REST API)  
- Update tencent-conn-config.sh (Update Available Zones) 
- Update testConfigTencent.yaml for driver local test (Update Available Zones)
=> Add and Update Tencent cloud Test scripts

cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go, cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/azure/resources/CommonAzureFunc.go, cloud-control-manager/cloud-driver/drivers/azure/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
Local 키페어 관리 로직 제거  (이슈 #480)
- Azure SSH-key 리소스 적용 로직 추가  및 local 키페어 로직 삭제
- cloud-init 스크립트 미적용 CSP
=> [Azure] - Local 키페어 관리 로직 제거 (이슈 #480)

api-runtime/rest-runtime/test/connect-config/12.ibmvpc-conn-config.sh, api-runtime/rest-runtime/test/full-test/12.ibmvpc-test.sh, api-runtime/rest-runtime/test/full-test/ibmvpc-full_test.sh, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc-plugin/build_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/conf/config.yaml.sample
- Add IBM VPC driver connection config file (with Regions and Zones info)
- Add driver Full test scripts (using CB-Spider REST API)
- Rename config.yaml to config.yaml.sample
=> Add IBM VPC conn config and full test scripts

cloud-control-manager/cloud-driver/drivers/azure/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/connect/OpenStack_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMSpecHandler.go
[vmSpec] region 파라미터 변경 (이슈 #417)
- Azure, openstack, cloudit 적용
=>  [vmSpec] region 파라미터 변경 (이슈 #417)

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/conf/config.yaml.sample
=> [Ibm-VPC] 테스트 코드의 대한 SystemId 입력

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/conf/config.yaml.sample, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/ImageHandler.go
- ImageResource NameId와 SystemId 일치화
=> [Ibm] ImageResource NameId와 SystemId 일치화

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VmSpecHandler.go
- 메모리 사이즈 단위 변경 GB=>MB (이슈 #513)
=> [vmSpec] 메모리 사이즈 단위 변경 GB=>MB (이슈 #513)

api-runtime/rest-runtime/test/full-test/12.ibmvpc-test.sh, api-runtime/rest-runtime/test/full-test/ibmvpc-full_test.sh
CB-Spider API를 이용한 IBM VPC driver full test 관련하여, 지난 금요일 최종 update된 test script 파일을 PR 올립니다. 
- Add values of Conn. config and VMImage SystemID parameter of each zone
- Update full test script using CB-Spider API
=> Update IBM VPC driver full test scripts

cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/tencent/main/Test_Resources.go
AWS / Alibaba / GCP / Tencent의 Test 코드에서 VMSpec의 리전 아규먼트 제거
=> 드라이버 개선안 I(이슈 #417) 처리

cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/cloudit/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/openstack/main/Test_Resources.go
- TestResource vmspec 파라미터 변경
Openstack / Azure / CloudIt / Ibm - VPC 적용
=> [vmspec] TestResource vmspec 파라미터 변경

api-runtime/rest-runtime/test/connect-config/11.ktcloud-conn-config.sh, cloud-driver-libs/cloudos_meta.yaml
- Add KTCloud connection config input script
: Includes ID of all available zones / connection config name related to each zone
- Update CloudOS_meta misspelling
: KT -> KTCLOUD
=> Add KTCloud conn. config, Update CloudOS_Meta

cloud-control-manager/cloud-driver/drivers/tencent/resources/SecurityHandler.go
=> Tencent - 보안 포트에서 All을 "-"에서 "-1"로 버그 수정 (이슈#487)

cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go, cloud-driver-libs/cloudos_meta.yaml
- Azure RootDisk Size (현재 미제공)
- vm 생성 시 지정하는 방식이 아닌 생성 후 디스크의 변경을 이용한 기능 제공
- disksize 변경 시 발생하는 에러 사항 고려 후 제공
- Azure RootDisk Type(제공)
- DiskType : Premium_LRS / Standard_LRS / StandardSSD_LRS / UltraSSD_LRS 중  UltraSSD_LRS 를 제외한 3가지 Type 제공
- UltraSSD_LRS 제외 이유 : 제공 지역 및 iops에 대한 제한
- Type의 가독성을 위하여  아래 타입의 문자열로 제공
- Premium_LRS = PremiumSSD
- StandardSSD_LRS  = StandardSSD
-  Standard_LRS = StandardHHD
=> [Azure] RootDisk Type 타입지정(이슈 #348)

cloud-driver-libs/.cloud-init-ktcloud/cloud-init, cloud-driver-libs/.cloud-init-ncp/cloud-init, utils/driver-build-docker/2.build/ktcloud-build.sh
- Add NCP driver Cloud-init script
- Add KT Cloud driver Cloud-init script
=> Add NCP, KT Cloud driver Cloud-init script

utils/driver-build-docker/2.build/ktcloud-build.sh, utils/driver-build-docker/2.build/ncp-build.sh
- Update KT Cloud driver build script
: Improve  readability
- Update NCP driver build script
: Remove unnecessary packages anymore
=> Update NCP, KT Cloud driver build scripts

utils/driver-build-docker/2.build/ktcloud-build.sh, utils/driver-build-docker/2.build/ncp-build.sh
- Update NCP driver build script
: Remove unnecessary code
- Update KTCloud driver build script
: Apply environment variables of git to go get
=> Update NCP, KTCloud driver build scripts

cloud-control-manager/cloud-driver/drivers/cloudit/ClouditDriver.go, cloud-control-manager/cloud-driver/drivers/cloudit/main/Test_Resources.go
- Update Cloudit Driver API version (v4.0 to v5.0)
=> [Cloudit] Update Cloudit Driver API version (v4.0 to v5.0)

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMHandler.go
- Zone의 url에서 Region의 정보 추출하여 누락되었던 Region 제공
=> [VM] Region 정보 추가

cloud-control-manager/CloudDriverHandler_common.go
Add NHNCLOUD info to getRegionNameByRegionInfo() on CloudDriverHandler_common.go
=> Add NHNCLOUD to getRegionNameByRegionInfo()

cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/CommonAlibabaFunc.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/KeyPairHandler.go
Alibaba Cloud KeyPairHandler에 페이징 로직 추가 - 이슈 #566
1 페이지당 50건씩 조회 함.
=> Alibaba 클라우드 키페어 페이징 적용 - 이슈 #566

.gitignore, cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/azure/main/conf/config.yaml.sample, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
[Azure] RootDisk Size 변경 및 Vmhandler 개선 (이슈 #536)
- RootDisk Size 변경 기능 추가 및 Vmhandler 개선
- RootDisk Size의 실패 연관 리소스 반납 로직 추가
- Error 케이스 분할 및 safe 로직 추가
- Test_Resources 통일 
- VM 과 타 핸들러의 Test_Resources 파일 통합
- Test_Resources를 위한 config.yaml 샘플  config.yaml.sample
=> [Azure] RootDisk Size 변경 및 vmhandler 개선 (이슈 #536)

api-runtime/rest-runtime/test/full-test/8.ncp-test.sh, api-runtime/rest-runtime/test/full-test/ncp-full_test.sh, utils/driver-build-docker/2.build/ncp-build.sh
- Add NCP Full test scripts to test NCP connection driver through CB-Spider REST API
- Update NCP driver build script in container
: Update ncloud-sdk-go-v2 version
=> Add NCP Full test scripts, Update ncp-build script in container

api-runtime/rest-runtime/test/connect-config/13.nhncloud-conn-config.sh, api-runtime/rest-runtime/test/full-test/13.nhncloud-test.sh, api-runtime/rest-runtime/test/full-test/nhncloud-full_test.sh
Add NHN Cloud connection config script and full test scripts
- Add 13.nhncloud-conn-config.sh to apply connection config to CB-Spider server
- Add 13.nhncloud-test.sh and nhncloud-full_test.sh for full testing of NHN Cloud connection driver through CB-Spider API
=> Add NHN connection config and full test scripts

utils/driver-build-docker/2.build/nhncloud-build.sh
- Add NHN Cloud driver building script for CB-Spider driver dynamic (plug-in) mod
=> Add NHN build script for dynamic (plug-in) mod

api-runtime/rest-runtime/test/full-test/nhncloud-full_test.sh, cloud-driver-libs/.cloud-init-nhncloud/cloud-init
- Add NHN Cloud Cloud-init script
- Update NHN Cloud Full test script for CB-Spider API call
=> Add NHN Cloud Cloud-init script, Update NHN Cloud Full test script

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/conf/config.yaml.sample, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/SecurityHandler.go
- AddRule, RemoveRule 기능 추가
- 시험 항목에 대한 테스트 완료.
- portRange CB <-> Ibm-vpc 포매팅 수정
- portRange의 all CB => -1 or 1-65535 => Ibm-vpc 1-65535
- TestResource 수정
=> [Ibm-vpc] AddRule, RemoveRule 기능 추가 및 핸들러 기능 개선

cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go
https://github.com/cloud-barista/cb-spider/issues/482#issuecomment-1111856529
- ADDRule 시 CIDR 값이 전체 업데이트 되는 현상 개선
테스트 결과는 이슈 482(#482)에 첨부하도록 하겠습니다.
=> [Azure]SecurityGroup-Rule-CIDR Bugfix(#482)

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/SecurityHandler.go
[Ibm-vpc] SecurityGroup - Rule 관련 포맷 안전 처리( https://github.com/cloud-barista/cb-spider/issues/482#issuecomment-1115065980)
- IPProtocol 대문자 넘어왔을 경우 에러 문제
- 중간 Convert로 소문자로 매핑 및
- IPProtocol All일 경우 Ibm에서 Cidr 값을 nil로 반환 
- nil => 0.0.0.0/0으로 매핑
=> [Ibm-vpc] SecurityGroup - Rule 관련 포맷 안전 처리

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VPCHandler.go
- VPC 생성시 deafult securityGroup 변경 로직 추가
- IBM에서 타 CSP 동일한 기능 제공을 위해 VPC가 생성될 경우, VPC에 적용되는 default securityGroup을 수정
- 해당 default securityGroup는 vm 생성시, VM의 Network Interface에 자동적으로 추가
- 해당 default securityGroup은 아래의 Rule을 포함.(편의상 CB-Spider의 RuleInfo로 표현)
```
- FromPort: "-1"
ToPort: "-1"
IPProtocol: "all"
CIDR: "0.0.0.0/0"
Direction: "outbound"
- FromPort: "22"
ToPort: "22"
IPProtocol: "TCP"
CIDR: "0.0.0.0/0"
Direction: "inbound"
- FromPort: "-1"
ToPort: "-1"
IPProtocol: "ICMP"
CIDR: "0.0.0.0/0"
Direction: "inbound"
- FromPort: "-1"
ToPort: "-1"
IPProtocol: "all"
CIDR: "Security group"
Direction: "inbound"
```
- 위 룰중 앞 3개를 제거하는 로직 추가(마지막 Rule은 IBM 자체의 필요 로직일 수도 있기에 보류)
- 결과적으로 VPC에 적용되는 default securityGroup는 어떠한 작용도 하지않는 빈 SecurityGroup으로 변경
- securityGroup 생성시 default Rule 추가
- 타 CSP …
=> [Ibm-VPC] OutBound 및 공통이슈 개발 방안 적용

cloud-control-manager/cloud-driver/drivers/gcp/resources/SecurityHandler.go
생성시 default로 
outbound all deny.(piority=65535), 
outbound all allow(priority=1000) 추가 하여  전체 추가가 삭제되면 all deny가 되도록 처리
=> GCP SecurityGroup 로직 보완

cloud-control-manager/cloud-driver/drivers/openstack/resources/SecurityHandler.go
- IPv4, IPv6 Cidr 제공 
- securityGroup이 생성될 시 default outbound 2개를 자동으로 생성
- 0.0.0.0/0(ipv4), ::/0(ipv6)
- IPv6 Rule의 포맷팅, 로직 개선
- Rule 추가/삭제시 기존 Rule에 따른 에러 리턴
- 추가 : 존재하는 Rule 추가 시 에러
- 제거 : 존재하지 않는 Rule 삭제 시 에러
해당 머지에 대한 outbound Test 결과는 이슈(https://github.com/cloud-barista/cb-spider/issues/482) 코멘트로 추가하겠습니다.
코드 변경에 따른 영향이 있을까 Inbound Test 수행 결과 모두 성공입니다.
=> [Openstack] OutBound 및 공통이슈 개발 방안 적용

cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go
https://github.com/cloud-barista/cb-spider/issues/482#issuecomment-1123283866 에 대한 수정사항입니다.
inbound, outbound 테스트 수행 결과 모두 성공입니다.
- 프로토콜 all :1-65535 => -1 로 통일
- CIDR *인 케이스 => 0.0.0.0/0으로 변경
=> [Azure] All Protocol Port 표현 변경

cloud-control-manager/cloud-driver/drivers/cloudit/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
RootDiskSize 설정 미제공 CSP 에러 핸들링 ([#661 ](https://github.com/cloud-barista/cb-spider/issues/661#issuecomment-1140823380))
IBM-VPC, Cloudit : RootDiskType, RootDiskSize
Openstack: RootDiskType
VMReqInfo에 위 값 제공시 에러 리턴.
=> [IBM-VPC/Cloudit/OpenStack]RootDiskSize 설정 미제공 CSP 에러 핸들링

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/IBMCloudDriver.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/connect/Ibm_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/CommonIbmFunc.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/NLBHandler.go
[IBM-VPC] NLBHandler 기능 구현
- NLBInterface V0.3.1 기준의 NLBHandler 기능 구현입니다.
- NLBInterface가 변경되는대로 수정하겠습니다.
=> [IBM-VPC] NLBHandler

cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go, cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/azure/resources/CommonAzureFunc.go, cloud-control-manager/cloud-driver/drivers/azure/resources/NLBHandler.go
NLBInterface V0.3.1 기준의 NLBHandler 기능 구현입니다.
NLBInterface가 변경되는대로 수정하겠습니다.
- NLBHandler외 커밋사항
- [Azure] VMHandler PublicIP 타입 NLBHandler 가능 PublicIP 타입과 일치
- NLBHandler 생성시, PublicIP 조건
- SKU : Standard, publicIPAllocationMethod: Static
- VM, NLBHandler PublicIP 타입에 대한 통일
- NLBHandler는 VM의 privateIP와 통신하기에 기능상의 변화는 없으나, PublicIP의 타입을 하나로 통일하여, 혼동 방지
=> [Azure] NLBHandler 기능 구현

cloud-control-manager/cloud-driver/drivers/tencent/resources/VMHandler.go
PENDING: creating
RUNNING: running
STOPPED: shut down
STARTING: starting (추가)
STOPPING: shutting down
REBOOTING: rebooting
SHUTDOWN: shut down and to be terminated
TERMINATING: terminating (추가)
=>  issue 687 : Tencent lifecycle 상태값 추가

cloud-control-manager/cloud-driver/drivers/alibaba/resources/NLBHandler.go
ChangeListener : ALIBABA_CANNOT_CHANGE_LISTENER
ChangeVMGroupInfo : ALIBABA_CANNOT_CHANGE_VMGROUP
=> Changing the Error Message

cloud-control-manager/cloud-driver/drivers/gcp/resources/NLBHandler.go
ListNLB 에서
AS-IS : SystemID : url
TO-BE : SystemID : nlbID
=> [GCP] NLB 보완. ListNLB에서 SystemID set 변경

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMHandler.go
- [IBM-VPC] [Want to meet faster VM Status Info](https://github.com/cloud-barista/cb-spider/issues/666)
- vmInfo 관련 성능 개선
- GetVM, ListVM 시 setVmInfo을 통해 vm정보를 순차적으로 조회 (setVmInfo * N)
- setVmInfo 내부에서 여러 API 호출로 많은 시간 소요 
- 개선 항목
- ListVM 순차적  setVmInfo => Go 루틴으로 변경
-  setVmInfo 내부 API => Go 루틴으로 변경
- 성능 향상 간이 테스트 
-  ListVM 함수 첫 부분startTime, 리턴 직전부분 시간 endTime
- VM 5개 - OLD 12.4초
- startTime : 15:54:30.532893959 +0900 m=+19.995078298
- endTime  : 15:54:43.9267173 +0900 m=+33.388901560
- VM 5개 - New 4.7초
- startTime : 16:27:58.727525007 +0900 m=+6.151401299
- endTime  : 16:28:03.373686718 +0900 m=+10.797562885
=> [IBM-VPC] VM 정보 조회 성능 개선(#666)

cloud-control-manager/cloud-driver/drivers/cloudit/resources/CommonClouditFunc.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go
- [Cloudit] [Check the continuous Rebooting status](https://github.com/cloud-barista/cb-spider/issues/692)
- 버그 픽스 사항 : SSH를 통한 Running 상태 확인 후, Running으로 리턴
=> [Cloudit] Cloudit Reboot / Resume 리턴 플로우 변경(#692)

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/NLBHandler.go
[IBM-VPC][Include null in HealthInfo result](https://github.com/cloud-barista/cb-spider/issues/697)
- nil 대신 빈 Array로 리턴
=> [IBM-VPC] GetVMGroupHealthInfo 결과 nil 제거(#697)

cloud-control-manager/cloud-driver/drivers/azure/resources/NLBHandler.go
[Azure] [NLB removeVM 버그](https://github.com/cloud-barista/cb-spider/issues/695#issuecomment-1185083978)
- 제거될 VM의 IP 확인 로직 수정
=> [Azure] NLB removeVM 버그 수정 (#695)

cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
[Azure] [VM Hostname 버그](https://github.com/cloud-barista/cb-spider/issues/707)
- VM Hostname으로 사용할 값 변경
=> [Azure] VM Hostname 오기입 오류 수정(#707)

cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go, cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/azure/resources/CommonAzureFunc.go, cloud-control-manager/cloud-driver/drivers/azure/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
[Azure] DiskHandler 기능 구현
- 기능 구현상 이슈는 없으나, CloudDriver의 DriverCapabilityInfo 내 DiskHandler가 존재하지 않아 Azure에서 일단 주석으로 표시해둔 상태입니다.
- 위 사항이 적용되면 MyImage 머지시 같이 적용하겠습니다.
=> [Azure] DiskHandler 기능 구현

cloud-control-manager/cloud-driver/drivers/aws/resources/CommonHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go
Data-Disk 부착(Attach) 제공을 위한 속성 추가
- VMHandler 보완
. StartVm에서 Instance start 후 attachDisk
. GetVm에서 DataDiskIID Set
=> AWS Disk 핸들러 보완

cloud-control-manager/cloud-driver/drivers/aws/resources/DiskHandler.go, cloud-driver-libs/cloudos_meta.yaml
cloudos_meta.yaml
- aws disktype 구분자 보완
DishHandler.go
- disktype validation check 보완
=> Disk and Driver API 보완[AWS]

cloud-control-manager/cloud-driver/drivers/aws/resources/DiskHandler.go
DishHandler.go
- AttachDisk : deviceName 체크로직 보완
=> [AWS]Disk and Driver API 보완3

cloud-control-manager/cloud-driver/drivers/gcp/resources/CommonHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go
GCP Disk Handler 보완
- CreateDisk에서 Type 입력 시 에러 수정
- Status 변환 function 추가
- CommonHandler에 GetDiskInfo function 추가 (DiskHandler, VMHandler에서 공통으로 사용)
- DetachDisk에서 해제하려는 Disk가 없는 경우 체크
- convertDiskInfo function 추가
=> [GCP] Disk Handler 보완

cloud-control-manager/cloud-driver/drivers/openstack/resources/DiskHandler.go
- Attach, Detach 간헐적 실패 => API 패키지 변경 및 Attach, Detach  완료 대기
- DeleteDisk 성공 시 리턴값 false로 고정된 상황 => 수정
=> [Openstack] DiskHandler 버그 픽스

cloud-control-manager/cloud-driver/drivers/gcp/connect/GCP_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/gcp/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/CommonHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/connect/TencentCloudConnection.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/MyImageHandler.go, go.mod, go.sum
[GCP, Tencent] MyImageHandler 추가
1. MyImageHandler 구현1차 완료
SnapshotVM
ListMyImage
GetMyImage
DeleteMyImage
VMHandler의
- GetVM 에 MyImage 정보 추가
2. Tencent adk version 변경
AS-IS
github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.415
github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm v1.0.206
TOBE
github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common v1.0.487
github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/cvm v1.0.487
=> [GCP, Tencent] MyImageHandler 추가

cloud-control-manager/cloud-driver/interfaces/CloudDriver.go
- Correct a typo 'MyIamgeHandler' -> 'MyImageHandler'
- Update alignment of DriverCapabilityInfo struct
=> Correct a typo 'MyIamgeHandler' -> 'MyImageHandler'

cloud-control-manager/cloud-driver/drivers/gcp/connect/GCP_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/tencent/TencentDriver.go, cloud-control-manager/cloud-driver/drivers/tencent/connect/TencentCloudConnection.go, cloud-control-manager/cloud-driver/drivers/tencent/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/tencent/main/conf/Test_Config.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/CommonHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/VMHandler.go
[Tencent] MyImageHandler 보완
1. CommonHandler.go
- DescribeImages 추가 (ListMyImage에서 사용)
- DescribeImagesByID 추가 (GetMyImage에서 사용)
2. Test_Resources.go
- handleMyImage  추가
3. MyImageHandler.go
- convertImageSetToMyImageInfo 추가 (MyImage Info 변환)
- convertTenStatusToImageStatus (MyImage Status 변환)
- myImageExist 추가 (중복체크)
=> [Tencent] MyImageHandler 보완

cloud-control-manager/cloud-driver/drivers/azure/resources/DiskHandler.go
이슈 (#748) 버그 수정 사항
- Disk List조회시, resourceGroup내의 Disk가 아닌 모든 Disk 조회되는 현상 => 수정
=> [Azure] DiskHandler List 조회시 resourceGroup 내 조회하도록 수정(#748)

cloud-control-manager/cloud-driver/drivers/openstack/OpenStackDriver.go, cloud-control-manager/cloud-driver/drivers/openstack/connect/OpenStack_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/openstack/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/CommonOpenStackFunc.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
[Openstack] MyImageHandler 기능 구현
- snapshot 시행시, Image snapshot과 Volume snapshot이 생성 됩니다. (삭제시 같이 삭제)
- 스냅샷으로서 노출되는 것은   Image snapshot입니다.
- snapshot으로 생성된 vm의 volume은 자동으로 생성되어 제공됩니다.(openstack의 경우, systemid가 이름으로 부여됨)
=> [Openstack] MyImageHandler 기능 구현

cloud-control-manager/cloud-driver/drivers/gcp/connect/GCP_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/VMHandler.go
[Tencent] MyImageHandler 보완 (DataDisk 포함)
- 일전에 말씀해주신 부분(https://github.com/cloud-barista/cb-spider/issues/719#issuecomment-1245306530) 에 대하여 결과 공유드립니다.
- 처음에는 말씀하신 것처럼 Console에 가이드와 같은 옵션이 나타나지 않고, 또한 API에서 DataDisk 옵션을 설정하여도 DataDisk가 포함된 Image가 생성되지 않았습니다.
- 해당 부분에 대하여 Tencent에 문의한 결과 Tencent에서 이 부분을 수정해주었습니다.
- 따라서 현재는 Console에서도 옵션을 확인할 수 있고, API에서 DataDisk 옵션 또한 동작하는 것을 확인하였습니다.
- 해당 사항 반영하여 PR합니다.
=> [Tencent] MyImageHandler 보완 (DataDisk 포함)

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/NLBHandler.go
- ListNLB 시, 각 NLB에 대한 GetNLB를 병렬처리
- GetNLB 시, NLB 구성요소들에 대한 Get 요청들을 병렬처리
=> [IBM-VPC] 이슈 #709 개선, NLB 조회 로직 병렬 요청 적용

cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go, cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/azure/main/conf/config.yaml.sample, cloud-control-manager/cloud-driver/drivers/azure/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/main/Test_Resources.go
- Generalized 기반 Capture MyImage 기능 구현
- SnapshotVM으로 생성된 Image로 VM 생성 기능 구현
=> [Azure]MyImagehandler 기능 구현

cloud-control-manager/cloud-driver/drivers/gcp/resources/CommonHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go, cloud-driver-libs/cloudos_meta.yaml
[GCP] MyImageHandler 수정
- 기존: CreateImage를 이용하여 구현 > CreateMachineImage로 변경
[cloudos_meta.yaml]
- idmaxlength 추가 (AWS, GCP, Tencent, Alibaba)
- https://github.com/cloud-barista/cb-spider/issues/758
=> [GCP] MyImageHandler 수정

cloud-control-manager/cloud-driver/drivers/openstack/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
- Cinder 미제공시 VM 생성가능하도록 로직 변경
- Cinder 미제공시 제한 기능(에러 리턴)
- DiskHandler 기능 사용 불가
- StartVM 시 DiskSize변경 불가
=> [Openstack]Cinder 미제공 시, VM 생성 실패 버그 수정

NOTICE.md
- Add CB-Spider Copyright and License Notice file
- Copyright (C) 2019 ~, Cloud-Barista Community
- Apache License 2.0
=> Add CB-Spider Copyright and License Notice file

cloud-control-manager/cloud-driver/drivers/aws/resources/AnyCallHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/AnyCallHandler.go
o Added sub-functions for AWS
- createTags: renamed from addTags, call aws's CreateTags()
- associateIamInstanceProfile: call aws's AssociateIamInstanceProfile()
- getRegionInfo: get region and zone information from a connection config
o Updated sub-functions for OpenStack
- getConnectionInfo: update the temporary encrypt and encode function
=> Add/Update AnyCall's sub-functions for AWS, OpenStack

cloud-control-manager/cloud-driver/drivers/cloudit/client/ace/disk/Request.go
- Disk의 OwnerVM이 출력되지 않는 오류 수정
=> [Cloudit] Disk 기능시험 결과 오류 수정 2차

api-runtime/rest-runtime/test/full-test/ncp-full_test.sh
- Update NCP Full Test script
- Increase sleep-time after StartVM(), ResumeVM() and RebootVM() in the Test script
- Related Issue) https://github.com/cloud-barista/ncp/issues/74
=> Update NCP driver Full Test script - Increase sleep-time after StartVM, ResumeVM, RebootVM

cloud-control-manager/cloud-driver/drivers/azure/resources/CommonAzureFunc.go, cloud-control-manager/cloud-driver/drivers/azure/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go, cloud-driver-libs/cloudos_meta.yaml
Disk 핸들러 AdminWeb 테스트 보완 사항 
1. DiskType 추가 (cloudos_meta.yaml)
- disktype 추가 
3. DiskType "default" 케이스 추가
- DiskType 케이스 추가 및 오타 수정(StandardHHD => StandardHDD)
5. VM 생성시 DataDisk Attach 기능 누락사항 추가
6.  Disk / NLB / MyImage / Cluster ID MaxLength 사항 추가
AdminWeb을 통한 테스트 후, 테스트 결과 변경해 놓았습니다.
=> [DISK]Azure DiskHandler 버그 픽스 및 누락사항 적용

cloud-control-manager/cloud-driver/drivers/openstack/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go, cloud-driver-libs/cloudos_meta.yaml
1. VM 생성시 DataDisk Attach 기능 누락사항 추가
2.  Disk / NLB / MyImage  ID MaxLength 사항 추가
AdminWeb을 통한 테스트 후, 테스트 결과 변경해 놓았습니다.
=> [DISK]Openstack DiskHandler 버그 픽스 및 누락사항 적용

cloud-control-manager/cloud-driver/drivers/azure/resources/MyImageHandler.go
- Running 중인 VM Snapshot 지원 (#785)
- Suspend 기능 추가  및 오타 수정
=> [Azure] Running 중인 VM Snapshot 지원

cloud-control-manager/CloudDriverHandler_common.go, cloud-control-manager/cloud-driver/drivers/cloudit/client/ace/snapshot/Request.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/MyImageHandler.go
- Admin Web을 통해 Credential의 ClusterId가 전달되지 않는 오류 수정
- NameID, SystemID가 모두 주어진 경우, 리소스를 검색할 수 없는 오류 수정
- SourceVm이 삭제된 경우, MyImage가 목록에 출력되지않는 오류 수정
=> [Cloudit] MyImage 기능시험 결과 오류 수정

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/MyImageHandler.go
- NameID, SystemID가 모두 주어진 경우, 리소스를 검색할 수 없는 오류 수정
- SourceVm이 삭제된 경우, MyImage가 목록에 출력되지않는 오류 수정
=> [IBM-VPC] MyImage 기능시험 결과 오류 수정

cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go
[alibaba, tencent]의 ClusterHandler에
클라우드바리스타에서 권고하는 로깅 양식으로 코드 추가 및 보완 작업을 진행
=> ClusterHandler  로깅 코드 추가

cloud-control-manager/cloud-driver/drivers/azure/resources/NLBHandler.go
NLB Health Probe 값 유효성 검사 수정
-  healthChecker.Interval >= 5
-  healthChecker.Threshold >= 1
healthChecker.Threshold  = 1인 경우 문제가 생겨 유효성 체크를 변경합니다.
추후, NLB Health Probe에 대한 변경사항이 있으면 추가 적용하도록 하겠습니다.
=> [Azure] NLB Health Probe 값 유효성 버그 픽스

cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go
ClusterHandler의 call log 코드를 보완했습니다.
=> fix: call log position

cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMHandler.go
[Alibaba] MyImage 기반 VM 삭제 시 DataDisk 함께 삭제되는 이슈 보완
(https://github.com/cloud-barista/cb-spider/issues/783#issuecomment-1271062641)
- MyImage를 이용하여 VM 생성 시 DataDisk의 DeleteWithInstance Option이 true로 되어 있어 VM 삭제 시 DataDisk 함께 삭제 됨
- 따라서 VM 생성 후 DeleteWithInstance=false로 변경
=> [Alibaba] MyImage 기반 VM 삭제 시 DataDisk 함께 삭제되는 이슈 보완

cloud-control-manager/cloud-driver/drivers/alibaba/main/pmks_test/ClusterHandler_test.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/main/pmks_test/ClusterHandler_test.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go
[PMKS] Proposal to delete two APIs #794 이슈 관련 코드 수정을 완료했습니다.
ClusterHandler API 삭제
- ListNodeGroup
- GetNodeGroup
API 삭제에 따른 테스트 코드 수정
=> [Alibaba, Tencent]: [PMKS] Proposal to delete two APIs #794  이슈 관련 코드 수정

cloud-control-manager/cloud-driver/drivers/tencent/main/pmks_test/ClusterHandler_test.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go
ClusterHandler의 AddNodeGroup시 security group 설정 오류 수정
=> [Tencent] fix security group bug

cloud-control-manager/cloud-driver/drivers/alibaba/main/pmks_test/ClusterHandler_test.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/alibaba/utils/alibaba/alibaba_api.go, cloud-control-manager/cloud-driver/drivers/tencent/main/pmks_test/ClusterHandler_test.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/utils/tencent/tencent_api.go
[Alibaba]
- 값이 없는 정보 추가 (완료)
- subnet_id
- keypair_id
- nodes 
- 잘못된 정보 수정 (완료)
- security_group_id  // 지정한값으로 정보 반환 완료
- 이미지 정보 // 지정 안됨 // not supported in alibaba
- desired_node_size // 지원 안함  // not supported in alibaba
[Tencent]
- 조회시 KeyPair 정보 추가 (완료)
- Node 정보 조회 결과 추가 (완료)
- 노드 생성이 멈추는 현상 해결 (미완료, 조사중)
=> [Alibaba, Tencent] 버그 수정

cloud-control-manager/cloud-driver/drivers/alibaba/main/pmks_test/ClusterHandler_test.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go
[Alibaba] 반환정보 수정
- KeyPairIID의 SystemId 정보 추가
- KeyValueList에서 'meta_data' 정보 제거
=> [Alibaba] 반환정보 수정

cloud-control-manager/cloud-driver/drivers/alibaba/utils/alibaba/alibaba_api.go
[Alibaba] NodePool 강제 삭제 옵션 추가
=> [Alibaba] NodePool 강제 삭제 옵션 추가

cloud-control-manager/cloud-driver/drivers/alibaba/main/pmks_test/ClusterHandler_test.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go
클러스터 생성 옵션 추가
- "endpoint_public_access": true
=> [Alibaba] 클러스터 생성시 endpoint_public_access 옵션 추가

cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go
[Tencent]
- fix: auto_scale_enalbed check bug
- index out of range bug fix
- add stacktrace code
[Alibaba]
- add stacktrace code
=> [Tencent, Alibaba] 버그수정 및 에러 StackTrace 코드 추가

cloud-control-manager/cloud-driver/drivers/tencent/main/pmks_test/ClusterHandler_test.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go
[Tencent] fix DataDisk configuration bug.
=> [Tencent] fix DataDisk configuration bug.

cloud-control-manager/cloud-driver/drivers/cloudit/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go
Windows VM 생성 시,
- SSH Key 대신 전달받은 비밀번호로 VM 생성
- SSH Key 등록 및 SSHD 설정 생략
- 사용자 추가 생략
- Hostname 15자 초과 케이스 예외처리 (Windows가 지원하지 않음)
=> [Cloudit] Windows VM 생성 기능 추가

cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go
[Tencent] add system disk parameter cases
=> [Tencent] add system disk parameter cases 

cloud-control-manager/cloud-driver/drivers/tencent/main/pmks_test/ClusterHandler_test.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go
=> [Tencent] add NodePoolOs setting code.

cloud-control-manager/cloud-driver/drivers/tencent/main/pmks_test/ClusterHandler_test.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/utils/tencent/tencent_api.go
오토스케일링 사이즈 변경 안되는 문제 해결
- 원인: 텐센트 유틸리티에서 "region_id"가 하드코드 되어있어서 발생
- 해결: "region_id"가 동적으로 설정되도록 변경
추가로, 위 문제 발생시 에러 리턴 안하는 버그 수정
=> [Tencent] 오토스케일링 사이즈 변경 안되는 문제 해결

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/MyImageHandler.go
MyImage 생성시, MyImage가 없으면 생성할 수 없는 오류 수정
=> [IBM-VPC] MyImage 생성시, MyImage가 없으면 생성할 수 없는 오류 수정

cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/azure/resources/ClusterHandler.go
- AccessInfo 추가
- 현재 도메인 주소를 리턴하고 있습니다. 혹시 IP주소를 알려주는것이 좋을까요? 
- 리스트 조회시, go루틴 활용한 속도 개선
- 여러 클러스터의 정보 조회시, 많은 시간이 소요되는 거 같아 개선하였습니다.
=> [Azure] Cluster 정보 AccessInfo 추가 및 리스트 조회 개선

cloud-control-manager/cloud-driver/drivers/cloudit/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go
Windows VM 생성 시,
- VM 생성 이후 1회만 VM 비밀번호 반환
- Windows 비밀번호 복잡성 조건 예외처리
=> [Cloudit] Windows VM 사용자 제공 비밀번호 설정

cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/alibaba/utils/alibaba/alibaba_api.go, cloud-control-manager/cloud-driver/drivers/alibaba/utils/alibaba_api_test.go, cloud-control-manager/cloud-driver/drivers/azure/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/interfaces/resources/ClusterHandler.go
[Alibaba] Add AccessInfo Query
#716 AccessInfo 인터페이스 추가 사항 반영
=> [Alibaba] Add AccessInfo Query

cloud-control-manager/cloud-driver/drivers/azure/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/MyImageHandler.go
- Azure: MyImage, Image WindowType 확인 로직 추가
- OpenStack: MyImage. Image WindowType 확인 로직 추가
- IBM-VPC: MyImage, Image WindowType 확인 로직 추가
- Cloudit: MyImage. Image WindowType 확인 로직 추가
=> [InnoCommon] MyImage, Image WindowType 확인 로직 구현

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMHandler.go
- VMImage IID 추가
- VMBootDisk 추가
- RootDiskType 추가
- VMUserId 추가
=> [IBM-VPC] VM 정보 반환 시, 누락된 항목 보완

cloud-control-manager/cloud-driver/drivers/cloudit/client/ace/server/Request.go, cloud-control-manager/cloud-driver/drivers/cloudit/resources/VMHandler.go
- Windows OS 여부에 따른 VMUserID값 분기 처리
- MyImage로 생성된 VM도 원본 PublicImage의 ImageIID를 반환하는 오류 개선
- ImageType 추가
=> [Cloudit] VM 정보 반환 시, 잘못 출력되는 항목의 오류 개선

cloud-control-manager/cloud-driver/drivers/azure/resources/ClusterHandler.go
[Azure] PMKS Server-Driver Integration Test #830
- 기본 생성되는 ClusterSecurityGroup의 Rule이 생성되는것을 확인
- Cluster의 기본 생성 룰이 생성된후, 사용자의 SecurityGroup을 적용
- 사용자룰을 적용하게 먼저 적용하는 경우, 경우에 따라 클러스터의 기본 룰이 밀리는 경우가 있었습니다.
- Async 처리를 위한 웨이팅 시간을 변경하였습니다.
- 간격 1초 => 4초 (빠르게 생성되는 리소스가 아니기에 간격을 늘렸습니다.)
[이슈 코멘트](https://github.com/cloud-barista/cb-spider/issues/830#issuecomment-1307265498)에 있는 API 테스트 Create => List => Get => AddNode => RemoveNode => Delete 테스트 완료하였습니다.(AdminWeb)
=> [Azure]ClusterHandler 버그픽스

cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go
K8S 클러스터 스펙 설정 옵션 추가하고 클러스터 스펙을 프로로 변경
클러스터 스펙별 클러스터 생성 개수
- 표준: 2개
- 프로: 100개
=> [Alibaba] add cluster_spec option

api-runtime/rest-runtime/test/full-test/14.ncpvpc-test.sh
- Apply Japan zones to Full Test script
- Add ncpvpc-japan4-config and ncpvpc-japan5-config to Full Test script
=> Apply Japan zones to Full Test script

cloud-driver-libs/cloudos_meta.yaml
- Update NHN Cloud Meta info
- Add Zone parameter
- Add rootdisksize, disktype and disksize parameters and values
=> Update NHN Cloud Meta info. for RootDisk and DataDisk creation

cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
Window MyImage 생성시, 패스워드 지정 안되는 버그 수정
- ImageType(MyImage, PublicImage)에 따라 password 지정 함수 수정 
- 기존 함수 수정(PublicImage인 경우 동작) changeAdministratorUser =>  createAdministratorUser - VM 생성시 지정되는 임시 유저(cb-user)는 buitin유저로 삭제 불가하여 cb-user삭제 관련 명령어은 삭제하였습니다..
- 유저 비밀번호 변경 함수 생성(MyImage 경우 동작) changeUserPassword
- administrator의 패스워드를 수정해주고, buitin(cb-user)유저 또한 같이 수정해줍니다.
=> [Azure]Window MyImage 패스워드 미지정 버그 수정

cloud-driver-libs/.cloud-init-ncpvpc/cloud-init-windows
- Update NCPVPC MS Windows OS Cloud-init script
- Update Visual Basic Cloud-init script
=> Update NCPVPC MS Windows OS Cloud-init script

cloud-driver-libs/cloudos_meta.yaml
- Add NCP VPC Meta info
- Add Meta info of Supporting RootDisk Type and Size, and DataDisk Type and Size
- Add Max length info of Each Cloud Resource ID
=> Add NCP VPC Meta info for RootDisk and DataDisk, and Max length Info. of Resource ID

cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/VMHandler.go
[AWS, GCP, Alibaba, Tencent] VMInfo.Platform 추가
- VM의 OS Platform 정보 제공 (GetVM, ListVM 시 VMInfo.Platform 제공)
- https://github.com/cloud-barista/cb-spider/issues/862
=> [AWS, GCP, Alibaba, Tencent] VMInfo.Platform 추가

CODE_OF_CONDUCT.md, CONTRIBUTING.md
이후 진행될 Repository 초기 설정을 위한 사전 작업입니다.
=> Update CODE_OF_CONDUCT.md and CONTRIBUTING.md

cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go, cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/azure/resources/RegionZoneHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/OpenStackDriver.go, cloud-control-manager/cloud-driver/drivers/openstack/connect/OpenStack_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/openstack/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/RegionZoneHandler.go, cloud-control-manager/cloud-driver/interfaces/CloudDriver.go
- Azure
-  Implement  Region/Zone APIs
-  Implement TestMenus
- OpenStack
- Implement OpenStack Region/Zone APIs
- Implement TestMenus
=> Implement Azure, OpenStack Region/Zone APIs

cloud-control-manager/cloud-driver/drivers/alibaba/AlibabaDriver.go, cloud-control-manager/cloud-driver/drivers/alibaba/connect/AlibabaCloudConnection.go, cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/alibaba/main/conf/Test_Config.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/CommonHandler.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/RegionZoneHandler.go
[+Region/Zone] Alibaba Cloud Driver Implementation #911
특이사항.
zone에는 사용가능한 resource 종류값들이 들어있음.
- IoOptimized, SystemDiskCategories, InstanceGenerations, DataDiskCategories, InstanceTypes, InstanceTypeFamilies, NetworkTypes
ListRegionZone 구현
- Zone에 Status가 없고 리전에 status값이 있음. ( available, soldOut ). : 비어있거나 available 일 때 Available로 처리
( https://next.api.alibabacloud.com/document/Ecs/2014-05-26/DescribeRegions )
-> Zone 상태가 없으므로 N/A로 반환하도록 변경
ListOrgRegion 구현
ListOrgZone 구현
=> [+Region/Zone] Alibaba Cloud Driver Implementation #911

cloud-control-manager/cloud-driver/drivers/openstack/connect/OpenStack_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/openstack/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/RegionZoneHandler.go
- Add support of getting Zone list by Region
- Add support of getting RegionZone list with zone list for each regions.
=> [+Region/Zone] Implement GetRegionZone() to OpenStack Cloud Driver

cloud-control-manager/cloud-driver/drivers/openstack/resources/RegionZoneHandler.go
- Get RegionZone list in parallel
=> [+Region/Zone] Get OpenStack's RegionZone list in parallel

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/IBMCloudDriver.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/connect/Ibm_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/RegionZoneHandler.go
- Implement all of 4 functions of RegionZoneHandler
- ListRegionZone() (with go routine)
- GetRegionZone()
- ListOrgRegion()
- ListOrgZone()
=> [+Region/Zone] Implement IBM's RegionZoneHandler

api-runtime/rest-runtime/test/region-zone-test/13.nhncloud-region-zone-test.sh, api-runtime/rest-runtime/test/region-zone-test/14.ncpvpc-region-zone-test.sh, api-runtime/rest-runtime/test/region-zone-test/8.ncp-region-zone-test.sh, api-runtime/rest-runtime/test/region-zone-test/region-zone_test.sh
- Add NHN Cloud RegionZoneHandler Test Script
- Update NCP Classic and NCP VPC RegionZoneHandler Test Scripts
=> Add and Update RegionZoneHandler Test Scripts

cloud-control-manager/cloud-driver/drivers/tencent/resources/RegionZoneHandler.go
Reverts cloud-barista/cb-spider#943
- ListRegionZone goroutine bug fix TEN
- goroutine 적용하며 ListRegionZone 출력 내용이 중복되는 버그
- 특이사항
- API 호출 초당 20회 제한
- https://www.tencentcloud.com/document/product/213/15708
- 호출 제한 걸리는 상황 재현시 다음과 같은 오류가 발생.
-`[CLOUD-BARISTA].[ERROR]: 2023-10-05 13:48:26 CommonHandler.go:278, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.DescribeZones() - [TencentCloudSDKError] Code=RequestLimitExceeded, Message=Your current request times equals to `30` in a second, which exceeds the frequency limit `20` for a second. Please reduce the frequency of calls., RequestId=e726665a-c2a0-4769-8414-70888c00749e
`
=> ListRegionZone goroutine bug fix TEN

cloud-control-manager/cloud-driver/drivers/alibaba/resources/RegionZoneHandler.go
Reverts cloud-barista/cb-spider#940
- ListRegionZone goroutine bug fix ALI
- goroutine 적용하며 ListRegionZone 출력 내용이 중복되는 버그
=> ListRegionZone goroutine bug fix ALI

cloud-control-manager/cloud-driver/drivers/aws/resources/RegionZoneHandler.go
Reverts cloud-barista/cb-spider#941
- ListRegionZone goroutine bug fix AWS
- goroutine 적용하며 ListRegionZone 출력 내용이 중복되는 버그
=>  ListRegionZone goroutine bug fix AWS

cloud-control-manager/cloud-driver/drivers/azure/resources/RegionZoneHandler.go
- Remove KeyValueList from ListRegionZone()
=> [+Region/Zone] Remove KeyValueList of Azure

api-runtime/rest-runtime/test/connect-config/11.ktcloud-conn-config.sh, api-runtime/rest-runtime/test/region-zone-test/11.ktcloud-region-zone-test.sh
- Add KT Cloud RegionZoneHandler Test Code
- Update KT Cloud connection config code
- Update 11.ktcloud-conn-config.sh
- Related PR) https://github.com/cloud-barista/ktcloud/pull/61
=> Add KT Cloud RegionZoneHandler Test Code, and Update KT Cloud connection config code

cloud-control-manager/cloud-driver/drivers/ktcloud/README.md
- Update KT Cloud Classic(G1/G2 platform) connection driver README.md
- Update Notice for VPC/Subnet
- Update Precautions for applying Security Group
=> Update KT Cloud Classic(G1/G2) driver README - Update VPC and SecurityGroup related Notes

cloud-control-manager/cloud-driver/drivers/azure/resources/RegionZoneHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/RegionZoneHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/RegionZoneHandler.go
- Fix go routines in RegionZoneHandler of Azure, IBM and OpenStack.
=> [+Region/Zone] Fix go routines in RegionZoneHandler

cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_VMHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMHandler.go
- Update NHN Cloud GuestOS supporting features
- Prevent Invalid Root Disk Size In case of Windows OS
- Apply Windows OS Platform Info to VMInfo
- Prevent a Null Point Error (In case Get VM Info with Invalid VM ID)
=> Update NHN Cloud GuestOS supporting features

cloud-control-manager/cloud-driver/drivers/ncp/connect/NcpCloudConnection.go, cloud-control-manager/cloud-driver/drivers/ncp/main/Test_PriceInfoHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/PriceInfoHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/connect/NcpVpcCloudConnection.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/main/Test_PriceInfoHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/main/test_price.sh, cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/PriceInfoHandler.go, go.mod, go.sum
- Add NCP Classic PriceInfo features
- Add Connection to NcpPriceInfoHandler
- Add NcpPriceInfoHandler
- Add NcpPriceInfoHandler Test codes
- Related issue) https://github.com/cloud-barista/cb-spider/issues/975
- Add NCP VPC PriceInfo features
- Add Connection to NcpVpcPriceInfoHandler
- Add NcpVpcPriceInfoHandler
- Add NcpVpcPriceInfoHandler Test codes
- Related issue) https://github.com/cloud-barista/cb-spider/issues/976
-  Update go.mod and go.sum
- Update ktcloud-sdk-go version v0.1.0 -> v0.1.1-0.20231128062321-d5e69ac1afa2
=> [+Price] Add NCP Classic/NCP VPC PriceInfo features

cloud-control-manager/cloud-driver/drivers/alibaba/resources/PriceInfoHandler.go
- QueryProductList를 통해 컴퓨팅 인프라에서 사용할 수 있는 SubscriptionType 쿼리
- ProductType이 필수 옵션은 아님, 일부 필요할 수 있는 별도 서비스를 위해 구현
- DescribePricingModule을 통해 사용가능한 인스턴스 목록 반환
- InstanceType 키의 존재를 확인하고 Attr 에서 가용한 config 쿼리
- 하지만, Alibaba 에서 특정 몇개의 인스턴스에 대해 500에러 반환 → 쿼타 제한 아님
- DescribeInstanceTypes을 통해 각 인스턴스에 대한 Spec info 반환
- VolumeType, OperatingSystem, PreInstalledSw 등 제공하지 않는 부분 다수. → NA로 표기
- ProductId → regionName + “_” + instanceType
- PricingId → regionName + "*" + instanceType + "*" + subscriptionType + "_" + pricingModulePriceType
- 해당되는 정보를 CSP에서 제공하지 않아 위와 같이 고유 값들을 가질 수 있다고 판단
---
1. **Querying SubscriptionType Through QueryProductList:**
- Utilize **`QueryProductList`** to query SubscriptionType available for computing infrastructure.
- While ProductType is not a mandatory option, it may …
=> [+Price] Alibaba Cloud Driver Implementation #971 

cloud-control-manager/cloud-driver/drivers/ktcloud/connect/KtCloud_Connection.go, cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/main/test_disk.sh, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/DiskHandler.go, go.mod, go.sum
- Add KT Cloud Classic(G1/G2 platform) DiskHandler features
- Add DiskHandler features
- Add DiskHandler Test codes
- Update KtCloud_Connection.go
- Add DiskHandler connection
=> Add KT Cloud Classic(G1/G2 platform) DiskHandler features

cloud-control-manager/cloud-driver/drivers/ktcloud/connect/KtCloud_Connection.go, cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/main/goget-ktsdk.sh, cloud-control-manager/cloud-driver/drivers/ktcloud/main/test_myimage.sh, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VMHandler.go, go.mod, go.sum
- Add MyImageHandler (Image Template) features
- Add MyImageHandler() connection
- Add MyImageHandler (Image Template) Test codes
- Update DiskHandler
- Add GetVolumeIdWithVMid() method
- Add GetKTCloudVM() method
- Update GetVmNameWithId() method
- Update go.mod/go.sum
- Update ktcloud-sdk-go version
- Related PR : https://github.com/cloud-barista/ktcloud-sdk-go/pull/21
=> Add KT Cloud Classic (G1/G2 platform) MyImageHandler (Image Template) features

cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/VMHandler.go
- Update NCP VPC VMHandler
- 'Returns' the error when it does not exist when searching for a VM with the SystemId.
- Before : Just logging the message -> After : Returnning the error message
- Organize the VMHandler codes.
=> [Bug fix] 'Returns' the error when it does not exist when searching for a VM.(NCP VPC)

cloud-control-manager/cloud-driver/drivers/ktcloud-plugin/KtCloudDriver-lib.go, cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_VMHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VPCHandler.go, cloud-driver-libs/.cloud-init-ktcloud/cloud-init-centos, cloud-driver-libs/.cloud-init-ktcloud/cloud-init-ubuntu, cloud-driver-libs/.cloud-init-ktcloud/cloud-init-windows
- Add CreateLinuxInitUserData() method
- Add CreateWinInitUserData() method
- Add and Update Cloud-Init scripts
- Update VMHandler Test code
- Update ImageHandler
- Add CheckWindowsImage() method
- Update MyImageHandler
- Add isPublicImage() and GetKTImage() methods
- Update SnapshotVM() and GetMyImage() methods
- Update KeyPairHandler
- Update CreateKey(), DeleteKey() methods
: To encrypt and store key in the DB
- Update DiskHandler
- Add GetRootVolumeIdWithVMId() method
- Add findAllDiskOfferingIds() and findDiskOfferingId() methods
- Update ListDisk() : Remove filtering
=> Add GuestOS Supporting features and Update KeyPairHandler, DiskHandler

cloud-control-manager/cloud-driver/drivers/ktcloud/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VMHandler.go, cloud-driver-libs/.cloud-init-ktcloudvpc/cloud-init-centos, cloud-driver-libs/.cloud-init-ktcloudvpc/cloud-init-windows
- Update KT Cloud VMHandler
- Update StartVM()
- Update KT Cloud NLBHandler
- Update CreateNLB() and DeleteNLB() method
- Add KT Cloud VPC Guest OS Cloud-Init scripts
=> Update KT Cloud VMHandler StartVM() and NLBHandler CreateNLB()/DeleteNLB()

cloud-control-manager/cloud-driver/drivers/alibaba/resources/PriceInfoHandler.go
- filter 
- purchaseOption to pricingPolicy
=> Ali priceInfo filter key value

cloud-control-manager/cloud-driver/drivers/azure/resources/PriceInfoHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/PriceInfoHandler.go
- [Azure: Make filtering to work](https://github.com/ish-hcc/cb-spider/commit/2240b39296b30451904ec73b4eb5290c4bc8c975)
- [IBM: Make filtering to work](https://github.com/ish-hcc/cb-spider/commit/b662ed835fd826a251bde386887cfd2ca57c27af)
=> [+Price] Make filtering to work on Azure and IBM

cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_ImageHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_VMHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/CommonNhnCloudFunc.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/RegionZoneHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VPCHandler.go
- Update NHN Cloud ImageHandler
- Add CheckWindowsImage() method and Test code of it
- Update Local Function Naming Convention for All NHN Cloud Handlers
- Change The First Letter of Local Functions as a Lowercase
- Related Issues :  
- https://github.com/cloud-barista/cb-spider/issues/1045
- https://github.com/cloud-barista/cb-spider/issues/1046
=> Add NHN Cloud - CheckWindowsImage(), and Change The First Letter of Local Functions as a Lowercase

cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go
추가 오류가 발견되어 수정하였습니다.
fix #1012
=> Prevent to access all indexes out of range [0] with length 0

cloud-control-manager/cloud-driver/drivers/nhncloud/README.md, cloud-control-manager/cloud-driver/drivers/nhncloud/connect/NHN_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_VPCHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VPCHandler.go, go.mod, go.sum
- Update NHN_CloudConnection.go
- Add CredentialInfo to VPCHandler Connection
- Update NHN VPCHandler
- Apply New Struct and Package of VPC/Subnet
- Add CreateVPC(), createSubnet() method according to New API
- Update GetVPC() and ListVPC() method according to New API
- Update mappingVpcInfo()
- Add mappingVpcSubnetInfo()
- Update NHN Cloud Go SDK version
- Update NHN Cloud NLBHandler
- Apply New Struct and Package of VPC/Subnet
- Update NHN Cloud README.md
- Update Notice of VPC and Subnet
=> Apply New REST API for NHN Cloud VPC - Update CreateVPC(), createSubnet(), GetVPC(), ListVPC() method

cloud-control-manager/cloud-driver/drivers/nhncloud-plugin/NHNCloudDriver-lib.go, cloud-control-manager/cloud-driver/drivers/nhncloud/NHNCloudDriver.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_NLBHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_VMHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_VPCHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/CommonNhnCloudFunc.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VPCHandler.go, cloud-driver-libs/cloudos_meta.yaml, go.mod, go.sum
- Update VPCHandler
- Add AddSubnet()
- Add RemoveSubnet() 
- Update DeleteVPC()
- Update mappingVpcInfo() and mappingSubnetInfo()
- Update VPCHander Test Code
- Related NHN Cloud go SDK PRs
- https://github.com/cloud-barista/nhncloud-sdk-go/pull/27
- https://github.com/cloud-barista/nhncloud-sdk-go/pull/28
- https://github.com/cloud-barista/nhncloud-sdk-go/pull/29
- https://github.com/cloud-barista/nhncloud-sdk-go/pull/30
- Related issue
- https://github.com/cloud-barista/cb-spider/issues/1059  
- Update NLBHandler, SecurityHandler and CommonNhnCloudFunc.go
- Update Network info according to New VPC/Sunbnet APIs
- Update NHN Cloud go SDK version
- Update CloudOS-meta info for NHN Cloud Service
- Related issue : …
=> [NHN Cloud] Update VPCHandler, NLBHandler and SecurityHandler - according to New VPC/Sunbnet APIs

cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMHandler.go
- Prevent error when there is no associated PubicIP for a VM when getting VMInfo List
=> Prevent an error when there is no associated Pubic IP when getting VM Info List

cloud-control-manager/cloud-driver/drivers/alibaba/README.md
Alibaba 드라이버의 ClusterHandler와 관련한 특이사항 등을 간략히 기록한 내용을 추가합니다.
=> Add README.md for Alibaba Driver

cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go
Alibaba와 Tencent의 ClusterHandler에 파라미터 검증 코드를 추가하였습니다.
=> Add more validation

cloud-control-manager/cloud-driver/drivers/nhncloud-plugin/NHNCloudDriver-lib.go, cloud-control-manager/cloud-driver/drivers/nhncloud/NHNCloudDriver.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMHandler.go
- Update NHNCloudDriver.go and NHNCloudDriver-lib.go
- Optimize ConnectCloud() method code - Reduce the number of authentication call to obtain token
=> [NHN Cloud] Optimize ConnectCloud() method - Reduce the number of authentication call to obtain token

cloud-control-manager/cloud-driver/drivers/nhncloud/NHNCloudDriver.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_DiskHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_ImageHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_NLBHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_RegionZoneHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_VMHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_VPCHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/CommonNhnCloudFunc.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/RegionZoneHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VPCHandler.go, go.mod, go.sum
nhncloud-sdk-go가 업데이트되어 일부 패키지명 변경 등이 발생하여 이를 반영한 내용을 업데이트합니다.
또한 gofmt를 활용하여 drivers/nhncloud 코드를 업데이트하였습니다.
참고로 VPC/Subnet, SG, Keypair, VM 생성까지 진행해보았습니다.
=> Apply nhncloud sdk go updates

cloud-control-manager/cloud-driver/drivers/alibaba/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/VPCHandler.go
[Alibaba] Add Default Region/Zone to Connection and Allow API Calls to Specify Target Zone
VPC는 Region base, Subnet은 zone base 이므로
subnet 생성시 zone parameter가 있으면 해당 zone을 사용하도록 보완.
VPCs are based on Regions and Subnets are based on zones, when creating a subnet, if a zone parameter is provided, it should be adjusted to use the specified zone
Disk는 zone base이므로 subnet 생성시 zone parameter가 있으면 해당 zone을 사용하도록 보완.
Disks are based on zones, when creating a disk, if a zone parameter is provided, it should be adjusted to use the specified zone.
if diskReqInfo.Zone != ""{
zoneId = diskReqInfo.Zone
}
=> [Alibaba] Add Default Region/Zone to Connection and Allow API Calls to Specify Target Zone by #1067

cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go
클러스터 생성시 함께 생성된 인터넷 NAT 게이트웨이 삭제 후 사용되었던 EIP가 남아있던 이슈를 해결하였습니다.
fix #1123
=> Fix release eip when deleting internet nat gateway in alibaba

cloud-control-manager/CloudDriverHandler_common.go, cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go, cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/azure/main/conf/config.yaml.sample, cloud-control-manager/cloud-driver/drivers/azure/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/CommonAzureFunc.go, cloud-control-manager/cloud-driver/drivers/azure/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/RegionZoneHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VPCHandler.go, cloud-control-manager/cloud-driver/interfaces/CloudDriver.go, go.mod
https://github.com/cloud-barista/cb-spider/issues/1008
The above issue was fixed.
=> Azure: Fix issue of creating resource group if not exist

api-runtime/rest-runtime/admin-web/AdminWeb-CIM.go, api-runtime/rest-runtime/test/connect-config/2.azure-conn-config.sh, cloud-control-manager/CloudDriverHandler_common.go, cloud-control-manager/cloud-driver/drivers/azure/AzureDriver.go, cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/azure/main/conf/config.yaml.sample, cloud-control-manager/cloud-driver/drivers/azure/resources/CommonAzureFunc.go, cloud-control-manager/cloud-driver/drivers/azure/resources/RegionZoneHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go, cloud-driver-libs/cloudos_meta.yaml
- Zone will not set if the region is not support available zones.
- "1" will be used as the default zone if configured zone is not found.
=> Azure: Support zone for Azure Driver

cloud-control-manager/cloud-driver/drivers/azure/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
- [Setting VM's zone from server info](https://github.com/cloud-barista/cb-spider/commit/bb1af47fd3909d4db86e330fe207cc95520cba11)
- [Setting zone for Disk](https://github.com/cloud-barista/cb-spider/commit/8093225fde5e5dcf0ea9045b360a1b4875f7c4c2)
=> Azure: Support zone for disk

cloud-control-manager/cloud-driver/drivers/nhncloud/README.md, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VPCHandler.go
- Update DiskHandler > CreateDisk() and mappingDiskInfo() method
- Specify Zone when Creating a Disk, and Apply Zone Info when Get/List Disk info
- Related issue : https://github.com/cloud-barista/cb-spider/issues/1067
- Update VPCHandler > DeleteVPC() method
- [Bug Fix] Remove the Subnets belonging to the VPC when Delete a VPC
=> [NHN Cloud] Specify Zone when Creating a Disk, and Apply Zone Info when Get/List Disk info

cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VPCHandler.go
- Update KT Cloud VPC > VPCHandler
- Update mappingSubnetInfo()  
: Add Zone Info to Subnet Info
- Update DeleteVPC() method error handling [Bug fix]
=> [KT Cloud VPC] Add Zone Info to Subnet Info. and, Update DeleteVPC() method error handling

cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go
alibaba와 nhncloud에서 각 CSP에 맞게 클러스터의 노드 이미지 요청 사항을 검증하도록 수정하였습니다.
=> Fix to validate node image in alibaba and nhncloud

cloud-control-manager/cloud-driver/drivers/alibaba/resources/VMHandler.go
https://github.com/cloud-barista/cb-spider/pull/1173
- Default 설정 시 Set 될 때 우선순위 수정
- 인스턴스 별 가능한 disk 목록에서
- Meta 정보의 순서대로 Set
- 만약, Alibaba에서 인스턴스 별 사용 가능한 Disk목록에서
- 해당 목록 순서의 기준이 있다면 적용한다
=> [Alibaba] Modify priority Disk list 

cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go
alibaba/pmks에서 노드 그룹 추가 시 해당 인스턴스 타입의 가용성을 확인한 후 진행되도록 개선하였습니다.
fix #1189
=> Check availability of instance type when adding nodegroup

cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/azure/resources/ClusterHandler.go
- 클러스터 생성시 nil 포인터 에러 이슈 수정
- 클러스터 생성시 사용가능한 k8s 버전인지 확인 및 에러메세지에 사용가능한 버전들 표시 기능 추가
=> Azure: Fix creating of cluster and check available k8s versions

cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go
Alibaba에서 노드그룹 추가할 때 이미지 타입을 지정하지 않는 경우 기본값으로 AliyunLinux2(지원종료)가 설정되어, 이미지 타입을 default로 설정시 AliyunLinux3가 설정되도록 수정하고, 이미지 타입(ImageIID)을 필수 입력으로 수정하였습니다.
=> Set default imagetype as AliyunLinux3 when adding nodegroup

cloud-control-manager/cloud-driver/call-log/calllogger.go, cloud-control-manager/cloud-driver/call-log/gen4test/gen_calllog.go
var resTypeList = []call.RES_TYPE{
call.REGIONZONE,
call.VMIMAGE,
call.VMSPEC,
call.VPCSUBNET,
call.SECURITYGROUP,
call.VMKEYPAIR,
call.DISK,
call.VM,
call.MYIMAGE,
call.NLB,
call.TAG,  --> added
}
=> add TAG To resType

cloud-control-manager/cloud-driver/drivers/openstack/connect/OpenStack_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/openstack/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/TagHandler.go
- Add new tag feature to OpenStack.
- Need to implement tagging for each resources later.
=> OpenStack: Add TagHandler

cloud-control-manager/cloud-driver/drivers/openstack/OpenStackDriver.go, cloud-control-manager/cloud-driver/drivers/openstack/connect/OpenStack_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/openstack/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/openstack/main/conf/config.yaml.sample, cloud-control-manager/cloud-driver/drivers/openstack/resources/CommonOpenStackFunc.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/TagHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VPCHandler.go
- Fix bugs in TagHandler.
- Fix delete bug in SecurityHandler when systemID is not provided.
- Add tagging feature for supported resources
=> OpenStack:  Add tagging feature for supported resources

cloud-control-manager/cloud-driver/drivers/ncp/README.md, cloud-control-manager/cloud-driver/drivers/ncp/connect/NcpCloudConnection.go, cloud-control-manager/cloud-driver/drivers/ncp/main/Test_TagHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/TagHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/VMHandler.go
- Create NCP Classic TagHandler (Init commit)
- Add AddTag(), GetTag() and RemoveTag()
- Add Testing code of them
- Update NCP Classic README.md
- Add Notice of Tagging feature
- Update NCP Classic VMHandler
- Remove Unnecessary Error Log (Change cblogger.Error to cblogger.Debug)
=> [NCP Classic] Create TagHandler (Init commit) - Add AddTag(), GetTag(), RemoveTag(), and Testing code of them

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/IBMCloudDriver.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/connect/Ibm_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/conf/config.yaml.sample, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/PriceInfoHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/TagHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VPCHandler.go
- Implement TagHandler
- PriceInfoHandler: Show cluster prices
- ClusterHandler: Fix cluster creating issue
- ClusterHandler: Fix security group setup issue while creating cluster
- config: Update k8s version
- Add cluster support to TagHandler
IBM is too difficult to implement..
Need to support some resources to TagHandler
- NLB
- MYIMAGE
- NODEGROUP
Need to implement tagging feature for supported resources.
=> IBM: Implement TagHandler

cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VPCHandler.go, go.mod, go.sum
- Update KT Cloud VPC > VPCHandler
- Add createSubnet() func. and Apply it to CreateVPC() and AddSubnet()
- Related issue : https://github.com/cloud-barista/cb-spider/issues/1178
- Update KT Cloud VPC SDK version
=> [KT Cloud VPC] Add createSubnet() func. and Apply it to CreateVPC() and AddSubnet()

cloud-control-manager/cloud-driver/drivers/ktcloud/connect/KtCloud_Connection.go, cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_TagHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/main/test_tag.sh, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/TagHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VMHandler.go, go.mod, go.sum
- Add KT Cloud Classic Tagging Features and Test Codes for them
- Add TagHandler and Test codes
- Update VMHandler, MyImageHandler, DiskHandler to apply TagList info to them
- Update KT Cloud Classic SDK version
- Related PR : https://github.com/cloud-barista/ktcloud-sdk-go/pull/23
=> [KT Cloud Classic] Add Tagging Features and Test Codes for them

cloud-control-manager/cloud-driver/drivers/azure/resources/ImageHandler.go
GetImage()에서 비정상적인 이미지일때 에러를 리턴하도록 수정하였습니다.
=> [azure:vm] fix getimage

api-runtime/common-runtime/CommonManager.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/CommonAlibabaFunc.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/MyImageHandler.go
@powerkimhub 
- ComonManager.go
- alibaba의 에러 메세지 추가 
- "noresult"
- CommonAlibabaFunc.go
- myImage의 return값 "ecs"로 수정
- MyImageHandler.go
- sourceVM IID 및 커스텀 태그 추출 수정
=> [Alibaba] Fix issue with myImage Tag, add statement to handle CSP error messages

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/connect/Ibm_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/conf/config.yaml.sample, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/CommonIbmFunc.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/TagHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VPCHandler.go
- Fixed all of wrong tagging logics of IBM.
- Fixed for all of resources.
- Tested for all of resources with creating, getting and deleting.
- Tested with TagHandler.
=> [IBM] Fix tagging for all of resources

cloud-control-manager/cloud-driver/drivers/aws/resources/ClusterHandler.go
CSP의 cluster/nodegroup status 값을 CB-SP의 status 값으로 변경합니다.
=> [aws:cluster] apply to convert csp's status to own status

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/CommonIbmFunc.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/TagHandler.go
- Validate TAGs for empty strings and ignore `:`.
=> [IBM] Validate tags

cloud-control-manager/cloud-driver/drivers/openstack/resources/TagHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
- Fix tags are not showing for VM.
- Fix can't add tags to VM.
- Fix internal server error related with flavor.
=> [OpenStack] Fix VM's tag feature

cloud-control-manager/cloud-driver/drivers/gcp/resources/ClusterHandler.go
GCP용 클러스터 드라이버에서 AddNodeGroup 호출시 default 값 지원 및 SystemId를 keypair값으로 대체하는 부분이 누락된 것을 수정합니다.
=> [gcp:cluster] support default word for rootdisksize and rootdisktype

cloud-control-manager/cloud-driver/drivers/gcp/resources/ClusterHandler.go
kubeconfig 내용을 생성하여 제공하도록 수정합니다.
AWS와 마찬가지 동일한 방식(#1141)이며, kubectl을 실행하는 장비에 gke-gcloud-auth-plugin 등의 설치가 필요합니다.
=> [gcp:cluster] support kubeconfig

cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go
- Fixed zone control issue of VM.
=> [OpenStack] Fix VM zone control

cloud-control-manager/cloud-driver/drivers/azure/resources/CommonAzureFunc.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
- Fix nil pointer error while gettig root disk type from the VM.
=> [Azure] Fix nil pointer error while listing VMs

cloud-control-manager/cloud-driver/drivers/ncp/README.md, cloud-control-manager/cloud-driver/drivers/ncp/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/VPCHandler.go
- NCP Classic VMHandler
- Update VM Tagging feature
- NCP Classic VPCHandler
- Add Requested Zone info to Subnet Info
- Update README
- Update Notice about NCP Classic cloud-init script management
=> [NCP Classic] Update VM Tagging feature

cloud-control-manager/cloud-driver/drivers/nhncloud/resources/RegionZoneHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VPCHandler.go
- Prevent internal server error related with flavor
- Fix VM zone control
- Fix duplicated subnet listing issue
- Fix zone names are not displayed and sort region/zone
=> [NHN] Fix zone control with some other issues

cloud-control-manager/cloud-driver/interfaces/resources/KeyPairHandler.go
- Keypair에 빠진 ListIID()를 추가하였습니다
=> interface: Add missed ListIID() in KeyPairHandler

cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/VPCHandler.go
-  Update Zone-based control
- Update NCP VPC DiskHandler
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1298  
- Update NCP VPC VPCHandler and VMHandler
=> [NCP VPC] Update Zone-based control

cloud-control-manager/cloud-driver/drivers/ncp/resources/CommonNcpFunc.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/VPCHandler.go
- Update NCP Classic VPCHandler, VMHandler and DiskHandler for Zone-based control
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1288
=> [NCP Classic] Update Zone-based control

cloud-control-manager/cloud-driver/drivers/openstack/resources/TagHandler.go
=> [OpenStack] Fix removing tags of NLB

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/VPCHandler.go
- Implement ListIID() for all resources.
=> [IBM] Implement ListIID()

cloud-control-manager/cloud-driver/drivers/azure/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
=> [Azure] Implement VM's ListIID()

cloud-control-manager/cloud-driver/drivers/nhncloud/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/VPCHandler.go
- Implement ListIID() for all resources.
=> [NHN] Implement ListIID()

cloud-control-manager/cloud-driver/drivers/openstack/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/openstack/resources/VPCHandler.go
- Implement ListIID() for supported resources.
=> [OpenStack] Implement ListIID()

cloud-control-manager/cloud-driver/drivers/azure/resources/ImageHandler.go
- Show VM image list errors as info
- Related issue: https://github.com/cloud-barista/cb-spider/issues/1364
=> [Azure] Show VM image list errors as info

cloud-control-manager/cloud-driver/drivers/gcp/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go
@powerkimhub 
- [https://cloud-barista.slack.com/archives/CLFCLNFTJ/p1727683197934229](https://github.com/MZC-CSC/cb-spider/pull/url)
- Tencent add tag시 보이지 않던 오류 해결하였습니다.
- clusterHandler.go
- Get cluster시 tagList 추가하여 반환하도록 수정
=> [Tencent] Resolve cluster tag issue

cloud-control-manager/cloud-driver/drivers/openstack/OpenStackDriver.go
- Do not listing services for non-admin users
=> OpenStack: Do not listing services for non-admin users

cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/aws/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/aws/resources/VPCHandler.go
- bug fix #1269 
- Added AWS ListIID func
=> Added AWS ListIID and Bug fix #1269

cloud-control-manager/cloud-driver/drivers/ncp/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/TagHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/VMHandler.go
[NCP Classic] Update Tag management features
- Update VMHandler, TagHandler, DiskHandler
=> [NCP Classic] Update Tag management features

cloud-control-manager/cloud-driver/drivers/openstack/OpenStackDriver.go
- Fix volume clinet initialization issue.
=> OpenStack: Fix volume clinet initialization

cloud-control-manager/cloud-driver/drivers/ncp/main/Test_DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/main/Test_KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/main/Test_MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/main/Test_NLBHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/main/Test_SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/main/Test_VMHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/main/Test_VPCHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/VPCHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/main/Test_DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/main/Test_KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/main/Test_MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/main/Test_NLBHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/main/Test_SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/main/Test_VMHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/main/Test_VPCHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/VPCHandler.go
[NCP Classic/VPC] 
- Update IID List retrieving feature of cloud resources (For VPC, VM, SecurityGroup, NLB, MyImage, KeyPair, Disk)
- Update IID List retrieving feature test codes
=> [NCP Classic/VPC] Update IID List retrieving feature of cloud resources

cloud-control-manager/cloud-driver/drivers/nhncloud/resources/RegionZoneHandler.go
- Add a new region US1 Califonia
- Change Korean names to English
=> NHN: Update NHN regions

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/RegionZoneHandler.go
- Show display names of regions
- IBM does not provide names from APIs, so mapped using hard-coded values.
=> IBM: Show display names of regions

cloud-control-manager/cloud-driver/drivers/alibaba/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/tencent/main/Test_Resources.go, cloud-driver-libs/region/alibaba_region_meta.yaml, cloud-driver-libs/region/aws_region_meta.yaml, cloud-driver-libs/region/gcp_region_meta.yaml, cloud-driver-libs/region/tencent_region_meta.yaml
Add region_meta.yaml files (aws,gcp,tencent,alibaba)
aws_region_meta.yaml
gcp_region_meta.yaml
tencent_region_meta.yaml
alibaba_region_meta.yaml
=> Add region_meta.yaml aws,gcp,tencent,alibaba

cloud-driver-libs/region/azure_region_meta.yaml, cloud-driver-libs/region/ibmcloud-vpc_region_meta.yaml, cloud-driver-libs/region/nhncloud_region_meta.yaml, cloud-driver-libs/region/openstack_region_meta.yaml
- Add metadata YAMLs for Azure, IBM, NHN and OpenStack
=> cloud-driver-libs: region: Add metadata YAMLs for Azure, IBM, NHN and OpenStack

cloud-control-manager/cloud-driver/drivers/azure/resources/VMSpecHandler.go
- Add more information to VMSpec
Related Issue: https://github.com/cloud-barista/cb-spider/issues/1396
=> Azure: Add more information to VMSpec

cloud-control-manager/cloud-driver/drivers/azure/resources/VMSpecHandler.go
- VM 스펙 GPU 정보의 단위가 현재 GB단위라 MB단위로 수정하였습니다
=> Azure: Fix GPU spec info

cloud-control-manager/cloud-driver/drivers/openstack/resources/VMSpecHandler.go
- Add more information to VMSpec
=> OpenStack: Add more information to VMSpec

cloud-control-manager/cloud-driver/drivers/azure/resources/ImageHandler.go
=> Azure: Add more VM image info

cloud-control-manager/cloud-driver/drivers/openstack/resources/ImageHandler.go
=> OpenStack: Add more VM image info

cloud-control-manager/cloud-driver/drivers/ibmcloud-vpc/resources/ImageHandler.go
=> IBM: Add more VM image info

api-runtime/rest-runtime/admin-web/html/disk.html, api-runtime/rest-runtime/admin-web/html/vpc-subnet.html
Enhancement a zone info for the AdminWeb - Issue #1415
=> AdminWeb: Enhancement a Zone Info for Disk and Subnet

api-runtime/rest-runtime/admin-web/html/vm.html
#1431
change color of messages : red to black
=> Change the Color of INFO Messages

cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/azure/resources/NLBHandler.go
- Refactor NLB codes
- Fix getting VM list of NLB
=> AzureL Refactor NLB and fix getting VM list of NLB

cloud-control-manager/cloud-driver/drivers/azure/connect/Azure_CloudConnection.go, cloud-control-manager/cloud-driver/drivers/azure/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/azure/resources/VPCHandler.go
- Re-work NLBHandler
Fix #1427
=> Azure: Re-work NLBHandler

api-runtime/rest-runtime/admin-web/html/nlb.html
=> Make a Add VM button in AdminWeb

api-runtime/rest-runtime/admin-web/html/nlb.html
To Support a VM Removal in NLB (#1442)
=> Add a Remove VM button in NLB Management

api-runtime/common-runtime/SecurityGroupManager.go, api-runtime/rest-runtime/SecurityGroupRest.go
- Add a ListVpcFunction in SecurityGroupManager.go 
for the /securitygroup/vpc/{VPCName}
- Permission based was not taken into consideration.
=> Added a ListVpcFunction in SecurityGroupManager.go

cloud-control-manager/cloud-driver/drivers/ncp/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/RegionZoneHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/RegionZoneHandler.go, cloud-driver-libs/region/ncp_region_meta.yaml, cloud-driver-libs/region/ncpvpc_region_meta.yaml
- Enhance Supported Region and Zone Info
- Update NCP Classic RegionZoneHandler
- Update NCP VPC RegionZoneHandler
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1389
- Enhance Supported VM Image Info
- Update NCP Classic ImageHandler
- Update NCP VPC ImageHandler
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1405
=> [NCP Class/VPC] Enhance Supported Region/Zone Info and VM Image Info

cloud-control-manager/cloud-driver/drivers/ncp/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/ncp/resources/VMSpecHandler.go
- Update ImageHandler, MyImageHandler, VMHandler and VMSpecHandler
- Update CheckWindowsImage() and isPublicImage()
- Deduplicate VM Spec info list
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1422
- Update VMSpecHandler
- Enhance Supported VM Spec Info 
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1396
=> [NCP Classic] Update CheckWindowsImage(), Deduplicate VM Spec info list, and, Enhance Supported VM Spec Info

api-runtime/common-runtime/SecurityGroupManager.go
the error message looks like
```json
{
"message": "The VPC-alibaba-tpc-6wg does not exist!"
}
```
=> Return Error Message if there's no vpc name

cloud-control-manager/cloud-driver/drivers/openstack/resources/NLBHandler.go
- Fix NLB VM health check
- Related Issue: https://github.com/cloud-barista/cb-spider/issues/1440#event-16059778010
=> OpenStack: Fix NLB VM health check

cloud-control-manager/cloud-driver/drivers/ktcloud/README.md, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/RegionZoneHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/ImageHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/RegionZoneHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VMSpecHandler.go
- Update KT Cloud Classic(G1/G2 platform) and KT Cloud VPC(D platform) connection driver
- Enhance Supported RegionZone Info 
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1389
- Enhance Supported VM Image Info
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1405
- Enhance Supported VM Spec Info
- Related issue) https://github.com/cloud-barista/cb-spider/issues/1396
- Update KT Cloud Classic README.md
=> [KT Cloud Classic/VPC] Enhance Supported RegionZone / VM Image / VM Sepc Info

cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_NLBHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_VMHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/main/Test_VPCHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloud/resources/VPCHandler.go
[ KT Cloud Classic(G1/G2 platform) ]
- Update VPCHandler, SecurityHandler, KeyPairHandler, VMHandler, DiskHandler, MyImageHandler, NLBHandler
- Update ListIID() method of the Handlers
- Update ListIID() method test codes for the Handlers
=> [KT Cloud Classic] Update IID listing features

api-runtime/rest-runtime/admin-web/html/main.html
=> Change 'i' in VM image to Uppercase in adminweb's menu.

cloud-control-manager/cloud-driver/drivers/ktcloudvpc/main/Test_DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/main/Test_KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/main/Test_MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/main/Test_NLBHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/main/Test_SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/main/Test_VMHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/main/Test_VPCHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VPCHandler.go
[ KT Cloud VPC (D platform) ]
- Update KT Cloud VPC connection driver (VPC/Security/KeyPair/VM/Disk/MyImage/NLB Handler)
- Update ListIID() method of the Handlers
- Update VPC/Security/KeyPair/VM/Disk/MyImage/NLB Handler Test codes
- Add ListIID() method testing features
=> [KT Cloud VPC (D platform)] Update IID listing features

cloud-control-manager/cloud-driver/drivers/alibaba/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go
본 PR은 Alibaba/Tencent/NHNCloud의 클러스터 핸들러 내에서 사용된 KeyValueList 항목에 대해 공통 함수(StructToKeyValueList())를 적용합니다.
@hanizang77
=> [Alibaba/Tencent/NHN:PMKS] Apply StructToKeyValueList()

cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/DiskHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VMHandler.go, cloud-control-manager/cloud-driver/drivers/ktcloudvpc/resources/VPCHandler.go
- Update KT Cloud VPC : VPC/KeyPair/VM/Disk/MyImage/NLB Handler
- Update KeyValue list info of the resources with StructToKeyValueList() fuction
=> [KT Cloud VPC] Update KeyValue list info of resources with StructToKeyValueList()

cloud-control-manager/cloud-driver/drivers/aws/AwsDriver.go, cloud-control-manager/cloud-driver/drivers/aws/main/Test_Resources.go
Modify default null check logic for StsToken field during AWS driver connection initialization
=> Updated null check logic for StsToken field default value

cloud-control-manager/cloud-driver/drivers/ncpvpc/resources/VPCHandler.go
- Update NCP VPC > VPCHandler
- Add Waiting time to RemoveSubnet() to Check the Status until the Subnet is Completely Deleted.
- Note) Since Subnet Deletion is processed Asynchronously, a Waiting time for Checking the Status of the Subnet is added already inside DeleteVPC(), but since no waiting time is applied to RemoveSubnet(), it was added.
- Related issue : https://github.com/cloud-barista/cm-beetle/issues/168#issuecomment-3157220177
=> [NCP VPC] Add Waiting time to Removesubnet() to Check the Status until the Subnet is Completely Deleted

build_all_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/alibaba-plugin/build_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/aws-plugin/build_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/azure-plugin/build_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/gcp-plugin/build_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/ibm-plugin/build_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/kt-plugin/build_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/ktclassic-plugin/build_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/ktclassic/resources/VPCHandler.go, cloud-control-manager/cloud-driver/drivers/mock-plugin/build_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/ncp-plugin/build_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/nhn-plugin/build_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/openstack-plugin/build_driver_lib.sh, cloud-control-manager/cloud-driver/drivers/tencent-plugin/build_driver_lib.sh, test/vm-cb-user-validation-cli/common/alibaba/setup.env
- Fixed error during dynamic mode build
- Updated handling of KTClassic VPC creation: treat `file not found` as `VPC does not exist`
=> [fix] build dynamic mode error and KTClassic VPC Creation error

api-runtime/rest-runtime/test/connect-config/13.nhn-conn-config.sh, api/docs.go, api/swagger.json, api/swagger.yaml, cloud-control-manager/cloud-driver/drivers/nhn/main/conf/config.yaml.sample, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/Test_ClusterHandler.go, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/Test_DiskHandler.go, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/Test_ImageHandler.go, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/Test_KeyPairHandler.go, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/Test_MyImageHandler.go, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/Test_NLBHandler.go, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/Test_RegionZoneHandler.go, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/Test_SecurityHandler.go, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/Test_VMHandler.go, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/Test_VMSpecHandler.go, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/Test_VPCHandler.go, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/goget-sdk.sh, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/test_disk.sh, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/test_image.sh, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/test_keypair.sh, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/test_myimage.sh, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/test_nlb.sh, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/test_region-zone.sh, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/test_security.sh, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/test_vm.sh, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/test_vmspec.sh, cloud-control-manager/cloud-driver/drivers/nhn/main/each-test/test_vpc.sh
- Update ./connect-config/13.nhn-conn-config.sh
- Fix Typo of Endpoint URL : api-identity-infrastructure.nhnservice.com -> api-identity-infrastructure.nhncloudservice.com
- Add US region
- Update config.yaml for NHN driver Test Code
- Add US region
- Add Test codes for Each Resource Handler test
- Update Swagger API docs
=> [NHN] Fix Typo of Endpoint URL for nhn-conn-config, and Add Test codes for Each Resource Handler test

api-runtime/common-runtime/S3Manager.go, api-runtime/rest-runtime/CBSpiderRuntime.go, api-runtime/rest-runtime/S3Rest.go, api-runtime/rest-runtime/admin-web/AdminWeb-S3.go, api-runtime/rest-runtime/admin-web/html/s3.html, cloud-control-manager/cloud-driver/drivers/alibaba/AlibabaDriver.go, cloud-control-manager/cloud-driver/drivers/alibaba/connect/AlibabaCloudConnection.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/AnyCallHandler.go, cloud-control-manager/cloud-driver/drivers/alibaba/resources/CommonHandler.go
- Add: Instance Type and Disk Availability API
- [AnyCall: Alibaba Availability APIs Guide](https://github.com/cloud-barista/cb-spider/wiki/AnyCall:-Alibaba-Availability-APIs-Guide)
- Related: #1540
=> [AnyCall:Alibaba] Add Instance Type and Disk Availability API

Dockerfile, api-runtime/rest-runtime/S3Rest.go, go.sum
=> [bugfix] fix escape in presigned url

cloud-control-manager/cloud-driver/drivers/azure/resources/VMHandler.go
- Related Issue: https://github.com/cloud-barista/cb-spider/issues/1544
- Task: Azure: Start VM 시 Root Disk Size Up 로직 개선
---
- #### Test Env.
```
Region/Zone: northeurope/1
Image: Canonical:UbuntuServer:18.04-LTS:18.04.202106220
Spec: Standard_B1ls
```
- #### (case-1): `default`
- 결과: 성공
- RootDisk Size: 30G
- 세부 내용
```
cb-user@azure-northeu-vm-7z8-d30gshu1pc4jk9aevh20:~$ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda       8:0    0   30G  0 disk   <============ Root Disk 
├─sda1    8:1    0 29.9G  0 part /
├─sda14   8:14   0    4M  0 part 
└─sda15   8:15   0  106M  0 part /boot/efi
sdb       8:16   0    4G  0 disk   <============ Temp Disk
└─sdb1    8:17   0    4G  0 part /mnt
sr0      11:0    1  630K  0 rom 
```
- #### (case-2): `10` (< `default`)
- 결과: 실패 
- 에러 메시지
``` …
```
=> [refactor] azure-vm-start-root-disk-logic

.gitignore, utils/memory-usage-analysis/README.md, utils/memory-usage-analysis/analyze_cb_spider_memory.py, utils/memory-usage-analysis/aws-image-test.cmd, utils/memory-usage-analysis/cmd-list.cmd, utils/memory-usage-analysis/cmd-single.cmd, utils/memory-usage-analysis/image-test.cmd, utils/memory-usage-analysis/ncp-price-test.cmd, utils/memory-usage-analysis/quick-test.cmd, utils/memory-usage-analysis/report.sh, utils/memory-usage-analysis/sample-cmd-list.cmd, utils/memory-usage-analysis/start.sh
- Add CB-Spider server memory usage analysis utility (scripts and Python tools).
- Enables automated measurement, logging, and reporting of API memory usage.
- Provides visual graphs and Excel reports for performance diagnostics.
=> [Utils] Add memory usage analysis utility

cloud-control-manager/cloud-driver/drivers/nhn/main/Test_Resources.go, cloud-control-manager/cloud-driver/drivers/nhn/resources/NLBHandler.go, cloud-control-manager/cloud-driver/drivers/nhn/resources/VPCHandler.go
Fixes #1554
1. Fixed CreateNLB timeout error by refactoring NLBHandler structure  
2. Fixed VPC deletion bug in VPCHandler
=> [NHN] NLB handler structure update and VPC handler delete function fix (#1554)
